/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ApiAgentVersionResponse, ApiErrorResponse, ApiQueryResponse, MsaReplyMetaOnly } from "../models/index";
import {
    ApiAgentVersionResponseFromJSON,
    ApiAgentVersionResponseToJSON,
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ApiQueryResponseFromJSON,
    ApiQueryResponseToJSON,
    MsaReplyMetaOnlyFromJSON,
    MsaReplyMetaOnlyToJSON,
} from "../models/index";

export interface AgentVersionsApiGetAgentVersionsV1Request {
    ids: Array<string>;
    projectId?: string;
}

export interface AgentVersionsApiQueryAgentVersionsV1Request {
    offset?: number;
    limit?: number;
    sort?: string;
    filter?: string;
    projectId?: string;
}

/**
 *
 */
export class AgentVersionsApi extends runtime.BaseAPI {
    /**
     * Retrieve agent version entities for the provided ids.
     */
    async getAgentVersionsV1Raw(
        requestParameters: AgentVersionsApiGetAgentVersionsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApiAgentVersionResponse>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getAgentVersionsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        if (requestParameters["projectId"] != null) {
            queryParameters["project_id"] = requestParameters["projectId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/entities/agent-versions/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAgentVersionResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve agent version entities for the provided ids.
     */
    async getAgentVersionsV1(ids: Array<string>, projectId?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAgentVersionResponse> {
        const response = await this.getAgentVersionsV1Raw({ ids: ids, projectId: projectId }, initOverrides);
        return await response.value();
    }

    /**
     * Query agent versions based on the provided filters.
     */
    async queryAgentVersionsV1Raw(
        requestParameters: AgentVersionsApiQueryAgentVersionsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApiQueryResponse>> {
        const queryParameters: any = {};

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["projectId"] != null) {
            queryParameters["project_id"] = requestParameters["projectId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/queries/agent-versions/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiQueryResponseFromJSON(jsonValue));
    }

    /**
     * Query agent versions based on the provided filters.
     */
    async queryAgentVersionsV1(
        offset?: number,
        limit?: number,
        sort?: string,
        filter?: string,
        projectId?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ApiQueryResponse> {
        const response = await this.queryAgentVersionsV1Raw({ offset: offset, limit: limit, sort: sort, filter: filter, projectId: projectId }, initOverrides);
        return await response.value();
    }
}
