/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ApiGetResourceApplicationFindingsResponse, MsaReplyMetaOnly } from "../models/index";
import { ApiGetResourceApplicationFindingsResponseFromJSON, ApiGetResourceApplicationFindingsResponseToJSON, MsaReplyMetaOnlyFromJSON, MsaReplyMetaOnlyToJSON } from "../models/index";

export interface AspmapiApiAspmCombinedApplicationFindingsRequest {
    authorization: string;
    gcrn: string;
    type: string;
    filter?: string;
    offset?: number;
    limit?: number;
    sort?: string;
}

/**
 *
 */
export class AspmapiApi extends runtime.BaseAPI {
    /**
     * Get findings of a given type for an application resource, with filtering, sorting and pagination.
     */
    async aspmCombinedApplicationFindingsRaw(
        requestParameters: AspmapiApiAspmCombinedApplicationFindingsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApiGetResourceApplicationFindingsResponse>> {
        if (requestParameters["authorization"] == null) {
            throw new runtime.RequiredError("authorization", 'Required parameter "authorization" was null or undefined when calling aspmCombinedApplicationFindings().');
        }

        if (requestParameters["gcrn"] == null) {
            throw new runtime.RequiredError("gcrn", 'Required parameter "gcrn" was null or undefined when calling aspmCombinedApplicationFindings().');
        }

        if (requestParameters["type"] == null) {
            throw new runtime.RequiredError("type", 'Required parameter "type" was null or undefined when calling aspmCombinedApplicationFindings().');
        }

        const queryParameters: any = {};

        if (requestParameters["gcrn"] != null) {
            queryParameters["gcrn"] = requestParameters["gcrn"];
        }

        if (requestParameters["type"] != null) {
            queryParameters["type"] = requestParameters["type"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters["authorization"] != null) {
            headerParameters["Authorization"] = String(requestParameters["authorization"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["cloud-security-assets:read"]);
        }

        const response = await this.request(
            {
                path: `/aspm/combined/aspm-application-findings/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiGetResourceApplicationFindingsResponseFromJSON(jsonValue));
    }

    /**
     * Get findings of a given type for an application resource, with filtering, sorting and pagination.
     */
    async aspmCombinedApplicationFindings(
        authorization: string,
        gcrn: string,
        type: string,
        filter?: string,
        offset?: number,
        limit?: number,
        sort?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ApiGetResourceApplicationFindingsResponse> {
        const response = await this.aspmCombinedApplicationFindingsRaw(
            { authorization: authorization, gcrn: gcrn, type: type, filter: filter, offset: offset, limit: limit, sort: sort },
            initOverrides,
        );
        return await response.value();
    }
}
