/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ApiBranchConfigGetResponse, ApiExchangeRequest, ModelApiResponse, MsaReplyMetaOnly, ScmintegrationRegisterAppPayload } from "../models/index";
import {
    ApiBranchConfigGetResponseFromJSON,
    ApiBranchConfigGetResponseToJSON,
    ApiExchangeRequestFromJSON,
    ApiExchangeRequestToJSON,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    MsaReplyMetaOnlyFromJSON,
    MsaReplyMetaOnlyToJSON,
    ScmintegrationRegisterAppPayloadFromJSON,
    ScmintegrationRegisterAppPayloadToJSON,
} from "../models/index";

export interface CodeSecurityScmIntegrationApiDeleteBranchConfigRequest {
    ids: string;
}

export interface CodeSecurityScmIntegrationApiDeleteExclusionRuleRequest {
    id: string;
}

export interface CodeSecurityScmIntegrationApiDeleteSCMConnectionRequest {
    uuid: string;
}

export interface CodeSecurityScmIntegrationApiExchangeGitHubAppCodeRequest {
    body: ApiExchangeRequest;
}

export interface CodeSecurityScmIntegrationApiGetBranchConfigRequest {
    connectionId: string;
    repositoryIds?: string;
}

export interface CodeSecurityScmIntegrationApiGetSCMConnectionRequest {
    uuid: string;
}

export interface CodeSecurityScmIntegrationApiListExclusionRulesRequest {
    connectionId: string;
}

export interface CodeSecurityScmIntegrationApiListSCMConnectionsRequest {
    provider?: string;
}

export interface CodeSecurityScmIntegrationApiRegisterSCMAppRequest {
    body: ScmintegrationRegisterAppPayload;
}

export interface CodeSecurityScmIntegrationApiTriggerSCMSyncRequest {
    uuid: string;
}

export interface CodeSecurityScmIntegrationApiUpdateBranchConfigRequest {
    id: string;
}

/**
 *
 */
export class CodeSecurityScmIntegrationApi extends runtime.BaseAPI {
    /**
     * Create a new branch config
     */
    async createBranchConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:write"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/branch-configs/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Create a new branch config
     */
    async createBranchConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.createBranchConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create an exclusion rule
     */
    async createExclusionRuleRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:write"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/exclusions/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Create an exclusion rule
     */
    async createExclusionRule(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.createExclusionRuleRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete a branch config, or exclude a specific repository from a connection-level config when repository_id query param is provided
     */
    async deleteBranchConfigRaw(
        requestParameters: CodeSecurityScmIntegrationApiDeleteBranchConfigRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling deleteBranchConfig().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:write"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/branch-configs/v1`,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Delete a branch config, or exclude a specific repository from a connection-level config when repository_id query param is provided
     */
    async deleteBranchConfig(ids: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.deleteBranchConfigRaw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Delete an exclusion rule
     */
    async deleteExclusionRuleRaw(
        requestParameters: CodeSecurityScmIntegrationApiDeleteExclusionRuleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters["id"] == null) {
            throw new runtime.RequiredError("id", 'Required parameter "id" was null or undefined when calling deleteExclusionRule().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:write"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/exclusions/v1/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"]))),
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Delete an exclusion rule
     */
    async deleteExclusionRule(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.deleteExclusionRuleRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Delete an SCM connection
     */
    async deleteSCMConnectionRaw(
        requestParameters: CodeSecurityScmIntegrationApiDeleteSCMConnectionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters["uuid"] == null) {
            throw new runtime.RequiredError("uuid", 'Required parameter "uuid" was null or undefined when calling deleteSCMConnection().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:write"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/connections/v1/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters["uuid"]))),
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Delete an SCM connection
     */
    async deleteSCMConnection(uuid: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.deleteSCMConnectionRaw({ uuid: uuid }, initOverrides);
        return await response.value();
    }

    /**
     * Exchange a GitHub App manifest code or complete registration after installation
     */
    async exchangeGitHubAppCodeRaw(
        requestParameters: CodeSecurityScmIntegrationApiExchangeGitHubAppCodeRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling exchangeGitHubAppCode().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:write"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/github-apps/exchange/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: ApiExchangeRequestToJSON(requestParameters["body"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Exchange a GitHub App manifest code or complete registration after installation
     */
    async exchangeGitHubAppCode(body: ApiExchangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.exchangeGitHubAppCodeRaw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Get branch config for a connection or repository
     */
    async getBranchConfigRaw(
        requestParameters: CodeSecurityScmIntegrationApiGetBranchConfigRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApiBranchConfigGetResponse>> {
        if (requestParameters["connectionId"] == null) {
            throw new runtime.RequiredError("connectionId", 'Required parameter "connectionId" was null or undefined when calling getBranchConfig().');
        }

        const queryParameters: any = {};

        if (requestParameters["connectionId"] != null) {
            queryParameters["connection_id"] = requestParameters["connectionId"];
        }

        if (requestParameters["repositoryIds"] != null) {
            queryParameters["repository_ids"] = requestParameters["repositoryIds"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:read"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/branch-configs/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiBranchConfigGetResponseFromJSON(jsonValue));
    }

    /**
     * Get branch config for a connection or repository
     */
    async getBranchConfig(connectionId: string, repositoryIds?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiBranchConfigGetResponse> {
        const response = await this.getBranchConfigRaw({ connectionId: connectionId, repositoryIds: repositoryIds }, initOverrides);
        return await response.value();
    }

    /**
     * Get an SCM connection by UUID
     */
    async getSCMConnectionRaw(
        requestParameters: CodeSecurityScmIntegrationApiGetSCMConnectionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters["uuid"] == null) {
            throw new runtime.RequiredError("uuid", 'Required parameter "uuid" was null or undefined when calling getSCMConnection().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:read"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/connections/v1/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters["uuid"]))),
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Get an SCM connection by UUID
     */
    async getSCMConnection(uuid: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.getSCMConnectionRaw({ uuid: uuid }, initOverrides);
        return await response.value();
    }

    /**
     * List exclusion rules for a connection
     */
    async listExclusionRulesRaw(
        requestParameters: CodeSecurityScmIntegrationApiListExclusionRulesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters["connectionId"] == null) {
            throw new runtime.RequiredError("connectionId", 'Required parameter "connectionId" was null or undefined when calling listExclusionRules().');
        }

        const queryParameters: any = {};

        if (requestParameters["connectionId"] != null) {
            queryParameters["connection_id"] = requestParameters["connectionId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:read"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/exclusions/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * List exclusion rules for a connection
     */
    async listExclusionRules(connectionId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.listExclusionRulesRaw({ connectionId: connectionId }, initOverrides);
        return await response.value();
    }

    /**
     * List SCM connections for a customer
     */
    async listSCMConnectionsRaw(
        requestParameters: CodeSecurityScmIntegrationApiListSCMConnectionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters["provider"] != null) {
            queryParameters["provider"] = requestParameters["provider"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:read"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/connections/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * List SCM connections for a customer
     */
    async listSCMConnections(provider?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.listSCMConnectionsRaw({ provider: provider }, initOverrides);
        return await response.value();
    }

    /**
     * Register a GitHub App via the wizard flow
     */
    async registerSCMAppRaw(
        requestParameters: CodeSecurityScmIntegrationApiRegisterSCMAppRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling registerSCMApp().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:write"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/registrations`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: ScmintegrationRegisterAppPayloadToJSON(requestParameters["body"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Register a GitHub App via the wizard flow
     */
    async registerSCMApp(body: ScmintegrationRegisterAppPayload, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.registerSCMAppRaw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Trigger an immediate sync for a connection
     */
    async triggerSCMSyncRaw(
        requestParameters: CodeSecurityScmIntegrationApiTriggerSCMSyncRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters["uuid"] == null) {
            throw new runtime.RequiredError("uuid", 'Required parameter "uuid" was null or undefined when calling triggerSCMSync().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:write"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/connections/v1/{uuid}/sync`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters["uuid"]))),
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Trigger an immediate sync for a connection
     */
    async triggerSCMSync(uuid: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.triggerSCMSyncRaw({ uuid: uuid }, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing branch config
     */
    async updateBranchConfigRaw(
        requestParameters: CodeSecurityScmIntegrationApiUpdateBranchConfigRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters["id"] == null) {
            throw new runtime.RequiredError("id", 'Required parameter "id" was null or undefined when calling updateBranchConfig().');
        }

        const queryParameters: any = {};

        if (requestParameters["id"] != null) {
            queryParameters["id"] = requestParameters["id"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["code-security-scm-integration:write"]);
        }

        const response = await this.request(
            {
                path: `/scm-integration/entities/branch-configs/v1`,
                method: "PATCH",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing branch config
     */
    async updateBranchConfig(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.updateBranchConfigRaw({ id: id }, initOverrides);
        return await response.value();
    }
}
