/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
    FalconidapiThirdPartyPasskeyRegistryDeleteResponseV1,
    FalconidapiThirdPartyPasskeyRegistryGetResponseV1,
    FalconidapiThirdPartyPasskeyRegistryPatchRequestV1,
    FalconidapiThirdPartyPasskeyRegistryPatchResponseV1,
    FalconidapiThirdPartyPasskeyRegistryQueryResponseV1,
    MsaReplyMetaOnly,
} from "../models/index";
import {
    FalconidapiThirdPartyPasskeyRegistryDeleteResponseV1FromJSON,
    FalconidapiThirdPartyPasskeyRegistryDeleteResponseV1ToJSON,
    FalconidapiThirdPartyPasskeyRegistryGetResponseV1FromJSON,
    FalconidapiThirdPartyPasskeyRegistryGetResponseV1ToJSON,
    FalconidapiThirdPartyPasskeyRegistryPatchRequestV1FromJSON,
    FalconidapiThirdPartyPasskeyRegistryPatchRequestV1ToJSON,
    FalconidapiThirdPartyPasskeyRegistryPatchResponseV1FromJSON,
    FalconidapiThirdPartyPasskeyRegistryPatchResponseV1ToJSON,
    FalconidapiThirdPartyPasskeyRegistryQueryResponseV1FromJSON,
    FalconidapiThirdPartyPasskeyRegistryQueryResponseV1ToJSON,
    MsaReplyMetaOnlyFromJSON,
    MsaReplyMetaOnlyToJSON,
} from "../models/index";

export interface FalconIdApiDeleteThirdPartyPasskeyRegistryRequest {
    ids: Array<string>;
}

export interface FalconIdApiGetThirdPartyPasskeyRegistryRequest {
    ids: Array<string>;
}

export interface FalconIdApiQueryThirdPartyPasskeyRegistryRequest {
    filter?: string;
    offset?: number;
    limit?: number;
    sort?: string;
}

export interface FalconIdApiUpdateThirdPartyPasskeyRegistryRequest {
    body: Array<FalconidapiThirdPartyPasskeyRegistryPatchRequestV1>;
}

/**
 *
 */
export class FalconIdApi extends runtime.BaseAPI {
    /**
     * Deletes third party passkey registries
     */
    async deleteThirdPartyPasskeyRegistryRaw(
        requestParameters: FalconIdApiDeleteThirdPartyPasskeyRegistryRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<FalconidapiThirdPartyPasskeyRegistryDeleteResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling deleteThirdPartyPasskeyRegistry().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["falcon-id:write"]);
        }

        const response = await this.request(
            {
                path: `/falcon-id/entities/third-party-passkeys/v1`,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => FalconidapiThirdPartyPasskeyRegistryDeleteResponseV1FromJSON(jsonValue));
    }

    /**
     * Deletes third party passkey registries
     */
    async deleteThirdPartyPasskeyRegistry(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FalconidapiThirdPartyPasskeyRegistryDeleteResponseV1> {
        const response = await this.deleteThirdPartyPasskeyRegistryRaw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Fetches third party passkey registries
     */
    async getThirdPartyPasskeyRegistryRaw(
        requestParameters: FalconIdApiGetThirdPartyPasskeyRegistryRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<FalconidapiThirdPartyPasskeyRegistryGetResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getThirdPartyPasskeyRegistry().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["falcon-id:read"]);
        }

        const response = await this.request(
            {
                path: `/falcon-id/entities/third-party-passkeys/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => FalconidapiThirdPartyPasskeyRegistryGetResponseV1FromJSON(jsonValue));
    }

    /**
     * Fetches third party passkey registries
     */
    async getThirdPartyPasskeyRegistry(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FalconidapiThirdPartyPasskeyRegistryGetResponseV1> {
        const response = await this.getThirdPartyPasskeyRegistryRaw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Query third party passkey registries
     */
    async queryThirdPartyPasskeyRegistryRaw(
        requestParameters: FalconIdApiQueryThirdPartyPasskeyRegistryRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<FalconidapiThirdPartyPasskeyRegistryQueryResponseV1>> {
        const queryParameters: any = {};

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["falcon-id:read"]);
        }

        const response = await this.request(
            {
                path: `/falcon-id/queries/third-party-passkeys/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => FalconidapiThirdPartyPasskeyRegistryQueryResponseV1FromJSON(jsonValue));
    }

    /**
     * Query third party passkey registries
     */
    async queryThirdPartyPasskeyRegistry(
        filter?: string,
        offset?: number,
        limit?: number,
        sort?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<FalconidapiThirdPartyPasskeyRegistryQueryResponseV1> {
        const response = await this.queryThirdPartyPasskeyRegistryRaw({ filter: filter, offset: offset, limit: limit, sort: sort }, initOverrides);
        return await response.value();
    }

    /**
     * Updates third party passkey registries
     */
    async updateThirdPartyPasskeyRegistryRaw(
        requestParameters: FalconIdApiUpdateThirdPartyPasskeyRegistryRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<FalconidapiThirdPartyPasskeyRegistryPatchResponseV1>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling updateThirdPartyPasskeyRegistry().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["falcon-id:write"]);
        }

        const response = await this.request(
            {
                path: `/falcon-id/entities/third-party-passkeys/v1`,
                method: "PATCH",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters["body"]!.map(FalconidapiThirdPartyPasskeyRegistryPatchRequestV1ToJSON),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => FalconidapiThirdPartyPasskeyRegistryPatchResponseV1FromJSON(jsonValue));
    }

    /**
     * Updates third party passkey registries
     */
    async updateThirdPartyPasskeyRegistry(
        body: Array<FalconidapiThirdPartyPasskeyRegistryPatchRequestV1>,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<FalconidapiThirdPartyPasskeyRegistryPatchResponseV1> {
        const response = await this.updateThirdPartyPasskeyRegistryRaw({ body: body }, initOverrides);
        return await response.value();
    }
}
