/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
    ApiErrorResponse,
    DomainReplyCombinedKnowledgeBaseAuditEventsResponse,
    DomainReplyEntitiesKnowledgeBaseAuditEventsResponse,
    DomainReplyQueryKnowledgeBaseAuditEventsResponse,
    MsaReplyMetaOnly,
} from "../models/index";
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    DomainReplyCombinedKnowledgeBaseAuditEventsResponseFromJSON,
    DomainReplyCombinedKnowledgeBaseAuditEventsResponseToJSON,
    DomainReplyEntitiesKnowledgeBaseAuditEventsResponseFromJSON,
    DomainReplyEntitiesKnowledgeBaseAuditEventsResponseToJSON,
    DomainReplyQueryKnowledgeBaseAuditEventsResponseFromJSON,
    DomainReplyQueryKnowledgeBaseAuditEventsResponseToJSON,
    MsaReplyMetaOnlyFromJSON,
    MsaReplyMetaOnlyToJSON,
} from "../models/index";

export interface KnowledgeBaseAuditEventsApiCombinedKnowledgeBaseAuditEventsV1Request {
    knowledgeBaseId: string;
    offset?: number;
    limit?: number;
    sort?: string;
    filter?: string;
    includeDeleted?: boolean;
    projectId?: string;
}

export interface KnowledgeBaseAuditEventsApiEntitiesKnowledgeBaseAuditEventsV1Request {
    knowledgeBaseId: string;
    ids: Array<string>;
    includeDeleted?: boolean;
    projectId?: string;
}

export interface KnowledgeBaseAuditEventsApiQueriesKnowledgeBaseAuditEventsV1Request {
    knowledgeBaseId: string;
    offset?: number;
    limit?: number;
    sort?: string;
    filter?: string;
    includeDeleted?: boolean;
    projectId?: string;
}

/**
 *
 */
export class KnowledgeBaseAuditEventsApi extends runtime.BaseAPI {
    /**
     * Get knowledge base audit events with full event details and pagination.
     */
    async combinedKnowledgeBaseAuditEventsV1Raw(
        requestParameters: KnowledgeBaseAuditEventsApiCombinedKnowledgeBaseAuditEventsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainReplyCombinedKnowledgeBaseAuditEventsResponse>> {
        if (requestParameters["knowledgeBaseId"] == null) {
            throw new runtime.RequiredError("knowledgeBaseId", 'Required parameter "knowledgeBaseId" was null or undefined when calling combinedKnowledgeBaseAuditEventsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["knowledgeBaseId"] != null) {
            queryParameters["knowledge_base_id"] = requestParameters["knowledgeBaseId"];
        }

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["includeDeleted"] != null) {
            queryParameters["include_deleted"] = requestParameters["includeDeleted"];
        }

        if (requestParameters["projectId"] != null) {
            queryParameters["project_id"] = requestParameters["projectId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/combined/knowledge_base_audit_events/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainReplyCombinedKnowledgeBaseAuditEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get knowledge base audit events with full event details and pagination.
     */
    async combinedKnowledgeBaseAuditEventsV1(
        knowledgeBaseId: string,
        offset?: number,
        limit?: number,
        sort?: string,
        filter?: string,
        includeDeleted?: boolean,
        projectId?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<DomainReplyCombinedKnowledgeBaseAuditEventsResponse> {
        const response = await this.combinedKnowledgeBaseAuditEventsV1Raw(
            { knowledgeBaseId: knowledgeBaseId, offset: offset, limit: limit, sort: sort, filter: filter, includeDeleted: includeDeleted, projectId: projectId },
            initOverrides,
        );
        return await response.value();
    }

    /**
     * Retrieve knowledge base audit event entities by their IDs.
     */
    async entitiesKnowledgeBaseAuditEventsV1Raw(
        requestParameters: KnowledgeBaseAuditEventsApiEntitiesKnowledgeBaseAuditEventsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainReplyEntitiesKnowledgeBaseAuditEventsResponse>> {
        if (requestParameters["knowledgeBaseId"] == null) {
            throw new runtime.RequiredError("knowledgeBaseId", 'Required parameter "knowledgeBaseId" was null or undefined when calling entitiesKnowledgeBaseAuditEventsV1().');
        }

        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling entitiesKnowledgeBaseAuditEventsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["knowledgeBaseId"] != null) {
            queryParameters["knowledge_base_id"] = requestParameters["knowledgeBaseId"];
        }

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        if (requestParameters["includeDeleted"] != null) {
            queryParameters["include_deleted"] = requestParameters["includeDeleted"];
        }

        if (requestParameters["projectId"] != null) {
            queryParameters["project_id"] = requestParameters["projectId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/entities/knowledge_base_audit_events/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainReplyEntitiesKnowledgeBaseAuditEventsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve knowledge base audit event entities by their IDs.
     */
    async entitiesKnowledgeBaseAuditEventsV1(
        knowledgeBaseId: string,
        ids: Array<string>,
        includeDeleted?: boolean,
        projectId?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<DomainReplyEntitiesKnowledgeBaseAuditEventsResponse> {
        const response = await this.entitiesKnowledgeBaseAuditEventsV1Raw({ knowledgeBaseId: knowledgeBaseId, ids: ids, includeDeleted: includeDeleted, projectId: projectId }, initOverrides);
        return await response.value();
    }

    /**
     * Query knowledge base audit event IDs with pagination and filtering.
     */
    async queriesKnowledgeBaseAuditEventsV1Raw(
        requestParameters: KnowledgeBaseAuditEventsApiQueriesKnowledgeBaseAuditEventsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainReplyQueryKnowledgeBaseAuditEventsResponse>> {
        if (requestParameters["knowledgeBaseId"] == null) {
            throw new runtime.RequiredError("knowledgeBaseId", 'Required parameter "knowledgeBaseId" was null or undefined when calling queriesKnowledgeBaseAuditEventsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["knowledgeBaseId"] != null) {
            queryParameters["knowledge_base_id"] = requestParameters["knowledgeBaseId"];
        }

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["includeDeleted"] != null) {
            queryParameters["include_deleted"] = requestParameters["includeDeleted"];
        }

        if (requestParameters["projectId"] != null) {
            queryParameters["project_id"] = requestParameters["projectId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/queries/knowledge_base_audit_events/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainReplyQueryKnowledgeBaseAuditEventsResponseFromJSON(jsonValue));
    }

    /**
     * Query knowledge base audit event IDs with pagination and filtering.
     */
    async queriesKnowledgeBaseAuditEventsV1(
        knowledgeBaseId: string,
        offset?: number,
        limit?: number,
        sort?: string,
        filter?: string,
        includeDeleted?: boolean,
        projectId?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<DomainReplyQueryKnowledgeBaseAuditEventsResponse> {
        const response = await this.queriesKnowledgeBaseAuditEventsV1Raw(
            { knowledgeBaseId: knowledgeBaseId, offset: offset, limit: limit, sort: sort, filter: filter, includeDeleted: includeDeleted, projectId: projectId },
            initOverrides,
        );
        return await response.value();
    }
}
