/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ApiEntitiesModelsResponse, ApiErrorResponse, ApiQueryResponse, MsaReplyMetaOnly } from "../models/index";
import {
    ApiEntitiesModelsResponseFromJSON,
    ApiEntitiesModelsResponseToJSON,
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ApiQueryResponseFromJSON,
    ApiQueryResponseToJSON,
    MsaReplyMetaOnlyFromJSON,
    MsaReplyMetaOnlyToJSON,
} from "../models/index";

export interface ModelsApiEntitiesModelsV1Request {
    ids: Array<string>;
}

export interface ModelsApiQueriesModelsV1Request {
    offset?: number;
    limit?: number;
    filter?: string;
}

/**
 *
 */
export class ModelsApi extends runtime.BaseAPI {
    /**
     * Get Model Entities by IDs
     */
    async entitiesModelsV1Raw(
        requestParameters: ModelsApiEntitiesModelsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApiEntitiesModelsResponse>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling entitiesModelsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/entities/models/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiEntitiesModelsResponseFromJSON(jsonValue));
    }

    /**
     * Get Model Entities by IDs
     */
    async entitiesModelsV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEntitiesModelsResponse> {
        const response = await this.entitiesModelsV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Query models based on the provided filters.
     */
    async queriesModelsV1Raw(requestParameters: ModelsApiQueriesModelsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiQueryResponse>> {
        const queryParameters: any = {};

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/queries/models/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiQueryResponseFromJSON(jsonValue));
    }

    /**
     * Query models based on the provided filters.
     */
    async queriesModelsV1(offset?: number, limit?: number, filter?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiQueryResponse> {
        const response = await this.queriesModelsV1Raw({ offset: offset, limit: limit, filter: filter }, initOverrides);
        return await response.value();
    }
}
