/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ApiErrorResponse, DomainReplyEntitiesSkillsResponse, DomainReplyQuerySkillsResponse, MsaReplyMetaOnly, MsaspecResponseFields } from "../models/index";
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    DomainReplyEntitiesSkillsResponseFromJSON,
    DomainReplyEntitiesSkillsResponseToJSON,
    DomainReplyQuerySkillsResponseFromJSON,
    DomainReplyQuerySkillsResponseToJSON,
    MsaReplyMetaOnlyFromJSON,
    MsaReplyMetaOnlyToJSON,
    MsaspecResponseFieldsFromJSON,
    MsaspecResponseFieldsToJSON,
} from "../models/index";

export interface SkillsApiEntitiesSkillsCreateV1Request {
    skillBlob: Blob;
    projectId?: string;
}

export interface SkillsApiEntitiesSkillsDeleteV1Request {
    id: string;
    projectId?: string;
}

export interface SkillsApiEntitiesSkillsDownloadV2Request {
    id: string;
    includeDeleted?: boolean;
    projectId?: string;
}

export interface SkillsApiEntitiesSkillsUpdateV1Request {
    id: string;
    skillBlob: Blob;
    projectId?: string;
}

export interface SkillsApiEntitiesSkillsV1Request {
    ids: Array<string>;
    includeDeleted?: boolean;
    projectId?: string;
}

export interface SkillsApiQueriesSkillsV1Request {
    offset?: number;
    limit?: number;
    sort?: string;
    filter?: string;
    includeDeleted?: boolean;
    projectId?: string;
}

/**
 *
 */
export class SkillsApi extends runtime.BaseAPI {
    /**
     * Upload a new skill as a zip archive.
     */
    async entitiesSkillsCreateV1Raw(
        requestParameters: SkillsApiEntitiesSkillsCreateV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainReplyEntitiesSkillsResponse>> {
        if (requestParameters["skillBlob"] == null) {
            throw new runtime.RequiredError("skillBlob", 'Required parameter "skillBlob" was null or undefined when calling entitiesSkillsCreateV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:write"]);
        }

        const consumes: runtime.Consume[] = [{ contentType: "multipart/form-data" }];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters["skillBlob"] != null) {
            formParams.append("skill_blob", requestParameters["skillBlob"] as any);
        }

        if (requestParameters["projectId"] != null) {
            formParams.append("project_id", requestParameters["projectId"] as any);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/entities/skills/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: formParams,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainReplyEntitiesSkillsResponseFromJSON(jsonValue));
    }

    /**
     * Upload a new skill as a zip archive.
     */
    async entitiesSkillsCreateV1(skillBlob: Blob, projectId?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainReplyEntitiesSkillsResponse> {
        const response = await this.entitiesSkillsCreateV1Raw({ skillBlob: skillBlob, projectId: projectId }, initOverrides);
        return await response.value();
    }

    /**
     * Delete a skill by its ID.
     */
    async entitiesSkillsDeleteV1Raw(
        requestParameters: SkillsApiEntitiesSkillsDeleteV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<MsaspecResponseFields>> {
        if (requestParameters["id"] == null) {
            throw new runtime.RequiredError("id", 'Required parameter "id" was null or undefined when calling entitiesSkillsDeleteV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["id"] != null) {
            queryParameters["id"] = requestParameters["id"];
        }

        if (requestParameters["projectId"] != null) {
            queryParameters["project_id"] = requestParameters["projectId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:write"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/entities/skills/v1`,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => MsaspecResponseFieldsFromJSON(jsonValue));
    }

    /**
     * Delete a skill by its ID.
     */
    async entitiesSkillsDeleteV1(id: string, projectId?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MsaspecResponseFields> {
        const response = await this.entitiesSkillsDeleteV1Raw({ id: id, projectId: projectId }, initOverrides);
        return await response.value();
    }

    /**
     * Download a single skill blob as a zip archive.
     */
    async entitiesSkillsDownloadV2Raw(requestParameters: SkillsApiEntitiesSkillsDownloadV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["id"] == null) {
            throw new runtime.RequiredError("id", 'Required parameter "id" was null or undefined when calling entitiesSkillsDownloadV2().');
        }

        const queryParameters: any = {};

        if (requestParameters["id"] != null) {
            queryParameters["id"] = requestParameters["id"];
        }

        if (requestParameters["includeDeleted"] != null) {
            queryParameters["include_deleted"] = requestParameters["includeDeleted"];
        }

        if (requestParameters["projectId"] != null) {
            queryParameters["project_id"] = requestParameters["projectId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/entities/skills/download/v2`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Download a single skill blob as a zip archive.
     */
    async entitiesSkillsDownloadV2(id: string, includeDeleted?: boolean, projectId?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.entitiesSkillsDownloadV2Raw({ id: id, includeDeleted: includeDeleted, projectId: projectId }, initOverrides);
    }

    /**
     * Update an existing skill with a new zip archive.
     */
    async entitiesSkillsUpdateV1Raw(
        requestParameters: SkillsApiEntitiesSkillsUpdateV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainReplyEntitiesSkillsResponse>> {
        if (requestParameters["id"] == null) {
            throw new runtime.RequiredError("id", 'Required parameter "id" was null or undefined when calling entitiesSkillsUpdateV1().');
        }

        if (requestParameters["skillBlob"] == null) {
            throw new runtime.RequiredError("skillBlob", 'Required parameter "skillBlob" was null or undefined when calling entitiesSkillsUpdateV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:write"]);
        }

        const consumes: runtime.Consume[] = [{ contentType: "multipart/form-data" }];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters["id"] != null) {
            formParams.append("id", requestParameters["id"] as any);
        }

        if (requestParameters["skillBlob"] != null) {
            formParams.append("skill_blob", requestParameters["skillBlob"] as any);
        }

        if (requestParameters["projectId"] != null) {
            formParams.append("project_id", requestParameters["projectId"] as any);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/entities/skills/v1`,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: formParams,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainReplyEntitiesSkillsResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing skill with a new zip archive.
     */
    async entitiesSkillsUpdateV1(id: string, skillBlob: Blob, projectId?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainReplyEntitiesSkillsResponse> {
        const response = await this.entitiesSkillsUpdateV1Raw({ id: id, skillBlob: skillBlob, projectId: projectId }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve skill entities for the provided IDs.
     */
    async entitiesSkillsV1Raw(
        requestParameters: SkillsApiEntitiesSkillsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainReplyEntitiesSkillsResponse>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling entitiesSkillsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        if (requestParameters["includeDeleted"] != null) {
            queryParameters["include_deleted"] = requestParameters["includeDeleted"];
        }

        if (requestParameters["projectId"] != null) {
            queryParameters["project_id"] = requestParameters["projectId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/entities/skills/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainReplyEntitiesSkillsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve skill entities for the provided IDs.
     */
    async entitiesSkillsV1(ids: Array<string>, includeDeleted?: boolean, projectId?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainReplyEntitiesSkillsResponse> {
        const response = await this.entitiesSkillsV1Raw({ ids: ids, includeDeleted: includeDeleted, projectId: projectId }, initOverrides);
        return await response.value();
    }

    /**
     * Query skills based on the provided filters.
     */
    async queriesSkillsV1Raw(
        requestParameters: SkillsApiQueriesSkillsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainReplyQuerySkillsResponse>> {
        const queryParameters: any = {};

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["includeDeleted"] != null) {
            queryParameters["include_deleted"] = requestParameters["includeDeleted"];
        }

        if (requestParameters["projectId"] != null) {
            queryParameters["project_id"] = requestParameters["projectId"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["charlotte-ai-agent-definition:read"]);
        }

        const response = await this.request(
            {
                path: `/agentic-studio/queries/skills/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainReplyQuerySkillsResponseFromJSON(jsonValue));
    }

    /**
     * Query skills based on the provided filters.
     */
    async queriesSkillsV1(
        offset?: number,
        limit?: number,
        sort?: string,
        filter?: string,
        includeDeleted?: boolean,
        projectId?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<DomainReplyQuerySkillsResponse> {
        const response = await this.queriesSkillsV1Raw({ offset: offset, limit: limit, sort: sort, filter: filter, includeDeleted: includeDeleted, projectId: projectId }, initOverrides);
        return await response.value();
    }
}
