/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Meta } from "./Meta";
import { MetaFromJSON, MetaFromJSONTyped, MetaToJSON } from "./Meta";
import type { UrlDomainListResult } from "./UrlDomainListResult";
import { UrlDomainListResultFromJSON, UrlDomainListResultFromJSONTyped, UrlDomainListResultToJSON } from "./UrlDomainListResult";
import type { APIError } from "./APIError";
import { APIErrorFromJSON, APIErrorFromJSONTyped, APIErrorToJSON } from "./APIError";

/**
 *
 * @export
 * @interface AddUrlDomainList200Response
 */
export interface AddUrlDomainList200Response {
    /**
     * Per-resource failures. Present and empty when the whole request succeeded. The get-by-ID operations report partial success here: IDs that could not be resolved appear as individual entries while the records that were found are still returned in resources.
     * @type {Array<APIError>}
     * @memberof AddUrlDomainList200Response
     */
    errors: Array<APIError>;
    /**
     *
     * @type {Meta}
     * @memberof AddUrlDomainList200Response
     */
    meta: Meta;
    /**
     *
     * @type {Array<UrlDomainListResult>}
     * @memberof AddUrlDomainList200Response
     */
    resources: Array<UrlDomainListResult>;
}

/**
 * Check if a given object implements the AddUrlDomainList200Response interface.
 */
export function instanceOfAddUrlDomainList200Response(value: object): value is AddUrlDomainList200Response {
    if (!("errors" in value) || value["errors"] === undefined) return false;
    if (!("meta" in value) || value["meta"] === undefined) return false;
    if (!("resources" in value) || value["resources"] === undefined) return false;
    return true;
}

export function AddUrlDomainList200ResponseFromJSON(json: any): AddUrlDomainList200Response {
    return AddUrlDomainList200ResponseFromJSONTyped(json, false);
}

export function AddUrlDomainList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUrlDomainList200Response {
    if (json == null) {
        return json;
    }
    return {
        errors: (json["errors"] as Array<any>).map(APIErrorFromJSON),
        meta: MetaFromJSON(json["meta"]),
        resources: (json["resources"] as Array<any>).map(UrlDomainListResultFromJSON),
    };
}

export function AddUrlDomainList200ResponseToJSON(value?: AddUrlDomainList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        errors: (value["errors"] as Array<any>).map(APIErrorToJSON),
        meta: MetaToJSON(value["meta"]),
        resources: (value["resources"] as Array<any>).map(UrlDomainListResultToJSON),
    };
}
