/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiAgentVersionDefinitionRequest } from "./ApiAgentVersionDefinitionRequest";
import { ApiAgentVersionDefinitionRequestFromJSON, ApiAgentVersionDefinitionRequestFromJSONTyped, ApiAgentVersionDefinitionRequestToJSON } from "./ApiAgentVersionDefinitionRequest";

/**
 *
 * @export
 * @interface ApiAgentTemplateEntry
 */
export interface ApiAgentTemplateEntry {
    /**
     *
     * @type {string}
     * @memberof ApiAgentTemplateEntry
     */
    author: string;
    /**
     *
     * @type {Date}
     * @memberof ApiAgentTemplateEntry
     */
    createdAt: Date;
    /**
     *
     * @type {string}
     * @memberof ApiAgentTemplateEntry
     */
    description: string;
    /**
     *
     * @type {string}
     * @memberof ApiAgentTemplateEntry
     */
    documentation: string;
    /**
     *
     * @type {string}
     * @memberof ApiAgentTemplateEntry
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ApiAgentTemplateEntry
     */
    model: string;
    /**
     *
     * @type {string}
     * @memberof ApiAgentTemplateEntry
     */
    name: string;
    /**
     *
     * @type {Array<string>}
     * @memberof ApiAgentTemplateEntry
     */
    products: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof ApiAgentTemplateEntry
     */
    targeting: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof ApiAgentTemplateEntry
     */
    tools: Array<string>;
    /**
     *
     * @type {Date}
     * @memberof ApiAgentTemplateEntry
     */
    updatedAt: Date;
    /**
     *
     * @type {Array<string>}
     * @memberof ApiAgentTemplateEntry
     */
    useCases: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof ApiAgentTemplateEntry
     */
    vendors: Array<string>;
    /**
     *
     * @type {string}
     * @memberof ApiAgentTemplateEntry
     */
    version: string;
    /**
     *
     * @type {ApiAgentVersionDefinitionRequest}
     * @memberof ApiAgentTemplateEntry
     */
    versionDefinition: ApiAgentVersionDefinitionRequest;
}

/**
 * Check if a given object implements the ApiAgentTemplateEntry interface.
 */
export function instanceOfApiAgentTemplateEntry(value: object): value is ApiAgentTemplateEntry {
    if (!("author" in value) || value["author"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("description" in value) || value["description"] === undefined) return false;
    if (!("documentation" in value) || value["documentation"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("model" in value) || value["model"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("products" in value) || value["products"] === undefined) return false;
    if (!("targeting" in value) || value["targeting"] === undefined) return false;
    if (!("tools" in value) || value["tools"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    if (!("useCases" in value) || value["useCases"] === undefined) return false;
    if (!("vendors" in value) || value["vendors"] === undefined) return false;
    if (!("version" in value) || value["version"] === undefined) return false;
    if (!("versionDefinition" in value) || value["versionDefinition"] === undefined) return false;
    return true;
}

export function ApiAgentTemplateEntryFromJSON(json: any): ApiAgentTemplateEntry {
    return ApiAgentTemplateEntryFromJSONTyped(json, false);
}

export function ApiAgentTemplateEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAgentTemplateEntry {
    if (json == null) {
        return json;
    }
    return {
        author: json["author"],
        createdAt: new Date(json["created_at"]),
        description: json["description"],
        documentation: json["documentation"],
        id: json["id"],
        model: json["model"],
        name: json["name"],
        products: json["products"],
        targeting: json["targeting"],
        tools: json["tools"],
        updatedAt: new Date(json["updated_at"]),
        useCases: json["use_cases"],
        vendors: json["vendors"],
        version: json["version"],
        versionDefinition: ApiAgentVersionDefinitionRequestFromJSON(json["version_definition"]),
    };
}

export function ApiAgentTemplateEntryToJSON(value?: ApiAgentTemplateEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        author: value["author"],
        created_at: value["createdAt"].toISOString(),
        description: value["description"],
        documentation: value["documentation"],
        id: value["id"],
        model: value["model"],
        name: value["name"],
        products: value["products"],
        targeting: value["targeting"],
        tools: value["tools"],
        updated_at: value["updatedAt"].toISOString(),
        use_cases: value["useCases"],
        vendors: value["vendors"],
        version: value["version"],
        version_definition: ApiAgentVersionDefinitionRequestToJSON(value["versionDefinition"]),
    };
}
