/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiBulkCreateDashboardItem } from "./ApiBulkCreateDashboardItem";
import { ApiBulkCreateDashboardItemFromJSON, ApiBulkCreateDashboardItemFromJSONTyped, ApiBulkCreateDashboardItemToJSON } from "./ApiBulkCreateDashboardItem";

/**
 *
 * @export
 * @interface ApiBulkCreateDashboardsFromTemplateRequestV1
 */
export interface ApiBulkCreateDashboardsFromTemplateRequestV1 {
    /**
     * List of dashboards to create
     * @type {Array<ApiBulkCreateDashboardItem>}
     * @memberof ApiBulkCreateDashboardsFromTemplateRequestV1
     */
    dashboardItems: Array<ApiBulkCreateDashboardItem>;
    /**
     * The name of the search domain where the dashboards will be created
     * @type {string}
     * @memberof ApiBulkCreateDashboardsFromTemplateRequestV1
     */
    searchDomain: string;
}

/**
 * Check if a given object implements the ApiBulkCreateDashboardsFromTemplateRequestV1 interface.
 */
export function instanceOfApiBulkCreateDashboardsFromTemplateRequestV1(value: object): value is ApiBulkCreateDashboardsFromTemplateRequestV1 {
    if (!("dashboardItems" in value) || value["dashboardItems"] === undefined) return false;
    if (!("searchDomain" in value) || value["searchDomain"] === undefined) return false;
    return true;
}

export function ApiBulkCreateDashboardsFromTemplateRequestV1FromJSON(json: any): ApiBulkCreateDashboardsFromTemplateRequestV1 {
    return ApiBulkCreateDashboardsFromTemplateRequestV1FromJSONTyped(json, false);
}

export function ApiBulkCreateDashboardsFromTemplateRequestV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiBulkCreateDashboardsFromTemplateRequestV1 {
    if (json == null) {
        return json;
    }
    return {
        dashboardItems: (json["dashboard_items"] as Array<any>).map(ApiBulkCreateDashboardItemFromJSON),
        searchDomain: json["search_domain"],
    };
}

export function ApiBulkCreateDashboardsFromTemplateRequestV1ToJSON(value?: ApiBulkCreateDashboardsFromTemplateRequestV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        dashboard_items: (value["dashboardItems"] as Array<any>).map(ApiBulkCreateDashboardItemToJSON),
        search_domain: value["searchDomain"],
    };
}
