/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ApiCreateScheduledReportLayoutInputV1
 */
export interface ApiCreateScheduledReportLayoutInputV1 {
    /**
     * Show footer page numbers
     * @type {boolean}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    footerShowPageNumbers: boolean;
    /**
     * Max rows in tables
     * @type {number}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    maxNumberOfRows: number;
    /**
     * Layout: List or Grid
     * @type {string}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    paperLayout: string;
    /**
     * Orientation: Landscape or Portrait
     * @type {string}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    paperOrientation: string;
    /**
     * Paper size: A4 or Letter
     * @type {string}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    paperSize: string;
    /**
     * Show report description
     * @type {boolean}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    showDescription: boolean;
    /**
     * Show export date
     * @type {boolean}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    showExportDate: boolean;
    /**
     * Show parameters
     * @type {boolean}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    showParameters: boolean;
    /**
     * Show title on frontpage
     * @type {boolean}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    showTitleFrontpage: boolean;
    /**
     * Show title header
     * @type {boolean}
     * @memberof ApiCreateScheduledReportLayoutInputV1
     */
    showTitleHeader: boolean;
}

/**
 * Check if a given object implements the ApiCreateScheduledReportLayoutInputV1 interface.
 */
export function instanceOfApiCreateScheduledReportLayoutInputV1(value: object): value is ApiCreateScheduledReportLayoutInputV1 {
    if (!("footerShowPageNumbers" in value) || value["footerShowPageNumbers"] === undefined) return false;
    if (!("maxNumberOfRows" in value) || value["maxNumberOfRows"] === undefined) return false;
    if (!("paperLayout" in value) || value["paperLayout"] === undefined) return false;
    if (!("paperOrientation" in value) || value["paperOrientation"] === undefined) return false;
    if (!("paperSize" in value) || value["paperSize"] === undefined) return false;
    if (!("showDescription" in value) || value["showDescription"] === undefined) return false;
    if (!("showExportDate" in value) || value["showExportDate"] === undefined) return false;
    if (!("showParameters" in value) || value["showParameters"] === undefined) return false;
    if (!("showTitleFrontpage" in value) || value["showTitleFrontpage"] === undefined) return false;
    if (!("showTitleHeader" in value) || value["showTitleHeader"] === undefined) return false;
    return true;
}

export function ApiCreateScheduledReportLayoutInputV1FromJSON(json: any): ApiCreateScheduledReportLayoutInputV1 {
    return ApiCreateScheduledReportLayoutInputV1FromJSONTyped(json, false);
}

export function ApiCreateScheduledReportLayoutInputV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCreateScheduledReportLayoutInputV1 {
    if (json == null) {
        return json;
    }
    return {
        footerShowPageNumbers: json["footer_show_page_numbers"],
        maxNumberOfRows: json["max_number_of_rows"],
        paperLayout: json["paper_layout"],
        paperOrientation: json["paper_orientation"],
        paperSize: json["paper_size"],
        showDescription: json["show_description"],
        showExportDate: json["show_export_date"],
        showParameters: json["show_parameters"],
        showTitleFrontpage: json["show_title_frontpage"],
        showTitleHeader: json["show_title_header"],
    };
}

export function ApiCreateScheduledReportLayoutInputV1ToJSON(value?: ApiCreateScheduledReportLayoutInputV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        footer_show_page_numbers: value["footerShowPageNumbers"],
        max_number_of_rows: value["maxNumberOfRows"],
        paper_layout: value["paperLayout"],
        paper_orientation: value["paperOrientation"],
        paper_size: value["paperSize"],
        show_description: value["showDescription"],
        show_export_date: value["showExportDate"],
        show_parameters: value["showParameters"],
        show_title_frontpage: value["showTitleFrontpage"],
        show_title_header: value["showTitleHeader"],
    };
}
