/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiPersistedAggregationSchedule } from "./ApiPersistedAggregationSchedule";
import { ApiPersistedAggregationScheduleFromJSON, ApiPersistedAggregationScheduleFromJSONTyped, ApiPersistedAggregationScheduleToJSON } from "./ApiPersistedAggregationSchedule";

/**
 *
 * @export
 * @interface ApiCreatePersistedAggregationRequestV1
 */
export interface ApiCreatePersistedAggregationRequestV1 {
    /**
     * Optional description (max 1024 chars)
     * @type {string}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    description?: string;
    /**
     * Destination PA repository name (must be a repository of kind PersistedAggregation)
     * @type {string}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    destination: string;
    /**
     * Enable immediately
     * @type {boolean}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    enabled: boolean;
    /**
     * Optional labels (max 64 chars each)
     * @type {Array<string>}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    labels?: Array<string>;
    /**
     * Display name (alphanumeric start, max 128 chars)
     * @type {string}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    name: string;
    /**
     * Ownership type (defaults to 'Organization' if not specified; valid values: 'Organization', 'User')
     * @type {string}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    queryOwnershipType?: string;
    /**
     * LogScale query
     * @type {string}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    queryString: string;
    /**
     *
     * @type {ApiPersistedAggregationSchedule}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    schedule: ApiPersistedAggregationSchedule;
    /**
     * Search domain (view or repository) name to query
     * @type {string}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    searchDomain: string;
    /**
     * Optional static key-value fields (max 20)
     * @type {Array<{ [key: string]: string; }>}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    staticFields?: Array<{ [key: string]: string }>;
    /**
     * Unique tag identifier (alphanumeric, underscore, hyphen, period; max 128 chars; must start with letter)
     * @type {string}
     * @memberof ApiCreatePersistedAggregationRequestV1
     */
    tag: string;
}

/**
 * Check if a given object implements the ApiCreatePersistedAggregationRequestV1 interface.
 */
export function instanceOfApiCreatePersistedAggregationRequestV1(value: object): value is ApiCreatePersistedAggregationRequestV1 {
    if (!("destination" in value) || value["destination"] === undefined) return false;
    if (!("enabled" in value) || value["enabled"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("queryString" in value) || value["queryString"] === undefined) return false;
    if (!("schedule" in value) || value["schedule"] === undefined) return false;
    if (!("searchDomain" in value) || value["searchDomain"] === undefined) return false;
    if (!("tag" in value) || value["tag"] === undefined) return false;
    return true;
}

export function ApiCreatePersistedAggregationRequestV1FromJSON(json: any): ApiCreatePersistedAggregationRequestV1 {
    return ApiCreatePersistedAggregationRequestV1FromJSONTyped(json, false);
}

export function ApiCreatePersistedAggregationRequestV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCreatePersistedAggregationRequestV1 {
    if (json == null) {
        return json;
    }
    return {
        description: json["description"] == null ? undefined : json["description"],
        destination: json["destination"],
        enabled: json["enabled"],
        labels: json["labels"] == null ? undefined : json["labels"],
        name: json["name"],
        queryOwnershipType: json["query_ownership_type"] == null ? undefined : json["query_ownership_type"],
        queryString: json["query_string"],
        schedule: ApiPersistedAggregationScheduleFromJSON(json["schedule"]),
        searchDomain: json["search_domain"],
        staticFields: json["static_fields"] == null ? undefined : json["static_fields"],
        tag: json["tag"],
    };
}

export function ApiCreatePersistedAggregationRequestV1ToJSON(value?: ApiCreatePersistedAggregationRequestV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        description: value["description"],
        destination: value["destination"],
        enabled: value["enabled"],
        labels: value["labels"],
        name: value["name"],
        query_ownership_type: value["queryOwnershipType"],
        query_string: value["queryString"],
        schedule: ApiPersistedAggregationScheduleToJSON(value["schedule"]),
        search_domain: value["searchDomain"],
        static_fields: value["staticFields"],
        tag: value["tag"],
    };
}
