/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ApiFileLabelResourceV1
 */
export interface ApiFileLabelResourceV1 {
    /**
     * The name of the lookup file
     * @type {string}
     * @memberof ApiFileLabelResourceV1
     */
    filename: string;
    /**
     * The current labels on the file
     * @type {Array<string>}
     * @memberof ApiFileLabelResourceV1
     */
    labels: Array<string>;
}

/**
 * Check if a given object implements the ApiFileLabelResourceV1 interface.
 */
export function instanceOfApiFileLabelResourceV1(value: object): value is ApiFileLabelResourceV1 {
    if (!("filename" in value) || value["filename"] === undefined) return false;
    if (!("labels" in value) || value["labels"] === undefined) return false;
    return true;
}

export function ApiFileLabelResourceV1FromJSON(json: any): ApiFileLabelResourceV1 {
    return ApiFileLabelResourceV1FromJSONTyped(json, false);
}

export function ApiFileLabelResourceV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiFileLabelResourceV1 {
    if (json == null) {
        return json;
    }
    return {
        filename: json["filename"],
        labels: json["labels"],
    };
}

export function ApiFileLabelResourceV1ToJSON(value?: ApiFileLabelResourceV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        filename: value["filename"],
        labels: value["labels"],
    };
}
