/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiMessage } from "./ApiMessage";
import { ApiMessageFromJSON, ApiMessageFromJSONTyped, ApiMessageToJSON } from "./ApiMessage";

/**
 *
 * @export
 * @interface ApiInvokeAgentVersionExternalRequest
 */
export interface ApiInvokeAgentVersionExternalRequest {
    /**
     *
     * @type {number}
     * @memberof ApiInvokeAgentVersionExternalRequest
     */
    creditCentsLimit?: number;
    /**
     *
     * @type {number}
     * @memberof ApiInvokeAgentVersionExternalRequest
     */
    deadlineSeconds?: number;
    /**
     *
     * @type {string}
     * @memberof ApiInvokeAgentVersionExternalRequest
     */
    id: string;
    /**
     *
     * @type {Array<ApiMessage>}
     * @memberof ApiInvokeAgentVersionExternalRequest
     */
    messages: Array<ApiMessage>;
    /**
     *
     * @type {string}
     * @memberof ApiInvokeAgentVersionExternalRequest
     */
    projectId?: string;
    /**
     *
     * @type {string}
     * @memberof ApiInvokeAgentVersionExternalRequest
     */
    versionId: string;
}

/**
 * Check if a given object implements the ApiInvokeAgentVersionExternalRequest interface.
 */
export function instanceOfApiInvokeAgentVersionExternalRequest(value: object): value is ApiInvokeAgentVersionExternalRequest {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("messages" in value) || value["messages"] === undefined) return false;
    if (!("versionId" in value) || value["versionId"] === undefined) return false;
    return true;
}

export function ApiInvokeAgentVersionExternalRequestFromJSON(json: any): ApiInvokeAgentVersionExternalRequest {
    return ApiInvokeAgentVersionExternalRequestFromJSONTyped(json, false);
}

export function ApiInvokeAgentVersionExternalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiInvokeAgentVersionExternalRequest {
    if (json == null) {
        return json;
    }
    return {
        creditCentsLimit: json["credit_cents_limit"] == null ? undefined : json["credit_cents_limit"],
        deadlineSeconds: json["deadline_seconds"] == null ? undefined : json["deadline_seconds"],
        id: json["id"],
        messages: (json["messages"] as Array<any>).map(ApiMessageFromJSON),
        projectId: json["project_id"] == null ? undefined : json["project_id"],
        versionId: json["version_id"],
    };
}

export function ApiInvokeAgentVersionExternalRequestToJSON(value?: ApiInvokeAgentVersionExternalRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        credit_cents_limit: value["creditCentsLimit"],
        deadline_seconds: value["deadlineSeconds"],
        id: value["id"],
        messages: (value["messages"] as Array<any>).map(ApiMessageToJSON),
        project_id: value["projectId"],
        version_id: value["versionId"],
    };
}
