/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ApiPatchAgentRequest
 */
export interface ApiPatchAgentRequest {
    /**
     *
     * @type {boolean}
     * @memberof ApiPatchAgentRequest
     */
    isEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ApiPatchAgentRequest
     */
    isPublished: boolean;
    /**
     *
     * @type {string}
     * @memberof ApiPatchAgentRequest
     */
    versionId: string;
}

/**
 * Check if a given object implements the ApiPatchAgentRequest interface.
 */
export function instanceOfApiPatchAgentRequest(value: object): value is ApiPatchAgentRequest {
    if (!("isPublished" in value) || value["isPublished"] === undefined) return false;
    if (!("versionId" in value) || value["versionId"] === undefined) return false;
    return true;
}

export function ApiPatchAgentRequestFromJSON(json: any): ApiPatchAgentRequest {
    return ApiPatchAgentRequestFromJSONTyped(json, false);
}

export function ApiPatchAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPatchAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        isEnabled: json["is_enabled"] == null ? undefined : json["is_enabled"],
        isPublished: json["is_published"],
        versionId: json["version_id"],
    };
}

export function ApiPatchAgentRequestToJSON(value?: ApiPatchAgentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        is_enabled: value["isEnabled"],
        is_published: value["isPublished"],
        version_id: value["versionId"],
    };
}
