/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ApiPersistedAggregationSchedule
 */
export interface ApiPersistedAggregationSchedule {
    /**
     * Optional backfill amount (if omitted, no backfill)
     * @type {number}
     * @memberof ApiPersistedAggregationSchedule
     */
    backfillAmount?: number;
    /**
     * Backfill unit (required if backfill_amount provided)
     * @type {string}
     * @memberof ApiPersistedAggregationSchedule
     */
    backfillUnit?: string;
    /**
     * Schedule interval (e.g., 'hourly', 'daily')
     * @type {string}
     * @memberof ApiPersistedAggregationSchedule
     */
    interval: string;
    /**
     * Optional offset in seconds (only for EventTime)
     * @type {number}
     * @memberof ApiPersistedAggregationSchedule
     */
    offsetSeconds?: number;
    /**
     * Timestamp type ('EventTime' or 'IngestTime')
     * @type {string}
     * @memberof ApiPersistedAggregationSchedule
     */
    timestampType: string;
}

/**
 * Check if a given object implements the ApiPersistedAggregationSchedule interface.
 */
export function instanceOfApiPersistedAggregationSchedule(value: object): value is ApiPersistedAggregationSchedule {
    if (!("interval" in value) || value["interval"] === undefined) return false;
    if (!("timestampType" in value) || value["timestampType"] === undefined) return false;
    return true;
}

export function ApiPersistedAggregationScheduleFromJSON(json: any): ApiPersistedAggregationSchedule {
    return ApiPersistedAggregationScheduleFromJSONTyped(json, false);
}

export function ApiPersistedAggregationScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPersistedAggregationSchedule {
    if (json == null) {
        return json;
    }
    return {
        backfillAmount: json["backfill_amount"] == null ? undefined : json["backfill_amount"],
        backfillUnit: json["backfill_unit"] == null ? undefined : json["backfill_unit"],
        interval: json["interval"],
        offsetSeconds: json["offset_seconds"] == null ? undefined : json["offset_seconds"],
        timestampType: json["timestamp_type"],
    };
}

export function ApiPersistedAggregationScheduleToJSON(value?: ApiPersistedAggregationSchedule | null): any {
    if (value == null) {
        return value;
    }
    return {
        backfill_amount: value["backfillAmount"],
        backfill_unit: value["backfillUnit"],
        interval: value["interval"],
        offset_seconds: value["offsetSeconds"],
        timestamp_type: value["timestampType"],
    };
}
