/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { MsaAPIError } from "./MsaAPIError";
import { MsaAPIErrorFromJSON, MsaAPIErrorFromJSONTyped, MsaAPIErrorToJSON } from "./MsaAPIError";
import type { MsaMetaInfo } from "./MsaMetaInfo";
import { MsaMetaInfoFromJSON, MsaMetaInfoFromJSONTyped, MsaMetaInfoToJSON } from "./MsaMetaInfo";

/**
 *
 * @export
 * @interface ApiRollbackParserResponseV1
 */
export interface ApiRollbackParserResponseV1 {
    /**
     *
     * @type {Array<MsaAPIError>}
     * @memberof ApiRollbackParserResponseV1
     */
    errors?: Array<MsaAPIError>;
    /**
     *
     * @type {MsaMetaInfo}
     * @memberof ApiRollbackParserResponseV1
     */
    meta: MsaMetaInfo;
    /**
     * The version the parser was rolled back to
     * @type {string}
     * @memberof ApiRollbackParserResponseV1
     */
    newVersion: string;
    /**
     * The unique identifier for the parser
     * @type {string}
     * @memberof ApiRollbackParserResponseV1
     */
    parserId: string;
    /**
     * The version the parser was at before rollback
     * @type {string}
     * @memberof ApiRollbackParserResponseV1
     */
    previousVersion: string;
    /**
     * The timestamp when the rollback was performed
     * @type {string}
     * @memberof ApiRollbackParserResponseV1
     */
    rollbackTimestamp: string;
}

/**
 * Check if a given object implements the ApiRollbackParserResponseV1 interface.
 */
export function instanceOfApiRollbackParserResponseV1(value: object): value is ApiRollbackParserResponseV1 {
    if (!("meta" in value) || value["meta"] === undefined) return false;
    if (!("newVersion" in value) || value["newVersion"] === undefined) return false;
    if (!("parserId" in value) || value["parserId"] === undefined) return false;
    if (!("previousVersion" in value) || value["previousVersion"] === undefined) return false;
    if (!("rollbackTimestamp" in value) || value["rollbackTimestamp"] === undefined) return false;
    return true;
}

export function ApiRollbackParserResponseV1FromJSON(json: any): ApiRollbackParserResponseV1 {
    return ApiRollbackParserResponseV1FromJSONTyped(json, false);
}

export function ApiRollbackParserResponseV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRollbackParserResponseV1 {
    if (json == null) {
        return json;
    }
    return {
        errors: json["errors"] == null ? undefined : (json["errors"] as Array<any>).map(MsaAPIErrorFromJSON),
        meta: MsaMetaInfoFromJSON(json["meta"]),
        newVersion: json["new_version"],
        parserId: json["parser_id"],
        previousVersion: json["previous_version"],
        rollbackTimestamp: json["rollback_timestamp"],
    };
}

export function ApiRollbackParserResponseV1ToJSON(value?: ApiRollbackParserResponseV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        errors: value["errors"] == null ? undefined : (value["errors"] as Array<any>).map(MsaAPIErrorToJSON),
        meta: MsaMetaInfoToJSON(value["meta"]),
        new_version: value["newVersion"],
        parser_id: value["parserId"],
        previous_version: value["previousVersion"],
        rollback_timestamp: value["rollbackTimestamp"],
    };
}
