/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiParserTestCase } from "./ApiParserTestCase";
import { ApiParserTestCaseFromJSON, ApiParserTestCaseFromJSONTyped, ApiParserTestCaseToJSON } from "./ApiParserTestCase";

/**
 *
 * @export
 * @interface ApiUpdateParserExtensionRequestV1
 */
export interface ApiUpdateParserExtensionRequestV1 {
    /**
     * The unique identifier of the parser extension to update
     * @type {string}
     * @memberof ApiUpdateParserExtensionRequestV1
     */
    extensionId: string;
    /**
     * Optional - update postprocessing logic
     * @type {string}
     * @memberof ApiUpdateParserExtensionRequestV1
     */
    postProcessingScript?: string;
    /**
     * Optional - update preprocessing logic
     * @type {string}
     * @memberof ApiUpdateParserExtensionRequestV1
     */
    preProcessingScript?: string;
    /**
     * Optional - update test cases
     * @type {Array<ApiParserTestCase>}
     * @memberof ApiUpdateParserExtensionRequestV1
     */
    testCases?: Array<ApiParserTestCase>;
}

/**
 * Check if a given object implements the ApiUpdateParserExtensionRequestV1 interface.
 */
export function instanceOfApiUpdateParserExtensionRequestV1(value: object): value is ApiUpdateParserExtensionRequestV1 {
    if (!("extensionId" in value) || value["extensionId"] === undefined) return false;
    return true;
}

export function ApiUpdateParserExtensionRequestV1FromJSON(json: any): ApiUpdateParserExtensionRequestV1 {
    return ApiUpdateParserExtensionRequestV1FromJSONTyped(json, false);
}

export function ApiUpdateParserExtensionRequestV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUpdateParserExtensionRequestV1 {
    if (json == null) {
        return json;
    }
    return {
        extensionId: json["extension_id"],
        postProcessingScript: json["post_processing_script"] == null ? undefined : json["post_processing_script"],
        preProcessingScript: json["pre_processing_script"] == null ? undefined : json["pre_processing_script"],
        testCases: json["test_cases"] == null ? undefined : (json["test_cases"] as Array<any>).map(ApiParserTestCaseFromJSON),
    };
}

export function ApiUpdateParserExtensionRequestV1ToJSON(value?: ApiUpdateParserExtensionRequestV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        extension_id: value["extensionId"],
        post_processing_script: value["postProcessingScript"],
        pre_processing_script: value["preProcessingScript"],
        test_cases: value["testCases"] == null ? undefined : (value["testCases"] as Array<any>).map(ApiParserTestCaseToJSON),
    };
}
