/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ApiUpdateFileLabelsRequestV1
 */
export interface ApiUpdateFileLabelsRequestV1 {
    /**
     * The name of the lookup file
     * @type {string}
     * @memberof ApiUpdateFileLabelsRequestV1
     */
    filename: string;
    /**
     * The new labels (replaces all existing labels, max 10 labels, max 60 chars each)
     * @type {Array<string>}
     * @memberof ApiUpdateFileLabelsRequestV1
     */
    labels: Array<string>;
    /**
     * The search domain (view or repository) containing the file
     * @type {string}
     * @memberof ApiUpdateFileLabelsRequestV1
     */
    searchDomain: string;
}

/**
 * Check if a given object implements the ApiUpdateFileLabelsRequestV1 interface.
 */
export function instanceOfApiUpdateFileLabelsRequestV1(value: object): value is ApiUpdateFileLabelsRequestV1 {
    if (!("filename" in value) || value["filename"] === undefined) return false;
    if (!("labels" in value) || value["labels"] === undefined) return false;
    if (!("searchDomain" in value) || value["searchDomain"] === undefined) return false;
    return true;
}

export function ApiUpdateFileLabelsRequestV1FromJSON(json: any): ApiUpdateFileLabelsRequestV1 {
    return ApiUpdateFileLabelsRequestV1FromJSONTyped(json, false);
}

export function ApiUpdateFileLabelsRequestV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUpdateFileLabelsRequestV1 {
    if (json == null) {
        return json;
    }
    return {
        filename: json["filename"],
        labels: json["labels"],
        searchDomain: json["search_domain"],
    };
}

export function ApiUpdateFileLabelsRequestV1ToJSON(value?: ApiUpdateFileLabelsRequestV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        filename: value["filename"],
        labels: value["labels"],
        search_domain: value["searchDomain"],
    };
}
