/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DeviceapiDevicePolicySwagger
 */
export interface DeviceapiDevicePolicySwagger {
    /**
     *
     * @type {boolean}
     * @memberof DeviceapiDevicePolicySwagger
     */
    applied: boolean;
    /**
     *
     * @type {Date}
     * @memberof DeviceapiDevicePolicySwagger
     */
    appliedDate: Date;
    /**
     *
     * @type {Date}
     * @memberof DeviceapiDevicePolicySwagger
     */
    assignedDate: Date;
    /**
     *
     * @type {string}
     * @memberof DeviceapiDevicePolicySwagger
     */
    policyId: string;
    /**
     *
     * @type {string}
     * @memberof DeviceapiDevicePolicySwagger
     */
    policyType: string;
    /**
     *
     * @type {Array<string>}
     * @memberof DeviceapiDevicePolicySwagger
     */
    ruleGroups?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DeviceapiDevicePolicySwagger
     */
    ruleSetId?: string;
    /**
     *
     * @type {string}
     * @memberof DeviceapiDevicePolicySwagger
     */
    settingsHash?: string;
    /**
     *
     * @type {string}
     * @memberof DeviceapiDevicePolicySwagger
     */
    uninstallProtection?: string;
}

/**
 * Check if a given object implements the DeviceapiDevicePolicySwagger interface.
 */
export function instanceOfDeviceapiDevicePolicySwagger(value: object): value is DeviceapiDevicePolicySwagger {
    if (!("applied" in value) || value["applied"] === undefined) return false;
    if (!("appliedDate" in value) || value["appliedDate"] === undefined) return false;
    if (!("assignedDate" in value) || value["assignedDate"] === undefined) return false;
    if (!("policyId" in value) || value["policyId"] === undefined) return false;
    if (!("policyType" in value) || value["policyType"] === undefined) return false;
    return true;
}

export function DeviceapiDevicePolicySwaggerFromJSON(json: any): DeviceapiDevicePolicySwagger {
    return DeviceapiDevicePolicySwaggerFromJSONTyped(json, false);
}

export function DeviceapiDevicePolicySwaggerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceapiDevicePolicySwagger {
    if (json == null) {
        return json;
    }
    return {
        applied: json["applied"],
        appliedDate: new Date(json["applied_date"]),
        assignedDate: new Date(json["assigned_date"]),
        policyId: json["policy_id"],
        policyType: json["policy_type"],
        ruleGroups: json["rule_groups"] == null ? undefined : json["rule_groups"],
        ruleSetId: json["rule_set_id"] == null ? undefined : json["rule_set_id"],
        settingsHash: json["settings_hash"] == null ? undefined : json["settings_hash"],
        uninstallProtection: json["uninstall_protection"] == null ? undefined : json["uninstall_protection"],
    };
}

export function DeviceapiDevicePolicySwaggerToJSON(value?: DeviceapiDevicePolicySwagger | null): any {
    if (value == null) {
        return value;
    }
    return {
        applied: value["applied"],
        applied_date: value["appliedDate"].toISOString(),
        assigned_date: value["assignedDate"].toISOString(),
        policy_id: value["policyId"],
        policy_type: value["policyType"],
        rule_groups: value["ruleGroups"],
        rule_set_id: value["ruleSetId"],
        settings_hash: value["settingsHash"],
        uninstall_protection: value["uninstallProtection"],
    };
}
