/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DomainAppAbuseExclusionCreateReqV1
 */
export interface DomainAppAbuseExclusionCreateReqV1 {
    /**
     *
     * @type {boolean}
     * @memberof DomainAppAbuseExclusionCreateReqV1
     */
    appliedGlobally?: boolean;
    /**
     *
     * @type {Array<string>}
     * @memberof DomainAppAbuseExclusionCreateReqV1
     */
    childrenCids?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionCreateReqV1
     */
    comment?: string;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionCreateReqV1
     */
    description?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof DomainAppAbuseExclusionCreateReqV1
     */
    hostGroups?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionCreateReqV1
     */
    tag: string;
}

/**
 * Check if a given object implements the DomainAppAbuseExclusionCreateReqV1 interface.
 */
export function instanceOfDomainAppAbuseExclusionCreateReqV1(value: object): value is DomainAppAbuseExclusionCreateReqV1 {
    if (!("tag" in value) || value["tag"] === undefined) return false;
    return true;
}

export function DomainAppAbuseExclusionCreateReqV1FromJSON(json: any): DomainAppAbuseExclusionCreateReqV1 {
    return DomainAppAbuseExclusionCreateReqV1FromJSONTyped(json, false);
}

export function DomainAppAbuseExclusionCreateReqV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAppAbuseExclusionCreateReqV1 {
    if (json == null) {
        return json;
    }
    return {
        appliedGlobally: json["applied_globally"] == null ? undefined : json["applied_globally"],
        childrenCids: json["children_cids"] == null ? undefined : json["children_cids"],
        comment: json["comment"] == null ? undefined : json["comment"],
        description: json["description"] == null ? undefined : json["description"],
        hostGroups: json["host_groups"] == null ? undefined : json["host_groups"],
        tag: json["tag"],
    };
}

export function DomainAppAbuseExclusionCreateReqV1ToJSON(value?: DomainAppAbuseExclusionCreateReqV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        applied_globally: value["appliedGlobally"],
        children_cids: value["childrenCids"],
        comment: value["comment"],
        description: value["description"],
        host_groups: value["hostGroups"],
        tag: value["tag"],
    };
}
