/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DomainUser } from "./DomainUser";
import { DomainUserFromJSON, DomainUserFromJSONTyped, DomainUserToJSON } from "./DomainUser";

/**
 *
 * @export
 * @interface DomainEvaluator
 */
export interface DomainEvaluator {
    /**
     *
     * @type {Array<string>}
     * @memberof DomainEvaluator
     */
    agentIds: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DomainEvaluator
     */
    config: string;
    /**
     *
     * @type {Date}
     * @memberof DomainEvaluator
     */
    createdAt: Date;
    /**
     *
     * @type {DomainUser}
     * @memberof DomainEvaluator
     */
    createdBy: DomainUser;
    /**
     *
     * @type {string}
     * @memberof DomainEvaluator
     */
    description: string;
    /**
     *
     * @type {string}
     * @memberof DomainEvaluator
     */
    evaluatorType: string;
    /**
     *
     * @type {string}
     * @memberof DomainEvaluator
     */
    id: string;
    /**
     *
     * @type {boolean}
     * @memberof DomainEvaluator
     */
    isDeleted: boolean;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof DomainEvaluator
     */
    metadata: { [key: string]: string };
    /**
     *
     * @type {string}
     * @memberof DomainEvaluator
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof DomainEvaluator
     */
    owner: string;
    /**
     *
     * @type {string}
     * @memberof DomainEvaluator
     */
    projectId?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof DomainEvaluator
     */
    tags: Array<string>;
    /**
     *
     * @type {Date}
     * @memberof DomainEvaluator
     */
    updatedAt: Date;
    /**
     *
     * @type {DomainUser}
     * @memberof DomainEvaluator
     */
    updatedBy: DomainUser;
}

/**
 * Check if a given object implements the DomainEvaluator interface.
 */
export function instanceOfDomainEvaluator(value: object): value is DomainEvaluator {
    if (!("agentIds" in value) || value["agentIds"] === undefined) return false;
    if (!("config" in value) || value["config"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("createdBy" in value) || value["createdBy"] === undefined) return false;
    if (!("description" in value) || value["description"] === undefined) return false;
    if (!("evaluatorType" in value) || value["evaluatorType"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("isDeleted" in value) || value["isDeleted"] === undefined) return false;
    if (!("metadata" in value) || value["metadata"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("owner" in value) || value["owner"] === undefined) return false;
    if (!("tags" in value) || value["tags"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    if (!("updatedBy" in value) || value["updatedBy"] === undefined) return false;
    return true;
}

export function DomainEvaluatorFromJSON(json: any): DomainEvaluator {
    return DomainEvaluatorFromJSONTyped(json, false);
}

export function DomainEvaluatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainEvaluator {
    if (json == null) {
        return json;
    }
    return {
        agentIds: json["agent_ids"],
        config: json["config"],
        createdAt: new Date(json["created_at"]),
        createdBy: DomainUserFromJSON(json["created_by"]),
        description: json["description"],
        evaluatorType: json["evaluator_type"],
        id: json["id"],
        isDeleted: json["is_deleted"],
        metadata: json["metadata"],
        name: json["name"],
        owner: json["owner"],
        projectId: json["project_id"] == null ? undefined : json["project_id"],
        tags: json["tags"],
        updatedAt: new Date(json["updated_at"]),
        updatedBy: DomainUserFromJSON(json["updated_by"]),
    };
}

export function DomainEvaluatorToJSON(value?: DomainEvaluator | null): any {
    if (value == null) {
        return value;
    }
    return {
        agent_ids: value["agentIds"],
        config: value["config"],
        created_at: value["createdAt"].toISOString(),
        created_by: DomainUserToJSON(value["createdBy"]),
        description: value["description"],
        evaluator_type: value["evaluatorType"],
        id: value["id"],
        is_deleted: value["isDeleted"],
        metadata: value["metadata"],
        name: value["name"],
        owner: value["owner"],
        project_id: value["projectId"],
        tags: value["tags"],
        updated_at: value["updatedAt"].toISOString(),
        updated_by: DomainUserToJSON(value["updatedBy"]),
    };
}
