/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DomainPermissionDetails
 */
export interface DomainPermissionDetails {
    /**
     *
     * @type {Array<string>}
     * @memberof DomainPermissionDetails
     */
    dependsOn: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DomainPermissionDetails
     */
    description: string;
    /**
     *
     * @type {string}
     * @memberof DomainPermissionDetails
     */
    displayName: string;
    /**
     *
     * @type {string}
     * @memberof DomainPermissionDetails
     */
    id: string;
    /**
     *
     * @type {Array<string>}
     * @memberof DomainPermissionDetails
     */
    isRequiredFor: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DomainPermissionDetails
     */
    permissionGroupId: string;
    /**
     *
     * @type {string}
     * @memberof DomainPermissionDetails
     */
    type: string;
}

/**
 * Check if a given object implements the DomainPermissionDetails interface.
 */
export function instanceOfDomainPermissionDetails(value: object): value is DomainPermissionDetails {
    if (!("dependsOn" in value) || value["dependsOn"] === undefined) return false;
    if (!("description" in value) || value["description"] === undefined) return false;
    if (!("displayName" in value) || value["displayName"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("isRequiredFor" in value) || value["isRequiredFor"] === undefined) return false;
    if (!("permissionGroupId" in value) || value["permissionGroupId"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    return true;
}

export function DomainPermissionDetailsFromJSON(json: any): DomainPermissionDetails {
    return DomainPermissionDetailsFromJSONTyped(json, false);
}

export function DomainPermissionDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainPermissionDetails {
    if (json == null) {
        return json;
    }
    return {
        dependsOn: json["depends_on"],
        description: json["description"],
        displayName: json["display_name"],
        id: json["id"],
        isRequiredFor: json["is_required_for"],
        permissionGroupId: json["permission_group_id"],
        type: json["type"],
    };
}

export function DomainPermissionDetailsToJSON(value?: DomainPermissionDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        depends_on: value["dependsOn"],
        description: value["description"],
        display_name: value["displayName"],
        id: value["id"],
        is_required_for: value["isRequiredFor"],
        permission_group_id: value["permissionGroupId"],
        type: value["type"],
    };
}
