/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DomainAppAbuseExclusionV1
 */
export interface DomainAppAbuseExclusionV1 {
    /**
     *
     * @type {boolean}
     * @memberof DomainAppAbuseExclusionV1
     */
    appliedGlobally?: boolean;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionV1
     */
    category: string;
    /**
     *
     * @type {Array<string>}
     * @memberof DomainAppAbuseExclusionV1
     */
    childrenCids?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionV1
     */
    cid: string;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionV1
     */
    comment?: string;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionV1
     */
    createdBy?: string;
    /**
     *
     * @type {Date}
     * @memberof DomainAppAbuseExclusionV1
     */
    createdOn?: Date;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionV1
     */
    description?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof DomainAppAbuseExclusionV1
     */
    hostGroups?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionV1
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionV1
     */
    modifiedBy?: string;
    /**
     *
     * @type {Date}
     * @memberof DomainAppAbuseExclusionV1
     */
    modifiedOn?: Date;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionV1
     */
    tag: string;
    /**
     *
     * @type {string}
     * @memberof DomainAppAbuseExclusionV1
     */
    tagLabel: string;
}

/**
 * Check if a given object implements the DomainAppAbuseExclusionV1 interface.
 */
export function instanceOfDomainAppAbuseExclusionV1(value: object): value is DomainAppAbuseExclusionV1 {
    if (!("category" in value) || value["category"] === undefined) return false;
    if (!("cid" in value) || value["cid"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("tag" in value) || value["tag"] === undefined) return false;
    if (!("tagLabel" in value) || value["tagLabel"] === undefined) return false;
    return true;
}

export function DomainAppAbuseExclusionV1FromJSON(json: any): DomainAppAbuseExclusionV1 {
    return DomainAppAbuseExclusionV1FromJSONTyped(json, false);
}

export function DomainAppAbuseExclusionV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAppAbuseExclusionV1 {
    if (json == null) {
        return json;
    }
    return {
        appliedGlobally: json["applied_globally"] == null ? undefined : json["applied_globally"],
        category: json["category"],
        childrenCids: json["children_cids"] == null ? undefined : json["children_cids"],
        cid: json["cid"],
        comment: json["comment"] == null ? undefined : json["comment"],
        createdBy: json["created_by"] == null ? undefined : json["created_by"],
        createdOn: json["created_on"] == null ? undefined : new Date(json["created_on"]),
        description: json["description"] == null ? undefined : json["description"],
        hostGroups: json["host_groups"] == null ? undefined : json["host_groups"],
        id: json["id"],
        modifiedBy: json["modified_by"] == null ? undefined : json["modified_by"],
        modifiedOn: json["modified_on"] == null ? undefined : new Date(json["modified_on"]),
        tag: json["tag"],
        tagLabel: json["tag_label"],
    };
}

export function DomainAppAbuseExclusionV1ToJSON(value?: DomainAppAbuseExclusionV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        applied_globally: value["appliedGlobally"],
        category: value["category"],
        children_cids: value["childrenCids"],
        cid: value["cid"],
        comment: value["comment"],
        created_by: value["createdBy"],
        created_on: value["createdOn"] == null ? undefined : value["createdOn"].toISOString(),
        description: value["description"],
        host_groups: value["hostGroups"],
        id: value["id"],
        modified_by: value["modifiedBy"],
        modified_on: value["modifiedOn"] == null ? undefined : value["modifiedOn"].toISOString(),
        tag: value["tag"],
        tag_label: value["tagLabel"],
    };
}
