/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DomainAPIRemediationV2
 */
export interface DomainAPIRemediationV2 {
    /**
     * Expanded description of the remediation
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    action: string;
    /**
     * The timestamp when this remediation was created
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    createdTimestamp?: string;
    /**
     * Refers to an unique identifier for a given remediation
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    id: string;
    /**
     * Link to the remediation page for the vendor
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    link: string;
    /**
     * The timestamp that this remediation was published
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    patchPublicationDate?: string;
    /**
     * The provider of the remediation
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    provider: string;
    /**
     * The type of recommendation for this remediation, usually either 'recommended' or 'minimum'
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    recommendationType?: string;
    /**
     * Relevant reference for the remediation that can be used to get additional details for the remediation. For example, a KB number that needs to be installed for a KB_SECURITY_UPDATE
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    reference: string;
    /**
     * Short description of the remediation
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    title: string;
    /**
     * The type of remediation (e.g., patch, workaround)
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    type: string;
    /**
     * The timestamp when this remediation was last updated
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    updatedTimestamp?: string;
    /**
     * Link to the vendor advisory - Note: This field is populated if there are extra steps that are required to complete the remediation
     * @type {string}
     * @memberof DomainAPIRemediationV2
     */
    vendorUrl: string;
}

/**
 * Check if a given object implements the DomainAPIRemediationV2 interface.
 */
export function instanceOfDomainAPIRemediationV2(value: object): value is DomainAPIRemediationV2 {
    if (!("action" in value) || value["action"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("link" in value) || value["link"] === undefined) return false;
    if (!("provider" in value) || value["provider"] === undefined) return false;
    if (!("reference" in value) || value["reference"] === undefined) return false;
    if (!("title" in value) || value["title"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    if (!("vendorUrl" in value) || value["vendorUrl"] === undefined) return false;
    return true;
}

export function DomainAPIRemediationV2FromJSON(json: any): DomainAPIRemediationV2 {
    return DomainAPIRemediationV2FromJSONTyped(json, false);
}

export function DomainAPIRemediationV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAPIRemediationV2 {
    if (json == null) {
        return json;
    }
    return {
        action: json["action"],
        createdTimestamp: json["created_timestamp"] == null ? undefined : json["created_timestamp"],
        id: json["id"],
        link: json["link"],
        patchPublicationDate: json["patch_publication_date"] == null ? undefined : json["patch_publication_date"],
        provider: json["provider"],
        recommendationType: json["recommendation_type"] == null ? undefined : json["recommendation_type"],
        reference: json["reference"],
        title: json["title"],
        type: json["type"],
        updatedTimestamp: json["updated_timestamp"] == null ? undefined : json["updated_timestamp"],
        vendorUrl: json["vendor_url"],
    };
}

export function DomainAPIRemediationV2ToJSON(value?: DomainAPIRemediationV2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        action: value["action"],
        created_timestamp: value["createdTimestamp"],
        id: value["id"],
        link: value["link"],
        patch_publication_date: value["patchPublicationDate"],
        provider: value["provider"],
        recommendation_type: value["recommendationType"],
        reference: value["reference"],
        title: value["title"],
        type: value["type"],
        updated_timestamp: value["updatedTimestamp"],
        vendor_url: value["vendorUrl"],
    };
}
