/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DomainAppAbuseExclusionUpdateReqV1 } from "./DomainAppAbuseExclusionUpdateReqV1";
import { DomainAppAbuseExclusionUpdateReqV1FromJSON, DomainAppAbuseExclusionUpdateReqV1FromJSONTyped, DomainAppAbuseExclusionUpdateReqV1ToJSON } from "./DomainAppAbuseExclusionUpdateReqV1";

/**
 *
 * @export
 * @interface DomainAppAbuseExclusionsUpdateReqV1
 */
export interface DomainAppAbuseExclusionsUpdateReqV1 {
    /**
     *
     * @type {Array<DomainAppAbuseExclusionUpdateReqV1>}
     * @memberof DomainAppAbuseExclusionsUpdateReqV1
     */
    exclusions: Array<DomainAppAbuseExclusionUpdateReqV1>;
}

/**
 * Check if a given object implements the DomainAppAbuseExclusionsUpdateReqV1 interface.
 */
export function instanceOfDomainAppAbuseExclusionsUpdateReqV1(value: object): value is DomainAppAbuseExclusionsUpdateReqV1 {
    if (!("exclusions" in value) || value["exclusions"] === undefined) return false;
    return true;
}

export function DomainAppAbuseExclusionsUpdateReqV1FromJSON(json: any): DomainAppAbuseExclusionsUpdateReqV1 {
    return DomainAppAbuseExclusionsUpdateReqV1FromJSONTyped(json, false);
}

export function DomainAppAbuseExclusionsUpdateReqV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAppAbuseExclusionsUpdateReqV1 {
    if (json == null) {
        return json;
    }
    return {
        exclusions: (json["exclusions"] as Array<any>).map(DomainAppAbuseExclusionUpdateReqV1FromJSON),
    };
}

export function DomainAppAbuseExclusionsUpdateReqV1ToJSON(value?: DomainAppAbuseExclusionsUpdateReqV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        exclusions: (value["exclusions"] as Array<any>).map(DomainAppAbuseExclusionUpdateReqV1ToJSON),
    };
}
