/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DomainProductFeatures } from "./DomainProductFeatures";
import { DomainProductFeaturesFromJSON, DomainProductFeaturesFromJSONTyped, DomainProductFeaturesToJSON } from "./DomainProductFeatures";
import type { DtoLogIngestionProperties } from "./DtoLogIngestionProperties";
import { DtoLogIngestionPropertiesFromJSON, DtoLogIngestionPropertiesFromJSONTyped, DtoLogIngestionPropertiesToJSON } from "./DtoLogIngestionProperties";
import type { GcpAgentlessScanningSettings } from "./GcpAgentlessScanningSettings";
import { GcpAgentlessScanningSettingsFromJSON, GcpAgentlessScanningSettingsFromJSONTyped, GcpAgentlessScanningSettingsToJSON } from "./GcpAgentlessScanningSettings";
import type { DtoInfraManagerProperties } from "./DtoInfraManagerProperties";
import { DtoInfraManagerPropertiesFromJSON, DtoInfraManagerPropertiesFromJSONTyped, DtoInfraManagerPropertiesToJSON } from "./DtoInfraManagerProperties";
import type { DtoOrganization } from "./DtoOrganization";
import { DtoOrganizationFromJSON, DtoOrganizationFromJSONTyped, DtoOrganizationToJSON } from "./DtoOrganization";
import type { DtoProject } from "./DtoProject";
import { DtoProjectFromJSON, DtoProjectFromJSONTyped, DtoProjectToJSON } from "./DtoProject";
import type { DtoWIFProperties } from "./DtoWIFProperties";
import { DtoWIFPropertiesFromJSON, DtoWIFPropertiesFromJSONTyped, DtoWIFPropertiesToJSON } from "./DtoWIFProperties";
import type { DtoFolder } from "./DtoFolder";
import { DtoFolderFromJSON, DtoFolderFromJSONTyped, DtoFolderToJSON } from "./DtoFolder";
import type { DtoServiceAccountProperties } from "./DtoServiceAccountProperties";
import { DtoServiceAccountPropertiesFromJSON, DtoServiceAccountPropertiesFromJSONTyped, DtoServiceAccountPropertiesToJSON } from "./DtoServiceAccountProperties";

/**
 *
 * @export
 * @interface DtoGCPRegistration
 */
export interface DtoGCPRegistration {
    /**
     *
     * @type {object}
     * @memberof DtoGCPRegistration
     */
    additionalProperties?: object;
    /**
     *
     * @type {boolean}
     * @memberof DtoGCPRegistration
     */
    cloudRegistrationEnabled: boolean;
    /**
     *
     * @type {Date}
     * @memberof DtoGCPRegistration
     */
    created?: Date;
    /**
     *
     * @type {boolean}
     * @memberof DtoGCPRegistration
     */
    cspmEnabled: boolean;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    deploymentMethod?: string;
    /**
     *
     * @type {GcpAgentlessScanningSettings}
     * @memberof DtoGCPRegistration
     */
    dspmSettings?: GcpAgentlessScanningSettings;
    /**
     *
     * @type {Array<string>}
     * @memberof DtoGCPRegistration
     */
    excludedProjectPatterns?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    falconClientKeyId?: string;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    falconClientKeyType?: string;
    /**
     *
     * @type {Array<DtoFolder>}
     * @memberof DtoGCPRegistration
     */
    folders?: Array<DtoFolder>;
    /**
     *
     * @type {DtoInfraManagerProperties}
     * @memberof DtoGCPRegistration
     */
    infraManagerProperties?: DtoInfraManagerProperties;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    infraProjectId?: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof DtoGCPRegistration
     */
    labels?: { [key: string]: string };
    /**
     *
     * @type {Date}
     * @memberof DtoGCPRegistration
     */
    lastHealthcheckCompletedAt?: Date;
    /**
     *
     * @type {DtoLogIngestionProperties}
     * @memberof DtoGCPRegistration
     */
    logIngestionProperties?: DtoLogIngestionProperties;
    /**
     *
     * @type {DtoOrganization}
     * @memberof DtoGCPRegistration
     */
    organization?: DtoOrganization;
    /**
     *
     * @type {Array<DomainProductFeatures>}
     * @memberof DtoGCPRegistration
     */
    products?: Array<DomainProductFeatures>;
    /**
     *
     * @type {Array<DtoProject>}
     * @memberof DtoGCPRegistration
     */
    projects?: Array<DtoProject>;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    registrationDescription?: string;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    registrationId?: string;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    registrationName?: string;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    registrationScope?: string;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    resourceNamePrefix?: string;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    resourceNameSuffix?: string;
    /**
     *
     * @type {DtoServiceAccountProperties}
     * @memberof DtoGCPRegistration
     */
    serviceAccountProperties?: DtoServiceAccountProperties;
    /**
     *
     * @type {string}
     * @memberof DtoGCPRegistration
     */
    status?: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof DtoGCPRegistration
     */
    tags?: { [key: string]: string };
    /**
     *
     * @type {Date}
     * @memberof DtoGCPRegistration
     */
    updated?: Date;
    /**
     *
     * @type {GcpAgentlessScanningSettings}
     * @memberof DtoGCPRegistration
     */
    vulnerabilityScanningSettings?: GcpAgentlessScanningSettings;
    /**
     *
     * @type {DtoWIFProperties}
     * @memberof DtoGCPRegistration
     */
    wifProperties?: DtoWIFProperties;
}

/**
 * Check if a given object implements the DtoGCPRegistration interface.
 */
export function instanceOfDtoGCPRegistration(value: object): value is DtoGCPRegistration {
    if (!("cloudRegistrationEnabled" in value) || value["cloudRegistrationEnabled"] === undefined) return false;
    if (!("cspmEnabled" in value) || value["cspmEnabled"] === undefined) return false;
    return true;
}

export function DtoGCPRegistrationFromJSON(json: any): DtoGCPRegistration {
    return DtoGCPRegistrationFromJSONTyped(json, false);
}

export function DtoGCPRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoGCPRegistration {
    if (json == null) {
        return json;
    }
    return {
        additionalProperties: json["additional_properties"] == null ? undefined : json["additional_properties"],
        cloudRegistrationEnabled: json["cloud_registration_enabled"],
        created: json["created"] == null ? undefined : new Date(json["created"]),
        cspmEnabled: json["cspm_enabled"],
        deploymentMethod: json["deployment_method"] == null ? undefined : json["deployment_method"],
        dspmSettings: json["dspm_settings"] == null ? undefined : GcpAgentlessScanningSettingsFromJSON(json["dspm_settings"]),
        excludedProjectPatterns: json["excluded_project_patterns"] == null ? undefined : json["excluded_project_patterns"],
        falconClientKeyId: json["falcon_client_key_id"] == null ? undefined : json["falcon_client_key_id"],
        falconClientKeyType: json["falcon_client_key_type"] == null ? undefined : json["falcon_client_key_type"],
        folders: json["folders"] == null ? undefined : (json["folders"] as Array<any>).map(DtoFolderFromJSON),
        infraManagerProperties: json["infra_manager_properties"] == null ? undefined : DtoInfraManagerPropertiesFromJSON(json["infra_manager_properties"]),
        infraProjectId: json["infra_project_id"] == null ? undefined : json["infra_project_id"],
        labels: json["labels"] == null ? undefined : json["labels"],
        lastHealthcheckCompletedAt: json["last_healthcheck_completed_at"] == null ? undefined : new Date(json["last_healthcheck_completed_at"]),
        logIngestionProperties: json["log_ingestion_properties"] == null ? undefined : DtoLogIngestionPropertiesFromJSON(json["log_ingestion_properties"]),
        organization: json["organization"] == null ? undefined : DtoOrganizationFromJSON(json["organization"]),
        products: json["products"] == null ? undefined : (json["products"] as Array<any>).map(DomainProductFeaturesFromJSON),
        projects: json["projects"] == null ? undefined : (json["projects"] as Array<any>).map(DtoProjectFromJSON),
        registrationDescription: json["registration_description"] == null ? undefined : json["registration_description"],
        registrationId: json["registration_id"] == null ? undefined : json["registration_id"],
        registrationName: json["registration_name"] == null ? undefined : json["registration_name"],
        registrationScope: json["registration_scope"] == null ? undefined : json["registration_scope"],
        resourceNamePrefix: json["resource_name_prefix"] == null ? undefined : json["resource_name_prefix"],
        resourceNameSuffix: json["resource_name_suffix"] == null ? undefined : json["resource_name_suffix"],
        serviceAccountProperties: json["service_account_properties"] == null ? undefined : DtoServiceAccountPropertiesFromJSON(json["service_account_properties"]),
        status: json["status"] == null ? undefined : json["status"],
        tags: json["tags"] == null ? undefined : json["tags"],
        updated: json["updated"] == null ? undefined : new Date(json["updated"]),
        vulnerabilityScanningSettings: json["vulnerability_scanning_settings"] == null ? undefined : GcpAgentlessScanningSettingsFromJSON(json["vulnerability_scanning_settings"]),
        wifProperties: json["wif_properties"] == null ? undefined : DtoWIFPropertiesFromJSON(json["wif_properties"]),
    };
}

export function DtoGCPRegistrationToJSON(value?: DtoGCPRegistration | null): any {
    if (value == null) {
        return value;
    }
    return {
        additional_properties: value["additionalProperties"],
        cloud_registration_enabled: value["cloudRegistrationEnabled"],
        created: value["created"] == null ? undefined : value["created"].toISOString(),
        cspm_enabled: value["cspmEnabled"],
        deployment_method: value["deploymentMethod"],
        dspm_settings: GcpAgentlessScanningSettingsToJSON(value["dspmSettings"]),
        excluded_project_patterns: value["excludedProjectPatterns"],
        falcon_client_key_id: value["falconClientKeyId"],
        falcon_client_key_type: value["falconClientKeyType"],
        folders: value["folders"] == null ? undefined : (value["folders"] as Array<any>).map(DtoFolderToJSON),
        infra_manager_properties: DtoInfraManagerPropertiesToJSON(value["infraManagerProperties"]),
        infra_project_id: value["infraProjectId"],
        labels: value["labels"],
        last_healthcheck_completed_at: value["lastHealthcheckCompletedAt"] == null ? undefined : value["lastHealthcheckCompletedAt"].toISOString(),
        log_ingestion_properties: DtoLogIngestionPropertiesToJSON(value["logIngestionProperties"]),
        organization: DtoOrganizationToJSON(value["organization"]),
        products: value["products"] == null ? undefined : (value["products"] as Array<any>).map(DomainProductFeaturesToJSON),
        projects: value["projects"] == null ? undefined : (value["projects"] as Array<any>).map(DtoProjectToJSON),
        registration_description: value["registrationDescription"],
        registration_id: value["registrationId"],
        registration_name: value["registrationName"],
        registration_scope: value["registrationScope"],
        resource_name_prefix: value["resourceNamePrefix"],
        resource_name_suffix: value["resourceNameSuffix"],
        service_account_properties: DtoServiceAccountPropertiesToJSON(value["serviceAccountProperties"]),
        status: value["status"],
        tags: value["tags"],
        updated: value["updated"] == null ? undefined : value["updated"].toISOString(),
        vulnerability_scanning_settings: GcpAgentlessScanningSettingsToJSON(value["vulnerabilityScanningSettings"]),
        wif_properties: DtoWIFPropertiesToJSON(value["wifProperties"]),
    };
}
