/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DtoServiceAccountProperties
 */
export interface DtoServiceAccountProperties {
    /**
     *
     * @type {string}
     * @memberof DtoServiceAccountProperties
     */
    clientEmail?: string;
    /**
     *
     * @type {string}
     * @memberof DtoServiceAccountProperties
     */
    clientId?: string;
    /**
     *
     * @type {string}
     * @memberof DtoServiceAccountProperties
     */
    encryptedPrivateKey?: string;
    /**
     *
     * @type {number}
     * @memberof DtoServiceAccountProperties
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof DtoServiceAccountProperties
     */
    privateKeyId?: string;
    /**
     *
     * @type {string}
     * @memberof DtoServiceAccountProperties
     */
    projectId?: string;
}

/**
 * Check if a given object implements the DtoServiceAccountProperties interface.
 */
export function instanceOfDtoServiceAccountProperties(value: object): value is DtoServiceAccountProperties {
    if (!("id" in value) || value["id"] === undefined) return false;
    return true;
}

export function DtoServiceAccountPropertiesFromJSON(json: any): DtoServiceAccountProperties {
    return DtoServiceAccountPropertiesFromJSONTyped(json, false);
}

export function DtoServiceAccountPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoServiceAccountProperties {
    if (json == null) {
        return json;
    }
    return {
        clientEmail: json["client_email"] == null ? undefined : json["client_email"],
        clientId: json["client_id"] == null ? undefined : json["client_id"],
        encryptedPrivateKey: json["encrypted_private_key"] == null ? undefined : json["encrypted_private_key"],
        id: json["id"],
        privateKeyId: json["private_key_id"] == null ? undefined : json["private_key_id"],
        projectId: json["project_id"] == null ? undefined : json["project_id"],
    };
}

export function DtoServiceAccountPropertiesToJSON(value?: DtoServiceAccountProperties | null): any {
    if (value == null) {
        return value;
    }
    return {
        client_email: value["clientEmail"],
        client_id: value["clientId"],
        encrypted_private_key: value["encryptedPrivateKey"],
        id: value["id"],
        private_key_id: value["privateKeyId"],
        project_id: value["projectId"],
    };
}
