/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GcpAgentlessScanningSettings } from "./GcpAgentlessScanningSettings";
import { GcpAgentlessScanningSettingsFromJSON, GcpAgentlessScanningSettingsFromJSONTyped, GcpAgentlessScanningSettingsToJSON } from "./GcpAgentlessScanningSettings";

/**
 *
 * @export
 * @interface DtoTerraformScriptParameters
 */
export interface DtoTerraformScriptParameters {
    /**
     *
     * @type {GcpAgentlessScanningSettings}
     * @memberof DtoTerraformScriptParameters
     */
    dspmSettings?: GcpAgentlessScanningSettings;
    /**
     *
     * @type {Array<string>}
     * @memberof DtoTerraformScriptParameters
     */
    entityId?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof DtoTerraformScriptParameters
     */
    excludedProjectPatterns?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    falconClientKeyId?: string;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    falconClientKeyType?: string;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    infraProjectId?: string;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    labels?: string;
    /**
     *
     * @type {boolean}
     * @memberof DtoTerraformScriptParameters
     */
    realtimeVisibilityEnabled?: boolean;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    registrationId: string;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    registrationName?: string;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    resourceNamePrefix?: string;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    resourceNameSuffix?: string;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    tags?: string;
    /**
     *
     * @type {boolean}
     * @memberof DtoTerraformScriptParameters
     */
    varsOnly?: boolean;
    /**
     *
     * @type {GcpAgentlessScanningSettings}
     * @memberof DtoTerraformScriptParameters
     */
    vulnerabilityScanningSettings?: GcpAgentlessScanningSettings;
    /**
     *
     * @type {string}
     * @memberof DtoTerraformScriptParameters
     */
    wifProjectId?: string;
}

/**
 * Check if a given object implements the DtoTerraformScriptParameters interface.
 */
export function instanceOfDtoTerraformScriptParameters(value: object): value is DtoTerraformScriptParameters {
    if (!("registrationId" in value) || value["registrationId"] === undefined) return false;
    return true;
}

export function DtoTerraformScriptParametersFromJSON(json: any): DtoTerraformScriptParameters {
    return DtoTerraformScriptParametersFromJSONTyped(json, false);
}

export function DtoTerraformScriptParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoTerraformScriptParameters {
    if (json == null) {
        return json;
    }
    return {
        dspmSettings: json["dspm_settings"] == null ? undefined : GcpAgentlessScanningSettingsFromJSON(json["dspm_settings"]),
        entityId: json["entity_id"] == null ? undefined : json["entity_id"],
        excludedProjectPatterns: json["excluded_project_patterns"] == null ? undefined : json["excluded_project_patterns"],
        falconClientKeyId: json["falcon_client_key_id"] == null ? undefined : json["falcon_client_key_id"],
        falconClientKeyType: json["falcon_client_key_type"] == null ? undefined : json["falcon_client_key_type"],
        infraProjectId: json["infra_project_id"] == null ? undefined : json["infra_project_id"],
        labels: json["labels"] == null ? undefined : json["labels"],
        realtimeVisibilityEnabled: json["realtime_visibility_enabled"] == null ? undefined : json["realtime_visibility_enabled"],
        registrationId: json["registration_id"],
        registrationName: json["registration_name"] == null ? undefined : json["registration_name"],
        resourceNamePrefix: json["resource_name_prefix"] == null ? undefined : json["resource_name_prefix"],
        resourceNameSuffix: json["resource_name_suffix"] == null ? undefined : json["resource_name_suffix"],
        tags: json["tags"] == null ? undefined : json["tags"],
        varsOnly: json["vars_only"] == null ? undefined : json["vars_only"],
        vulnerabilityScanningSettings: json["vulnerability_scanning_settings"] == null ? undefined : GcpAgentlessScanningSettingsFromJSON(json["vulnerability_scanning_settings"]),
        wifProjectId: json["wif_project_id"] == null ? undefined : json["wif_project_id"],
    };
}

export function DtoTerraformScriptParametersToJSON(value?: DtoTerraformScriptParameters | null): any {
    if (value == null) {
        return value;
    }
    return {
        dspm_settings: GcpAgentlessScanningSettingsToJSON(value["dspmSettings"]),
        entity_id: value["entityId"],
        excluded_project_patterns: value["excludedProjectPatterns"],
        falcon_client_key_id: value["falconClientKeyId"],
        falcon_client_key_type: value["falconClientKeyType"],
        infra_project_id: value["infraProjectId"],
        labels: value["labels"],
        realtime_visibility_enabled: value["realtimeVisibilityEnabled"],
        registration_id: value["registrationId"],
        registration_name: value["registrationName"],
        resource_name_prefix: value["resourceNamePrefix"],
        resource_name_suffix: value["resourceNameSuffix"],
        tags: value["tags"],
        vars_only: value["varsOnly"],
        vulnerability_scanning_settings: GcpAgentlessScanningSettingsToJSON(value["vulnerabilityScanningSettings"]),
        wif_project_id: value["wifProjectId"],
    };
}
