/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { MetaGetCheckTags } from "./MetaGetCheckTags";
import { MetaGetCheckTagsFromJSON, MetaGetCheckTagsFromJSONTyped, MetaGetCheckTagsToJSON } from "./MetaGetCheckTags";
import type { ErrorGetCheckTags } from "./ErrorGetCheckTags";
import { ErrorGetCheckTagsFromJSON, ErrorGetCheckTagsFromJSONTyped, ErrorGetCheckTagsToJSON } from "./ErrorGetCheckTags";
import type { CheckTagGetCheckTags } from "./CheckTagGetCheckTags";
import { CheckTagGetCheckTagsFromJSON, CheckTagGetCheckTagsFromJSONTyped, CheckTagGetCheckTagsToJSON } from "./CheckTagGetCheckTags";

/**
 *
 * @export
 * @interface GetCheckTags
 */
export interface GetCheckTags {
    /**
     *
     * @type {Array<ErrorGetCheckTags>}
     * @memberof GetCheckTags
     */
    errors?: Array<ErrorGetCheckTags>;
    /**
     *
     * @type {MetaGetCheckTags}
     * @memberof GetCheckTags
     */
    meta?: MetaGetCheckTags | null;
    /**
     *
     * @type {Array<CheckTagGetCheckTags>}
     * @memberof GetCheckTags
     */
    resources?: Array<CheckTagGetCheckTags>;
}

/**
 * Check if a given object implements the GetCheckTags interface.
 */
export function instanceOfGetCheckTags(value: object): value is GetCheckTags {
    return true;
}

export function GetCheckTagsFromJSON(json: any): GetCheckTags {
    return GetCheckTagsFromJSONTyped(json, false);
}

export function GetCheckTagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCheckTags {
    if (json == null) {
        return json;
    }
    return {
        errors: json["errors"] == null ? undefined : (json["errors"] as Array<any>).map(ErrorGetCheckTagsFromJSON),
        meta: json["meta"] == null ? undefined : MetaGetCheckTagsFromJSON(json["meta"]),
        resources: json["resources"] == null ? undefined : (json["resources"] as Array<any>).map(CheckTagGetCheckTagsFromJSON),
    };
}

export function GetCheckTagsToJSON(value?: GetCheckTags | null): any {
    if (value == null) {
        return value;
    }
    return {
        errors: value["errors"] == null ? undefined : (value["errors"] as Array<any>).map(ErrorGetCheckTagsToJSON),
        meta: MetaGetCheckTagsToJSON(value["meta"]),
        resources: value["resources"] == null ? undefined : (value["resources"] as Array<any>).map(CheckTagGetCheckTagsToJSON),
    };
}
