/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { IpwhitelistinteractorRuleOption } from "./IpwhitelistinteractorRuleOption";
import { IpwhitelistinteractorRuleOptionFromJSON, IpwhitelistinteractorRuleOptionFromJSONTyped, IpwhitelistinteractorRuleOptionToJSON } from "./IpwhitelistinteractorRuleOption";

/**
 *
 * @export
 * @interface IpwhitelistinteractorAllowlistRule
 */
export interface IpwhitelistinteractorAllowlistRule {
    /**
     *
     * @type {string}
     * @memberof IpwhitelistinteractorAllowlistRule
     */
    cid?: string;
    /**
     *
     * @type {string}
     * @memberof IpwhitelistinteractorAllowlistRule
     */
    context: string;
    /**
     *
     * @type {string}
     * @memberof IpwhitelistinteractorAllowlistRule
     */
    createdBy: string;
    /**
     *
     * @type {Date}
     * @memberof IpwhitelistinteractorAllowlistRule
     */
    createdOn: Date;
    /**
     *
     * @type {string}
     * @memberof IpwhitelistinteractorAllowlistRule
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof IpwhitelistinteractorAllowlistRule
     */
    label: string;
    /**
     *
     * @type {IpwhitelistinteractorRuleOption}
     * @memberof IpwhitelistinteractorAllowlistRule
     */
    options?: IpwhitelistinteractorRuleOption;
    /**
     *
     * @type {string}
     * @memberof IpwhitelistinteractorAllowlistRule
     */
    rule: string;
    /**
     *
     * @type {string}
     * @memberof IpwhitelistinteractorAllowlistRule
     */
    type: string;
}

/**
 * Check if a given object implements the IpwhitelistinteractorAllowlistRule interface.
 */
export function instanceOfIpwhitelistinteractorAllowlistRule(value: object): value is IpwhitelistinteractorAllowlistRule {
    if (!("context" in value) || value["context"] === undefined) return false;
    if (!("createdBy" in value) || value["createdBy"] === undefined) return false;
    if (!("createdOn" in value) || value["createdOn"] === undefined) return false;
    if (!("label" in value) || value["label"] === undefined) return false;
    if (!("rule" in value) || value["rule"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    return true;
}

export function IpwhitelistinteractorAllowlistRuleFromJSON(json: any): IpwhitelistinteractorAllowlistRule {
    return IpwhitelistinteractorAllowlistRuleFromJSONTyped(json, false);
}

export function IpwhitelistinteractorAllowlistRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpwhitelistinteractorAllowlistRule {
    if (json == null) {
        return json;
    }
    return {
        cid: json["cid"] == null ? undefined : json["cid"],
        context: json["context"],
        createdBy: json["created_by"],
        createdOn: new Date(json["created_on"]),
        id: json["id"] == null ? undefined : json["id"],
        label: json["label"],
        options: json["options"] == null ? undefined : IpwhitelistinteractorRuleOptionFromJSON(json["options"]),
        rule: json["rule"],
        type: json["type"],
    };
}

export function IpwhitelistinteractorAllowlistRuleToJSON(value?: IpwhitelistinteractorAllowlistRule | null): any {
    if (value == null) {
        return value;
    }
    return {
        cid: value["cid"],
        context: value["context"],
        created_by: value["createdBy"],
        created_on: value["createdOn"].toISOString(),
        id: value["id"],
        label: value["label"],
        options: IpwhitelistinteractorRuleOptionToJSON(value["options"]),
        rule: value["rule"],
        type: value["type"],
    };
}
