/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PaginationMetaRestoreAffected } from "./PaginationMetaRestoreAffected";
import { PaginationMetaRestoreAffectedFromJSON, PaginationMetaRestoreAffectedFromJSONTyped, PaginationMetaRestoreAffectedToJSON } from "./PaginationMetaRestoreAffected";

/**
 *
 * @export
 * @interface MetaRestoreAffected
 */
export interface MetaRestoreAffected {
    /**
     *
     * @type {PaginationMetaRestoreAffected}
     * @memberof MetaRestoreAffected
     */
    pagination?: PaginationMetaRestoreAffected | null;
    /**
     *
     * @type {number}
     * @memberof MetaRestoreAffected
     */
    queryTime?: number | null;
    /**
     *
     * @type {string}
     * @memberof MetaRestoreAffected
     */
    traceId?: string | null;
}

/**
 * Check if a given object implements the MetaRestoreAffected interface.
 */
export function instanceOfMetaRestoreAffected(value: object): value is MetaRestoreAffected {
    return true;
}

export function MetaRestoreAffectedFromJSON(json: any): MetaRestoreAffected {
    return MetaRestoreAffectedFromJSONTyped(json, false);
}

export function MetaRestoreAffectedFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaRestoreAffected {
    if (json == null) {
        return json;
    }
    return {
        pagination: json["pagination"] == null ? undefined : PaginationMetaRestoreAffectedFromJSON(json["pagination"]),
        queryTime: json["query_time"] == null ? undefined : json["query_time"],
        traceId: json["trace_id"] == null ? undefined : json["trace_id"],
    };
}

export function MetaRestoreAffectedToJSON(value?: MetaRestoreAffected | null): any {
    if (value == null) {
        return value;
    }
    return {
        pagination: PaginationMetaRestoreAffectedToJSON(value["pagination"]),
        query_time: value["queryTime"],
        trace_id: value["traceId"],
    };
}
