/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ModelsModuleRemediation
 */
export interface ModelsModuleRemediation {
    /**
     *
     * @type {string}
     * @memberof ModelsModuleRemediation
     */
    moduleCallFile?: string;
    /**
     *
     * @type {number}
     * @memberof ModelsModuleRemediation
     */
    moduleCallLine?: number;
    /**
     *
     * @type {string}
     * @memberof ModelsModuleRemediation
     */
    remediation1?: string;
    /**
     *
     * @type {string}
     * @memberof ModelsModuleRemediation
     */
    remediation2?: string;
}

/**
 * Check if a given object implements the ModelsModuleRemediation interface.
 */
export function instanceOfModelsModuleRemediation(value: object): value is ModelsModuleRemediation {
    return true;
}

export function ModelsModuleRemediationFromJSON(json: any): ModelsModuleRemediation {
    return ModelsModuleRemediationFromJSONTyped(json, false);
}

export function ModelsModuleRemediationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsModuleRemediation {
    if (json == null) {
        return json;
    }
    return {
        moduleCallFile: json["module_call_file"] == null ? undefined : json["module_call_file"],
        moduleCallLine: json["module_call_line"] == null ? undefined : json["module_call_line"],
        remediation1: json["remediation_1"] == null ? undefined : json["remediation_1"],
        remediation2: json["remediation_2"] == null ? undefined : json["remediation_2"],
    };
}

export function ModelsModuleRemediationToJSON(value?: ModelsModuleRemediation | null): any {
    if (value == null) {
        return value;
    }
    return {
        module_call_file: value["moduleCallFile"],
        module_call_line: value["moduleCallLine"],
        remediation_1: value["remediation1"],
        remediation_2: value["remediation2"],
    };
}
