/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MsahandlerOSUserResource
 */
export interface MsahandlerOSUserResource {
    /**
     *
     * @type {string}
     * @memberof MsahandlerOSUserResource
     */
    aid: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerOSUserResource
     */
    firstSeen?: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerOSUserResource
     */
    lastSeen?: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerOSUserResource
     */
    objectSid?: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerOSUserResource
     */
    username: string;
}

/**
 * Check if a given object implements the MsahandlerOSUserResource interface.
 */
export function instanceOfMsahandlerOSUserResource(value: object): value is MsahandlerOSUserResource {
    if (!("aid" in value) || value["aid"] === undefined) return false;
    if (!("username" in value) || value["username"] === undefined) return false;
    return true;
}

export function MsahandlerOSUserResourceFromJSON(json: any): MsahandlerOSUserResource {
    return MsahandlerOSUserResourceFromJSONTyped(json, false);
}

export function MsahandlerOSUserResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MsahandlerOSUserResource {
    if (json == null) {
        return json;
    }
    return {
        aid: json["Aid"],
        firstSeen: json["FirstSeen"] == null ? undefined : json["FirstSeen"],
        lastSeen: json["LastSeen"] == null ? undefined : json["LastSeen"],
        objectSid: json["ObjectSid"] == null ? undefined : json["ObjectSid"],
        username: json["Username"],
    };
}

export function MsahandlerOSUserResourceToJSON(value?: MsahandlerOSUserResource | null): any {
    if (value == null) {
        return value;
    }
    return {
        Aid: value["aid"],
        FirstSeen: value["firstSeen"],
        LastSeen: value["lastSeen"],
        ObjectSid: value["objectSid"],
        Username: value["username"],
    };
}
