/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { MsahandlerClassifiedFileAccess } from "./MsahandlerClassifiedFileAccess";
import { MsahandlerClassifiedFileAccessFromJSON, MsahandlerClassifiedFileAccessFromJSONTyped, MsahandlerClassifiedFileAccessToJSON } from "./MsahandlerClassifiedFileAccess";

/**
 *
 * @export
 * @interface MsahandlerClassifiedFileProcess
 */
export interface MsahandlerClassifiedFileProcess {
    /**
     *
     * @type {Array<MsahandlerClassifiedFileAccess>}
     * @memberof MsahandlerClassifiedFileProcess
     */
    classifiedFileAccesses: Array<MsahandlerClassifiedFileAccess>;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileProcess
     */
    commandLine: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileProcess
     */
    imageFileName: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileProcess
     */
    processId: string;
}

/**
 * Check if a given object implements the MsahandlerClassifiedFileProcess interface.
 */
export function instanceOfMsahandlerClassifiedFileProcess(value: object): value is MsahandlerClassifiedFileProcess {
    if (!("classifiedFileAccesses" in value) || value["classifiedFileAccesses"] === undefined) return false;
    if (!("commandLine" in value) || value["commandLine"] === undefined) return false;
    if (!("imageFileName" in value) || value["imageFileName"] === undefined) return false;
    if (!("processId" in value) || value["processId"] === undefined) return false;
    return true;
}

export function MsahandlerClassifiedFileProcessFromJSON(json: any): MsahandlerClassifiedFileProcess {
    return MsahandlerClassifiedFileProcessFromJSONTyped(json, false);
}

export function MsahandlerClassifiedFileProcessFromJSONTyped(json: any, ignoreDiscriminator: boolean): MsahandlerClassifiedFileProcess {
    if (json == null) {
        return json;
    }
    return {
        classifiedFileAccesses: (json["classified_file_accesses"] as Array<any>).map(MsahandlerClassifiedFileAccessFromJSON),
        commandLine: json["command_line"],
        imageFileName: json["image_file_name"],
        processId: json["process_id"],
    };
}

export function MsahandlerClassifiedFileProcessToJSON(value?: MsahandlerClassifiedFileProcess | null): any {
    if (value == null) {
        return value;
    }
    return {
        classified_file_accesses: (value["classifiedFileAccesses"] as Array<any>).map(MsahandlerClassifiedFileAccessToJSON),
        command_line: value["commandLine"],
        image_file_name: value["imageFileName"],
        process_id: value["processId"],
    };
}
