/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MsahandlerClassifiedFileAccess
 */
export interface MsahandlerClassifiedFileAccess {
    /**
     *
     * @type {object}
     * @memberof MsahandlerClassifiedFileAccess
     */
    classifications: object;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileAccess
     */
    eventCloudTime: string;
    /**
     *
     * @type {object}
     * @memberof MsahandlerClassifiedFileAccess
     */
    eventCount: object;
    /**
     *
     * @type {Array<object>}
     * @memberof MsahandlerClassifiedFileAccess
     */
    files: Array<object>;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileAccess
     */
    localAppId: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileAccess
     */
    localAppName: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileAccess
     */
    origin: string;
    /**
     *
     * @type {object}
     * @memberof MsahandlerClassifiedFileAccess
     */
    patternCategories: object;
    /**
     *
     * @type {object}
     * @memberof MsahandlerClassifiedFileAccess
     */
    ruleActions: object;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileAccess
     */
    vertexId: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileAccess
     */
    windowEnd: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerClassifiedFileAccess
     */
    windowStart: string;
}

/**
 * Check if a given object implements the MsahandlerClassifiedFileAccess interface.
 */
export function instanceOfMsahandlerClassifiedFileAccess(value: object): value is MsahandlerClassifiedFileAccess {
    if (!("classifications" in value) || value["classifications"] === undefined) return false;
    if (!("eventCloudTime" in value) || value["eventCloudTime"] === undefined) return false;
    if (!("eventCount" in value) || value["eventCount"] === undefined) return false;
    if (!("files" in value) || value["files"] === undefined) return false;
    if (!("localAppId" in value) || value["localAppId"] === undefined) return false;
    if (!("localAppName" in value) || value["localAppName"] === undefined) return false;
    if (!("origin" in value) || value["origin"] === undefined) return false;
    if (!("patternCategories" in value) || value["patternCategories"] === undefined) return false;
    if (!("ruleActions" in value) || value["ruleActions"] === undefined) return false;
    if (!("vertexId" in value) || value["vertexId"] === undefined) return false;
    if (!("windowEnd" in value) || value["windowEnd"] === undefined) return false;
    if (!("windowStart" in value) || value["windowStart"] === undefined) return false;
    return true;
}

export function MsahandlerClassifiedFileAccessFromJSON(json: any): MsahandlerClassifiedFileAccess {
    return MsahandlerClassifiedFileAccessFromJSONTyped(json, false);
}

export function MsahandlerClassifiedFileAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): MsahandlerClassifiedFileAccess {
    if (json == null) {
        return json;
    }
    return {
        classifications: json["classifications"],
        eventCloudTime: json["event_cloud_time"],
        eventCount: json["event_count"],
        files: json["files"],
        localAppId: json["local_app_id"],
        localAppName: json["local_app_name"],
        origin: json["origin"],
        patternCategories: json["pattern_categories"],
        ruleActions: json["rule_actions"],
        vertexId: json["vertex_id"],
        windowEnd: json["window_end"],
        windowStart: json["window_start"],
    };
}

export function MsahandlerClassifiedFileAccessToJSON(value?: MsahandlerClassifiedFileAccess | null): any {
    if (value == null) {
        return value;
    }
    return {
        classifications: value["classifications"],
        event_cloud_time: value["eventCloudTime"],
        event_count: value["eventCount"],
        files: value["files"],
        local_app_id: value["localAppId"],
        local_app_name: value["localAppName"],
        origin: value["origin"],
        pattern_categories: value["patternCategories"],
        rule_actions: value["ruleActions"],
        vertex_id: value["vertexId"],
        window_end: value["windowEnd"],
        window_start: value["windowStart"],
    };
}
