/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MsahandlerModuleRef
 */
export interface MsahandlerModuleRef {
    /**
     *
     * @type {string}
     * @memberof MsahandlerModuleRef
     */
    imageFileName: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerModuleRef
     */
    mD5HashData: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerModuleRef
     */
    sHA256HashData: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerModuleRef
     */
    targetFileName: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerModuleRef
     */
    id: string;
}

/**
 * Check if a given object implements the MsahandlerModuleRef interface.
 */
export function instanceOfMsahandlerModuleRef(value: object): value is MsahandlerModuleRef {
    if (!("imageFileName" in value) || value["imageFileName"] === undefined) return false;
    if (!("mD5HashData" in value) || value["mD5HashData"] === undefined) return false;
    if (!("sHA256HashData" in value) || value["sHA256HashData"] === undefined) return false;
    if (!("targetFileName" in value) || value["targetFileName"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    return true;
}

export function MsahandlerModuleRefFromJSON(json: any): MsahandlerModuleRef {
    return MsahandlerModuleRefFromJSONTyped(json, false);
}

export function MsahandlerModuleRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): MsahandlerModuleRef {
    if (json == null) {
        return json;
    }
    return {
        imageFileName: json["ImageFileName"],
        mD5HashData: json["MD5HashData"],
        sHA256HashData: json["SHA256HashData"],
        targetFileName: json["TargetFileName"],
        id: json["__id"],
    };
}

export function MsahandlerModuleRefToJSON(value?: MsahandlerModuleRef | null): any {
    if (value == null) {
        return value;
    }
    return {
        ImageFileName: value["imageFileName"],
        MD5HashData: value["mD5HashData"],
        SHA256HashData: value["sHA256HashData"],
        TargetFileName: value["targetFileName"],
        __id: value["id"],
    };
}
