/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MsahandlerUserIDRef
 */
export interface MsahandlerUserIDRef {
    /**
     *
     * @type {string}
     * @memberof MsahandlerUserIDRef
     */
    logonDomain: string;
    /**
     *
     * @type {boolean}
     * @memberof MsahandlerUserIDRef
     */
    userIsAdmin: boolean;
    /**
     *
     * @type {string}
     * @memberof MsahandlerUserIDRef
     */
    userName: string;
    /**
     *
     * @type {string}
     * @memberof MsahandlerUserIDRef
     */
    id: string;
}

/**
 * Check if a given object implements the MsahandlerUserIDRef interface.
 */
export function instanceOfMsahandlerUserIDRef(value: object): value is MsahandlerUserIDRef {
    if (!("logonDomain" in value) || value["logonDomain"] === undefined) return false;
    if (!("userIsAdmin" in value) || value["userIsAdmin"] === undefined) return false;
    if (!("userName" in value) || value["userName"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    return true;
}

export function MsahandlerUserIDRefFromJSON(json: any): MsahandlerUserIDRef {
    return MsahandlerUserIDRefFromJSONTyped(json, false);
}

export function MsahandlerUserIDRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): MsahandlerUserIDRef {
    if (json == null) {
        return json;
    }
    return {
        logonDomain: json["LogonDomain"],
        userIsAdmin: json["UserIsAdmin"],
        userName: json["UserName"],
        id: json["__id"],
    };
}

export function MsahandlerUserIDRefToJSON(value?: MsahandlerUserIDRef | null): any {
    if (value == null) {
        return value;
    }
    return {
        LogonDomain: value["logonDomain"],
        UserIsAdmin: value["userIsAdmin"],
        UserName: value["userName"],
        __id: value["id"],
    };
}
