/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NvaapiGlobalConfigScanner
 */
export interface NvaapiGlobalConfigScanner {
    /**
     * Describes whether this scanner is enabled or not
     * @type {boolean}
     * @memberof NvaapiGlobalConfigScanner
     */
    enabled: boolean;
    /**
     * Either the sensor AID or host group ID depending on type
     * @type {string}
     * @memberof NvaapiGlobalConfigScanner
     */
    id: string;
    /**
     * Describes if this scanner is a host group or individual host
     * @type {string}
     * @memberof NvaapiGlobalConfigScanner
     */
    type: NvaapiGlobalConfigScannerTypeEnum;
}

/**
 * @export
 */
export const NvaapiGlobalConfigScannerTypeEnum = {
    HostGrouphost: "host_group,host",
} as const;
export type NvaapiGlobalConfigScannerTypeEnum = (typeof NvaapiGlobalConfigScannerTypeEnum)[keyof typeof NvaapiGlobalConfigScannerTypeEnum];

/**
 * Check if a given object implements the NvaapiGlobalConfigScanner interface.
 */
export function instanceOfNvaapiGlobalConfigScanner(value: object): value is NvaapiGlobalConfigScanner {
    if (!("enabled" in value) || value["enabled"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    return true;
}

export function NvaapiGlobalConfigScannerFromJSON(json: any): NvaapiGlobalConfigScanner {
    return NvaapiGlobalConfigScannerFromJSONTyped(json, false);
}

export function NvaapiGlobalConfigScannerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NvaapiGlobalConfigScanner {
    if (json == null) {
        return json;
    }
    return {
        enabled: json["enabled"],
        id: json["id"],
        type: json["type"],
    };
}

export function NvaapiGlobalConfigScannerToJSON(value?: NvaapiGlobalConfigScanner | null): any {
    if (value == null) {
        return value;
    }
    return {
        enabled: value["enabled"],
        id: value["id"],
        type: value["type"],
    };
}
