/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Represents IP target specification
 * @export
 * @interface NvaapiTargetIP
 */
export interface NvaapiTargetIP {
    /**
     * Formatted as either CIDR or specific IP or IP range
     * @type {Array<string>}
     * @memberof NvaapiTargetIP
     */
    ipSpecs?: Array<string>;
    /**
     * The zone ID associated with this scan
     * @type {string}
     * @memberof NvaapiTargetIP
     */
    zoneId: string;
}

/**
 * Check if a given object implements the NvaapiTargetIP interface.
 */
export function instanceOfNvaapiTargetIP(value: object): value is NvaapiTargetIP {
    if (!("zoneId" in value) || value["zoneId"] === undefined) return false;
    return true;
}

export function NvaapiTargetIPFromJSON(json: any): NvaapiTargetIP {
    return NvaapiTargetIPFromJSONTyped(json, false);
}

export function NvaapiTargetIPFromJSONTyped(json: any, ignoreDiscriminator: boolean): NvaapiTargetIP {
    if (json == null) {
        return json;
    }
    return {
        ipSpecs: json["ip_specs"] == null ? undefined : json["ip_specs"],
        zoneId: json["zone_id"],
    };
}

export function NvaapiTargetIPToJSON(value?: NvaapiTargetIP | null): any {
    if (value == null) {
        return value;
    }
    return {
        ip_specs: value["ipSpecs"],
        zone_id: value["zoneId"],
    };
}
