/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { NswipScanFlags } from "./NswipScanFlags";
import { NswipScanFlagsFromJSON, NswipScanFlagsFromJSONTyped, NswipScanFlagsToJSON } from "./NswipScanFlags";

/**
 * Represents a template entity
 * @export
 * @interface NvaapiTemplate
 */
export interface NvaapiTemplate {
    /**
     * The active check level associated with the template
     * @type {string}
     * @memberof NvaapiTemplate
     */
    activeCheckLevel: NvaapiTemplateActiveCheckLevelEnum;
    /**
     * Additional TCP ports associated with the template
     * @type {Array<string>}
     * @memberof NvaapiTemplate
     */
    additionalTcpPorts?: Array<string>;
    /**
     * Additional UDP ports associated with the template
     * @type {Array<string>}
     * @memberof NvaapiTemplate
     */
    additionalUdpPorts?: Array<string>;
    /**
     * Automatically include new detections in the template
     * @type {boolean}
     * @memberof NvaapiTemplate
     */
    autoIncludeNewDetections: boolean;
    /**
     * The customer who owns the template
     * @type {string}
     * @memberof NvaapiTemplate
     */
    cid: string;
    /**
     * The user that created the template
     * @type {string}
     * @memberof NvaapiTemplate
     */
    createdBy: string;
    /**
     * The time at which the template was created
     * @type {string}
     * @memberof NvaapiTemplate
     */
    createdTimestamp: string;
    /**
     * Detections associated with the template
     * @type {Array<string>}
     * @memberof NvaapiTemplate
     */
    detections: Array<string>;
    /**
     * Excluded TCP ports associated with the template
     * @type {Array<string>}
     * @memberof NvaapiTemplate
     */
    excludedTcpPorts?: Array<string>;
    /**
     * Excluded UDP ports associated with the template
     * @type {Array<string>}
     * @memberof NvaapiTemplate
     */
    excludedUdpPorts?: Array<string>;
    /**
     * The unique identifier of the template
     * @type {string}
     * @memberof NvaapiTemplate
     */
    id: string;
    /**
     * Ignore TCP resets associated with the template
     * @type {boolean}
     * @memberof NvaapiTemplate
     */
    ignoreTcpResets: boolean;
    /**
     * The name which was given to the template
     * @type {string}
     * @memberof NvaapiTemplate
     */
    name: string;
    /**
     * The port scan level associated with the template
     * @type {string}
     * @memberof NvaapiTemplate
     */
    portsScanLevel: NvaapiTemplatePortsScanLevelEnum;
    /**
     *
     * @type {NswipScanFlags}
     * @memberof NvaapiTemplate
     */
    scanFlags?: NswipScanFlags;
    /**
     * The scan intensity at which scans will run from this template
     * @type {string}
     * @memberof NvaapiTemplate
     */
    scanIntensity: NvaapiTemplateScanIntensityEnum;
    /**
     * The type of the template
     * @type {string}
     * @memberof NvaapiTemplate
     */
    type: NvaapiTemplateTypeEnum;
    /**
     * The user that updated the template
     * @type {string}
     * @memberof NvaapiTemplate
     */
    updatedBy?: string;
    /**
     * The time at which the template was updated
     * @type {string}
     * @memberof NvaapiTemplate
     */
    updatedTimestamp?: string;
}

/**
 * @export
 */
export const NvaapiTemplateActiveCheckLevelEnum = {
    ActiveCheckSafeOnlyactiveCheckAll: "active_check_safe_only,active_check_all",
} as const;
export type NvaapiTemplateActiveCheckLevelEnum = (typeof NvaapiTemplateActiveCheckLevelEnum)[keyof typeof NvaapiTemplateActiveCheckLevelEnum];

/**
 * @export
 */
export const NvaapiTemplatePortsScanLevelEnum = {
    DefaultallPortscustom: "default,all_ports,custom",
} as const;
export type NvaapiTemplatePortsScanLevelEnum = (typeof NvaapiTemplatePortsScanLevelEnum)[keyof typeof NvaapiTemplatePortsScanLevelEnum];

/**
 * @export
 */
export const NvaapiTemplateScanIntensityEnum = {
    Basicstandardcautiousmaximumcustom: "basic,standard,cautious,maximum,custom",
} as const;
export type NvaapiTemplateScanIntensityEnum = (typeof NvaapiTemplateScanIntensityEnum)[keyof typeof NvaapiTemplateScanIntensityEnum];

/**
 * @export
 */
export const NvaapiTemplateTypeEnum = {
    Discoveryassessment: "discovery,assessment",
} as const;
export type NvaapiTemplateTypeEnum = (typeof NvaapiTemplateTypeEnum)[keyof typeof NvaapiTemplateTypeEnum];

/**
 * Check if a given object implements the NvaapiTemplate interface.
 */
export function instanceOfNvaapiTemplate(value: object): value is NvaapiTemplate {
    if (!("activeCheckLevel" in value) || value["activeCheckLevel"] === undefined) return false;
    if (!("autoIncludeNewDetections" in value) || value["autoIncludeNewDetections"] === undefined) return false;
    if (!("cid" in value) || value["cid"] === undefined) return false;
    if (!("createdBy" in value) || value["createdBy"] === undefined) return false;
    if (!("createdTimestamp" in value) || value["createdTimestamp"] === undefined) return false;
    if (!("detections" in value) || value["detections"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("ignoreTcpResets" in value) || value["ignoreTcpResets"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("portsScanLevel" in value) || value["portsScanLevel"] === undefined) return false;
    if (!("scanIntensity" in value) || value["scanIntensity"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    return true;
}

export function NvaapiTemplateFromJSON(json: any): NvaapiTemplate {
    return NvaapiTemplateFromJSONTyped(json, false);
}

export function NvaapiTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NvaapiTemplate {
    if (json == null) {
        return json;
    }
    return {
        activeCheckLevel: json["active_check_level"],
        additionalTcpPorts: json["additional_tcp_ports"] == null ? undefined : json["additional_tcp_ports"],
        additionalUdpPorts: json["additional_udp_ports"] == null ? undefined : json["additional_udp_ports"],
        autoIncludeNewDetections: json["auto_include_new_detections"],
        cid: json["cid"],
        createdBy: json["created_by"],
        createdTimestamp: json["created_timestamp"],
        detections: json["detections"],
        excludedTcpPorts: json["excluded_tcp_ports"] == null ? undefined : json["excluded_tcp_ports"],
        excludedUdpPorts: json["excluded_udp_ports"] == null ? undefined : json["excluded_udp_ports"],
        id: json["id"],
        ignoreTcpResets: json["ignore_tcp_resets"],
        name: json["name"],
        portsScanLevel: json["ports_scan_level"],
        scanFlags: json["scan_flags"] == null ? undefined : NswipScanFlagsFromJSON(json["scan_flags"]),
        scanIntensity: json["scan_intensity"],
        type: json["type"],
        updatedBy: json["updated_by"] == null ? undefined : json["updated_by"],
        updatedTimestamp: json["updated_timestamp"] == null ? undefined : json["updated_timestamp"],
    };
}

export function NvaapiTemplateToJSON(value?: NvaapiTemplate | null): any {
    if (value == null) {
        return value;
    }
    return {
        active_check_level: value["activeCheckLevel"],
        additional_tcp_ports: value["additionalTcpPorts"],
        additional_udp_ports: value["additionalUdpPorts"],
        auto_include_new_detections: value["autoIncludeNewDetections"],
        cid: value["cid"],
        created_by: value["createdBy"],
        created_timestamp: value["createdTimestamp"],
        detections: value["detections"],
        excluded_tcp_ports: value["excludedTcpPorts"],
        excluded_udp_ports: value["excludedUdpPorts"],
        id: value["id"],
        ignore_tcp_resets: value["ignoreTcpResets"],
        name: value["name"],
        ports_scan_level: value["portsScanLevel"],
        scan_flags: NswipScanFlagsToJSON(value["scanFlags"]),
        scan_intensity: value["scanIntensity"],
        type: value["type"],
        updated_by: value["updatedBy"],
        updated_timestamp: value["updatedTimestamp"],
    };
}
