/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Represents a request to create a network (UDN)
 * @export
 * @interface NvaapiNetworkCreateRequest
 */
export interface NvaapiNetworkCreateRequest {
    /**
     * The name which was given to the network
     * @type {string}
     * @memberof NvaapiNetworkCreateRequest
     */
    name: string;
    /**
     * The set of scanners assigned to the network
     * @type {Array<string>}
     * @memberof NvaapiNetworkCreateRequest
     */
    scannerAids?: Array<string>;
    /**
     * The scanner assignment type for the network
     * @type {string}
     * @memberof NvaapiNetworkCreateRequest
     */
    scannerAssignmentType?: NvaapiNetworkCreateRequestScannerAssignmentTypeEnum;
    /**
     * The subnet included in the network
     * @type {string}
     * @memberof NvaapiNetworkCreateRequest
     */
    subnet: string;
    /**
     * The zone to which the network is assigned
     * @type {string}
     * @memberof NvaapiNetworkCreateRequest
     */
    zoneId: string;
}

/**
 * @export
 */
export const NvaapiNetworkCreateRequestScannerAssignmentTypeEnum = {
    Localzonemanual: "local,zone,manual",
} as const;
export type NvaapiNetworkCreateRequestScannerAssignmentTypeEnum = (typeof NvaapiNetworkCreateRequestScannerAssignmentTypeEnum)[keyof typeof NvaapiNetworkCreateRequestScannerAssignmentTypeEnum];

/**
 * Check if a given object implements the NvaapiNetworkCreateRequest interface.
 */
export function instanceOfNvaapiNetworkCreateRequest(value: object): value is NvaapiNetworkCreateRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("subnet" in value) || value["subnet"] === undefined) return false;
    if (!("zoneId" in value) || value["zoneId"] === undefined) return false;
    return true;
}

export function NvaapiNetworkCreateRequestFromJSON(json: any): NvaapiNetworkCreateRequest {
    return NvaapiNetworkCreateRequestFromJSONTyped(json, false);
}

export function NvaapiNetworkCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NvaapiNetworkCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        scannerAids: json["scanner_aids"] == null ? undefined : json["scanner_aids"],
        scannerAssignmentType: json["scanner_assignment_type"] == null ? undefined : json["scanner_assignment_type"],
        subnet: json["subnet"],
        zoneId: json["zone_id"],
    };
}

export function NvaapiNetworkCreateRequestToJSON(value?: NvaapiNetworkCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        name: value["name"],
        scanner_aids: value["scannerAids"],
        scanner_assignment_type: value["scannerAssignmentType"],
        subnet: value["subnet"],
        zone_id: value["zoneId"],
    };
}
