/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Represents a zone entity
 * @export
 * @interface NvaapiZone
 */
export interface NvaapiZone {
    /**
     * The customer to which the zone belongs
     * @type {string}
     * @memberof NvaapiZone
     */
    cid: string;
    /**
     * The user that created the zone
     * @type {string}
     * @memberof NvaapiZone
     */
    createdBy: string;
    /**
     * The time at which the zone was created
     * @type {string}
     * @memberof NvaapiZone
     */
    createdTimestamp: string;
    /**
     * Indicates whether networks contained by the zone have conflicts within them
     * @type {boolean}
     * @memberof NvaapiZone
     */
    hasConflict: boolean;
    /**
     * The unique identifier of the zone
     * @type {string}
     * @memberof NvaapiZone
     */
    id: string;
    /**
     * Indicates whether this zone is the default zone
     * @type {boolean}
     * @memberof NvaapiZone
     */
    isDefault: boolean;
    /**
     * The name which was given to the zone
     * @type {string}
     * @memberof NvaapiZone
     */
    name: string;
    /**
     * The scanner AIDs assigned to the zone
     * @type {Array<string>}
     * @memberof NvaapiZone
     */
    scanners?: Array<string>;
    /**
     * The user that updated the zone
     * @type {string}
     * @memberof NvaapiZone
     */
    updatedBy?: string;
    /**
     * The time at which the zone was updated
     * @type {string}
     * @memberof NvaapiZone
     */
    updatedTimestamp?: string;
}

/**
 * Check if a given object implements the NvaapiZone interface.
 */
export function instanceOfNvaapiZone(value: object): value is NvaapiZone {
    if (!("cid" in value) || value["cid"] === undefined) return false;
    if (!("createdBy" in value) || value["createdBy"] === undefined) return false;
    if (!("createdTimestamp" in value) || value["createdTimestamp"] === undefined) return false;
    if (!("hasConflict" in value) || value["hasConflict"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("isDefault" in value) || value["isDefault"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function NvaapiZoneFromJSON(json: any): NvaapiZone {
    return NvaapiZoneFromJSONTyped(json, false);
}

export function NvaapiZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): NvaapiZone {
    if (json == null) {
        return json;
    }
    return {
        cid: json["cid"],
        createdBy: json["created_by"],
        createdTimestamp: json["created_timestamp"],
        hasConflict: json["has_conflict"],
        id: json["id"],
        isDefault: json["is_default"],
        name: json["name"],
        scanners: json["scanners"] == null ? undefined : json["scanners"],
        updatedBy: json["updated_by"] == null ? undefined : json["updated_by"],
        updatedTimestamp: json["updated_timestamp"] == null ? undefined : json["updated_timestamp"],
    };
}

export function NvaapiZoneToJSON(value?: NvaapiZone | null): any {
    if (value == null) {
        return value;
    }
    return {
        cid: value["cid"],
        created_by: value["createdBy"],
        created_timestamp: value["createdTimestamp"],
        has_conflict: value["hasConflict"],
        id: value["id"],
        is_default: value["isDefault"],
        name: value["name"],
        scanners: value["scanners"],
        updated_by: value["updatedBy"],
        updated_timestamp: value["updatedTimestamp"],
    };
}
