/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { NvaapiScanExclusionV1 } from "./NvaapiScanExclusionV1";
import { NvaapiScanExclusionV1FromJSON, NvaapiScanExclusionV1FromJSONTyped, NvaapiScanExclusionV1ToJSON } from "./NvaapiScanExclusionV1";
import type { NvaapiAutoConfirmOwnership } from "./NvaapiAutoConfirmOwnership";
import { NvaapiAutoConfirmOwnershipFromJSON, NvaapiAutoConfirmOwnershipFromJSONTyped, NvaapiAutoConfirmOwnershipToJSON } from "./NvaapiAutoConfirmOwnership";
import type { NvaapiGlobalConfigScanner } from "./NvaapiGlobalConfigScanner";
import { NvaapiGlobalConfigScannerFromJSON, NvaapiGlobalConfigScannerFromJSONTyped, NvaapiGlobalConfigScannerToJSON } from "./NvaapiGlobalConfigScanner";

/**
 *
 * @export
 * @interface NvaapiGlobalConfigUpdateRequest
 */
export interface NvaapiGlobalConfigUpdateRequest {
    /**
     *
     * @type {NvaapiAutoConfirmOwnership}
     * @memberof NvaapiGlobalConfigUpdateRequest
     */
    autoConfirmOwnership?: NvaapiAutoConfirmOwnership;
    /**
     * Maximum scan tasks to run in parallel
     * @type {number}
     * @memberof NvaapiGlobalConfigUpdateRequest
     */
    maxConcurrentTasks?: number;
    /**
     * Attempts to stop ongoing network scans and disables further scans from being executed
     * @type {boolean}
     * @memberof NvaapiGlobalConfigUpdateRequest
     */
    networkScanningEnabled?: boolean;
    /**
     *
     * @type {NvaapiScanExclusionV1}
     * @memberof NvaapiGlobalConfigUpdateRequest
     */
    scanExclusion: NvaapiScanExclusionV1;
    /**
     * Describes the list of assets that will act as eligible scanners
     * @type {Array<NvaapiGlobalConfigScanner>}
     * @memberof NvaapiGlobalConfigUpdateRequest
     */
    scanners?: Array<NvaapiGlobalConfigScanner>;
    /**
     * Describes the list of assets that will always be excluded from being selected as scanners
     * @type {Array<NvaapiGlobalConfigScanner>}
     * @memberof NvaapiGlobalConfigUpdateRequest
     */
    scannersExclusion?: Array<NvaapiGlobalConfigScanner>;
}

/**
 * Check if a given object implements the NvaapiGlobalConfigUpdateRequest interface.
 */
export function instanceOfNvaapiGlobalConfigUpdateRequest(value: object): value is NvaapiGlobalConfigUpdateRequest {
    if (!("scanExclusion" in value) || value["scanExclusion"] === undefined) return false;
    return true;
}

export function NvaapiGlobalConfigUpdateRequestFromJSON(json: any): NvaapiGlobalConfigUpdateRequest {
    return NvaapiGlobalConfigUpdateRequestFromJSONTyped(json, false);
}

export function NvaapiGlobalConfigUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NvaapiGlobalConfigUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        autoConfirmOwnership: json["auto_confirm_ownership"] == null ? undefined : NvaapiAutoConfirmOwnershipFromJSON(json["auto_confirm_ownership"]),
        maxConcurrentTasks: json["max_concurrent_tasks"] == null ? undefined : json["max_concurrent_tasks"],
        networkScanningEnabled: json["network_scanning_enabled"] == null ? undefined : json["network_scanning_enabled"],
        scanExclusion: NvaapiScanExclusionV1FromJSON(json["scan_exclusion"]),
        scanners: json["scanners"] == null ? undefined : (json["scanners"] as Array<any>).map(NvaapiGlobalConfigScannerFromJSON),
        scannersExclusion: json["scanners_exclusion"] == null ? undefined : (json["scanners_exclusion"] as Array<any>).map(NvaapiGlobalConfigScannerFromJSON),
    };
}

export function NvaapiGlobalConfigUpdateRequestToJSON(value?: NvaapiGlobalConfigUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        auto_confirm_ownership: NvaapiAutoConfirmOwnershipToJSON(value["autoConfirmOwnership"]),
        max_concurrent_tasks: value["maxConcurrentTasks"],
        network_scanning_enabled: value["networkScanningEnabled"],
        scan_exclusion: NvaapiScanExclusionV1ToJSON(value["scanExclusion"]),
        scanners: value["scanners"] == null ? undefined : (value["scanners"] as Array<any>).map(NvaapiGlobalConfigScannerToJSON),
        scanners_exclusion: value["scannersExclusion"] == null ? undefined : (value["scannersExclusion"] as Array<any>).map(NvaapiGlobalConfigScannerToJSON),
    };
}
