/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SdkAlertEvidenceSelector } from "./SdkAlertEvidenceSelector";
import { SdkAlertEvidenceSelectorFromJSON, SdkAlertEvidenceSelectorFromJSONTyped, SdkAlertEvidenceSelectorToJSON } from "./SdkAlertEvidenceSelector";

/**
 *
 * @export
 * @interface OperationsAddAlertsToCaseRequestV2
 */
export interface OperationsAddAlertsToCaseRequestV2 {
    /**
     *
     * @type {Array<SdkAlertEvidenceSelector>}
     * @memberof OperationsAddAlertsToCaseRequestV2
     */
    alerts: Array<SdkAlertEvidenceSelector>;
    /**
     *
     * @type {string}
     * @memberof OperationsAddAlertsToCaseRequestV2
     */
    id: string;
}

/**
 * Check if a given object implements the OperationsAddAlertsToCaseRequestV2 interface.
 */
export function instanceOfOperationsAddAlertsToCaseRequestV2(value: object): value is OperationsAddAlertsToCaseRequestV2 {
    if (!("alerts" in value) || value["alerts"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    return true;
}

export function OperationsAddAlertsToCaseRequestV2FromJSON(json: any): OperationsAddAlertsToCaseRequestV2 {
    return OperationsAddAlertsToCaseRequestV2FromJSONTyped(json, false);
}

export function OperationsAddAlertsToCaseRequestV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationsAddAlertsToCaseRequestV2 {
    if (json == null) {
        return json;
    }
    return {
        alerts: (json["alerts"] as Array<any>).map(SdkAlertEvidenceSelectorFromJSON),
        id: json["id"],
    };
}

export function OperationsAddAlertsToCaseRequestV2ToJSON(value?: OperationsAddAlertsToCaseRequestV2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        alerts: (value["alerts"] as Array<any>).map(SdkAlertEvidenceSelectorToJSON),
        id: value["id"],
    };
}
