/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PatchdeployerapiDeploymentConfigSchedule } from "./PatchdeployerapiDeploymentConfigSchedule";
import {
    PatchdeployerapiDeploymentConfigScheduleFromJSON,
    PatchdeployerapiDeploymentConfigScheduleFromJSONTyped,
    PatchdeployerapiDeploymentConfigScheduleToJSON,
} from "./PatchdeployerapiDeploymentConfigSchedule";
import type { PatchdeployerapiPostPatchScriptOptionsPatch } from "./PatchdeployerapiPostPatchScriptOptionsPatch";
import {
    PatchdeployerapiPostPatchScriptOptionsPatchFromJSON,
    PatchdeployerapiPostPatchScriptOptionsPatchFromJSONTyped,
    PatchdeployerapiPostPatchScriptOptionsPatchToJSON,
} from "./PatchdeployerapiPostPatchScriptOptionsPatch";
import type { PatchdeployerapiPrePatchScriptOptionsPatch } from "./PatchdeployerapiPrePatchScriptOptionsPatch";
import {
    PatchdeployerapiPrePatchScriptOptionsPatchFromJSON,
    PatchdeployerapiPrePatchScriptOptionsPatchFromJSONTyped,
    PatchdeployerapiPrePatchScriptOptionsPatchToJSON,
} from "./PatchdeployerapiPrePatchScriptOptionsPatch";
import type { PatchdeployerapiRebootOptions } from "./PatchdeployerapiRebootOptions";
import { PatchdeployerapiRebootOptionsFromJSON, PatchdeployerapiRebootOptionsFromJSONTyped, PatchdeployerapiRebootOptionsToJSON } from "./PatchdeployerapiRebootOptions";
import type { PatchdeployerapiUserNotificationOptions } from "./PatchdeployerapiUserNotificationOptions";
import {
    PatchdeployerapiUserNotificationOptionsFromJSON,
    PatchdeployerapiUserNotificationOptionsFromJSONTyped,
    PatchdeployerapiUserNotificationOptionsToJSON,
} from "./PatchdeployerapiUserNotificationOptions";

/**
 *
 * @export
 * @interface PatchdeployerapiDeploymentConfigUpdateRequestV1
 */
export interface PatchdeployerapiDeploymentConfigUpdateRequestV1 {
    /**
     * Block filter group refs (is_block=true). Omit to leave unchanged; send [] to clear.
     * @type {Array<string>}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    blockFilterGroupIds?: Array<string>;
    /**
     * Whether the deployment configuration is disabled
     * @type {boolean}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    disabled?: boolean;
    /**
     * ID of the deployment configuration to update
     * @type {string}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    id: string;
    /**
     * Name of the deployment configuration
     * @type {string}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    name?: string;
    /**
     * References to patch filter groups (is_block=false). Omit to leave existing references unchanged; send [] to clear all references.
     * @type {Array<string>}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    patchFilterGroupIds?: Array<string>;
    /**
     * Platforms which are targeted by this deployment configuration
     * @type {string}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    platform?: PatchdeployerapiDeploymentConfigUpdateRequestV1PlatformEnum;
    /**
     *
     * @type {PatchdeployerapiPostPatchScriptOptionsPatch}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    postPatchScriptOptions?: PatchdeployerapiPostPatchScriptOptionsPatch;
    /**
     *
     * @type {PatchdeployerapiPrePatchScriptOptionsPatch}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    prePatchScriptOptions?: PatchdeployerapiPrePatchScriptOptionsPatch;
    /**
     * Whether patches should be downloaded to a host ahead of installation
     * @type {boolean}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    prestage?: boolean;
    /**
     *
     * @type {PatchdeployerapiRebootOptions}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    rebootOptions?: PatchdeployerapiRebootOptions;
    /**
     * Whether the deployment is recurring or one-time scheduled
     * @type {boolean}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    recurring?: boolean;
    /**
     * Whether the Deployment should run immediately
     * @type {boolean}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    runNowNoSchedule?: boolean;
    /**
     *
     * @type {PatchdeployerapiDeploymentConfigSchedule}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    schedule?: PatchdeployerapiDeploymentConfigSchedule;
    /**
     * FQL query for hosts to target. Supported fields: host.aid | host.name | host.device_type | host.os_version | host.last_seen | host.asset_criticality | host.organizational_unit | host.country | host.tags | host.groups | host.internet_exposure | last_scanned
     * @type {string}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    targetHosts?: string;
    /**
     * FQL query for patches to apply. OS deployment supported fields: patch.id | patch.name | patch.version | patch.severity | patch.type | patch.classifications | patch.release_date | patch.vendor_name | patch.vendor_url | patch.size | patch.supersedence | patch.reboot_requirement | patch.repo | patch.description | vulnerabilities.exprt_ai_rating | vulnerabilities.id. App deployment supported fields: available_update.id | available_update.vendor | available_update.name | available_update.version | available_update.arch | available_update.locale | available_update.scope | available_update.application_id | available_update.source | available_update.publish_date | available_update.family_name | available_update.family_category | available_update.vendor_name_version | available_update.version_sequence | available_update.is_latest_version | available_update.is_in_place_update | installation_status | last_scanned | platform | vulnerabilities.id | vulnerabilities.exprt_ai_rating | vulnerabilities.cvss_attack_vector
     * @type {string}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    targetPatches?: string;
    /**
     *
     * @type {PatchdeployerapiUserNotificationOptions}
     * @memberof PatchdeployerapiDeploymentConfigUpdateRequestV1
     */
    userNotificationOptions?: PatchdeployerapiUserNotificationOptions;
}

/**
 * @export
 */
export const PatchdeployerapiDeploymentConfigUpdateRequestV1PlatformEnum = {
    Windows: "Windows",
} as const;
export type PatchdeployerapiDeploymentConfigUpdateRequestV1PlatformEnum =
    (typeof PatchdeployerapiDeploymentConfigUpdateRequestV1PlatformEnum)[keyof typeof PatchdeployerapiDeploymentConfigUpdateRequestV1PlatformEnum];

/**
 * Check if a given object implements the PatchdeployerapiDeploymentConfigUpdateRequestV1 interface.
 */
export function instanceOfPatchdeployerapiDeploymentConfigUpdateRequestV1(value: object): value is PatchdeployerapiDeploymentConfigUpdateRequestV1 {
    if (!("id" in value) || value["id"] === undefined) return false;
    return true;
}

export function PatchdeployerapiDeploymentConfigUpdateRequestV1FromJSON(json: any): PatchdeployerapiDeploymentConfigUpdateRequestV1 {
    return PatchdeployerapiDeploymentConfigUpdateRequestV1FromJSONTyped(json, false);
}

export function PatchdeployerapiDeploymentConfigUpdateRequestV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchdeployerapiDeploymentConfigUpdateRequestV1 {
    if (json == null) {
        return json;
    }
    return {
        blockFilterGroupIds: json["block_filter_group_ids"] == null ? undefined : json["block_filter_group_ids"],
        disabled: json["disabled"] == null ? undefined : json["disabled"],
        id: json["id"],
        name: json["name"] == null ? undefined : json["name"],
        patchFilterGroupIds: json["patch_filter_group_ids"] == null ? undefined : json["patch_filter_group_ids"],
        platform: json["platform"] == null ? undefined : json["platform"],
        postPatchScriptOptions: json["post_patch_script_options"] == null ? undefined : PatchdeployerapiPostPatchScriptOptionsPatchFromJSON(json["post_patch_script_options"]),
        prePatchScriptOptions: json["pre_patch_script_options"] == null ? undefined : PatchdeployerapiPrePatchScriptOptionsPatchFromJSON(json["pre_patch_script_options"]),
        prestage: json["prestage"] == null ? undefined : json["prestage"],
        rebootOptions: json["reboot_options"] == null ? undefined : PatchdeployerapiRebootOptionsFromJSON(json["reboot_options"]),
        recurring: json["recurring"] == null ? undefined : json["recurring"],
        runNowNoSchedule: json["run_now_no_schedule"] == null ? undefined : json["run_now_no_schedule"],
        schedule: json["schedule"] == null ? undefined : PatchdeployerapiDeploymentConfigScheduleFromJSON(json["schedule"]),
        targetHosts: json["target_hosts"] == null ? undefined : json["target_hosts"],
        targetPatches: json["target_patches"] == null ? undefined : json["target_patches"],
        userNotificationOptions: json["user_notification_options"] == null ? undefined : PatchdeployerapiUserNotificationOptionsFromJSON(json["user_notification_options"]),
    };
}

export function PatchdeployerapiDeploymentConfigUpdateRequestV1ToJSON(value?: PatchdeployerapiDeploymentConfigUpdateRequestV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        block_filter_group_ids: value["blockFilterGroupIds"],
        disabled: value["disabled"],
        id: value["id"],
        name: value["name"],
        patch_filter_group_ids: value["patchFilterGroupIds"],
        platform: value["platform"],
        post_patch_script_options: PatchdeployerapiPostPatchScriptOptionsPatchToJSON(value["postPatchScriptOptions"]),
        pre_patch_script_options: PatchdeployerapiPrePatchScriptOptionsPatchToJSON(value["prePatchScriptOptions"]),
        prestage: value["prestage"],
        reboot_options: PatchdeployerapiRebootOptionsToJSON(value["rebootOptions"]),
        recurring: value["recurring"],
        run_now_no_schedule: value["runNowNoSchedule"],
        schedule: PatchdeployerapiDeploymentConfigScheduleToJSON(value["schedule"]),
        target_hosts: value["targetHosts"],
        target_patches: value["targetPatches"],
        user_notification_options: PatchdeployerapiUserNotificationOptionsToJSON(value["userNotificationOptions"]),
    };
}
