/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { MsaAPIError } from "./MsaAPIError";
import { MsaAPIErrorFromJSON, MsaAPIErrorFromJSONTyped, MsaAPIErrorToJSON } from "./MsaAPIError";
import type { PatchmgmtOSAssessmentScan } from "./PatchmgmtOSAssessmentScan";
import { PatchmgmtOSAssessmentScanFromJSON, PatchmgmtOSAssessmentScanFromJSONTyped, PatchmgmtOSAssessmentScanToJSON } from "./PatchmgmtOSAssessmentScan";
import type { PatchmgmtCursorMetaInfo } from "./PatchmgmtCursorMetaInfo";
import { PatchmgmtCursorMetaInfoFromJSON, PatchmgmtCursorMetaInfoFromJSONTyped, PatchmgmtCursorMetaInfoToJSON } from "./PatchmgmtCursorMetaInfo";

/**
 *
 * @export
 * @interface PatchmgmtCombinedOSAssessmentScanResponse
 */
export interface PatchmgmtCombinedOSAssessmentScanResponse {
    /**
     *
     * @type {Array<MsaAPIError>}
     * @memberof PatchmgmtCombinedOSAssessmentScanResponse
     */
    errors?: Array<MsaAPIError>;
    /**
     *
     * @type {PatchmgmtCursorMetaInfo}
     * @memberof PatchmgmtCombinedOSAssessmentScanResponse
     */
    meta: PatchmgmtCursorMetaInfo;
    /**
     *
     * @type {Array<PatchmgmtOSAssessmentScan>}
     * @memberof PatchmgmtCombinedOSAssessmentScanResponse
     */
    resources: Array<PatchmgmtOSAssessmentScan>;
}

/**
 * Check if a given object implements the PatchmgmtCombinedOSAssessmentScanResponse interface.
 */
export function instanceOfPatchmgmtCombinedOSAssessmentScanResponse(value: object): value is PatchmgmtCombinedOSAssessmentScanResponse {
    if (!("meta" in value) || value["meta"] === undefined) return false;
    if (!("resources" in value) || value["resources"] === undefined) return false;
    return true;
}

export function PatchmgmtCombinedOSAssessmentScanResponseFromJSON(json: any): PatchmgmtCombinedOSAssessmentScanResponse {
    return PatchmgmtCombinedOSAssessmentScanResponseFromJSONTyped(json, false);
}

export function PatchmgmtCombinedOSAssessmentScanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchmgmtCombinedOSAssessmentScanResponse {
    if (json == null) {
        return json;
    }
    return {
        errors: json["errors"] == null ? undefined : (json["errors"] as Array<any>).map(MsaAPIErrorFromJSON),
        meta: PatchmgmtCursorMetaInfoFromJSON(json["meta"]),
        resources: (json["resources"] as Array<any>).map(PatchmgmtOSAssessmentScanFromJSON),
    };
}

export function PatchmgmtCombinedOSAssessmentScanResponseToJSON(value?: PatchmgmtCombinedOSAssessmentScanResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        errors: value["errors"] == null ? undefined : (value["errors"] as Array<any>).map(MsaAPIErrorToJSON),
        meta: PatchmgmtCursorMetaInfoToJSON(value["meta"]),
        resources: (value["resources"] as Array<any>).map(PatchmgmtOSAssessmentScanToJSON),
    };
}
