/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RestapiEmailAddress } from "./RestapiEmailAddress";
import { RestapiEmailAddressFromJSON, RestapiEmailAddressFromJSONTyped, RestapiEmailAddressToJSON } from "./RestapiEmailAddress";
import type { RestapiWhoIS } from "./RestapiWhoIS";
import { RestapiWhoISFromJSON, RestapiWhoISFromJSONTyped, RestapiWhoISToJSON } from "./RestapiWhoIS";
import type { RestapiMXRecord } from "./RestapiMXRecord";
import { RestapiMXRecordFromJSON, RestapiMXRecordFromJSONTyped, RestapiMXRecordToJSON } from "./RestapiMXRecord";
import type { RestapiIPv6 } from "./RestapiIPv6";
import { RestapiIPv6FromJSON, RestapiIPv6FromJSONTyped, RestapiIPv6ToJSON } from "./RestapiIPv6";
import type { RestapiIPv4 } from "./RestapiIPv4";
import { RestapiIPv4FromJSON, RestapiIPv4FromJSONTyped, RestapiIPv4ToJSON } from "./RestapiIPv4";
import type { RestapiNameServer } from "./RestapiNameServer";
import { RestapiNameServerFromJSON, RestapiNameServerFromJSONTyped, RestapiNameServerToJSON } from "./RestapiNameServer";

/**
 *
 * @export
 * @interface RestapiDomain
 */
export interface RestapiDomain {
    /**
     * Date the domain was registered
     * @type {string}
     * @memberof RestapiDomain
     */
    creationDate?: string;
    /**
     * The domain name
     * @type {string}
     * @memberof RestapiDomain
     */
    domain?: string;
    /**
     * Date the domain record was last updated by the source
     * @type {string}
     * @memberof RestapiDomain
     */
    domainUpdatedDate?: string;
    /**
     * Email addresses associated with the domain, by contact role
     * @type {Array<RestapiEmailAddress>}
     * @memberof RestapiDomain
     */
    emailAddresses?: Array<RestapiEmailAddress>;
    /**
     * Date the domain registration expires
     * @type {string}
     * @memberof RestapiDomain
     */
    expirationDate?: string;
    /**
     * HTTP response code returned when the domain was last crawled
     * @type {number}
     * @memberof RestapiDomain
     */
    hTTPStatus?: number;
    /**
     * Hosting providers (ISPs) of the IPv4 and IPv6 addresses the domain resolves to
     * @type {Array<string>}
     * @memberof RestapiDomain
     */
    hostingProvider?: Array<string>;
    /**
     * IPv4 addresses the domain resolves to, with ISP and ASN
     * @type {Array<RestapiIPv4>}
     * @memberof RestapiDomain
     */
    iPv4Addresses?: Array<RestapiIPv4>;
    /**
     * IPv6 addresses the domain resolves to, with ISP and ASN
     * @type {Array<RestapiIPv6>}
     * @memberof RestapiDomain
     */
    iPv6Addresses?: Array<RestapiIPv6>;
    /**
     * Mail exchange records for the domain
     * @type {Array<RestapiMXRecord>}
     * @memberof RestapiDomain
     */
    mXRecords?: Array<RestapiMXRecord>;
    /**
     * Name servers the domain resolves through
     * @type {Array<RestapiNameServer>}
     * @memberof RestapiDomain
     */
    nameServers?: Array<RestapiNameServer>;
    /**
     * HTML title of the page returned when the domain was last crawled
     * @type {string}
     * @memberof RestapiDomain
     */
    pageTitle?: string;
    /**
     * Popularity rank of the domain; only populated for a small subset of domains
     * @type {number}
     * @memberof RestapiDomain
     */
    popularityRank?: number;
    /**
     * Registered domain of the redirect destination
     * @type {string}
     * @memberof RestapiDomain
     */
    redirectDomain?: string;
    /**
     * Redirect destination: usually a hostname, sometimes a bare IP, rarely a full URL
     * @type {string}
     * @memberof RestapiDomain
     */
    redirectTarget?: string;
    /**
     * Registrar that the domain is registered with
     * @type {string}
     * @memberof RestapiDomain
     */
    registrar?: string;
    /**
     * EPP status codes reported by the registrar
     * @type {Array<string>}
     * @memberof RestapiDomain
     */
    registrarStatus?: Array<string>;
    /**
     * Categorical domain risk: NO_THREAT_LIKELY, LOW, MEDIUM, HIGH or CONFIRMED_THREAT
     * @type {string}
     * @memberof RestapiDomain
     */
    riskScore?: string;
    /**
     * Top-level domain
     * @type {string}
     * @memberof RestapiDomain
     */
    tLD?: string;
    /**
     *
     * @type {RestapiWhoIS}
     * @memberof RestapiDomain
     */
    whoIS?: RestapiWhoIS;
}

/**
 * Check if a given object implements the RestapiDomain interface.
 */
export function instanceOfRestapiDomain(value: object): value is RestapiDomain {
    return true;
}

export function RestapiDomainFromJSON(json: any): RestapiDomain {
    return RestapiDomainFromJSONTyped(json, false);
}

export function RestapiDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestapiDomain {
    if (json == null) {
        return json;
    }
    return {
        creationDate: json["CreationDate"] == null ? undefined : json["CreationDate"],
        domain: json["Domain"] == null ? undefined : json["Domain"],
        domainUpdatedDate: json["DomainUpdatedDate"] == null ? undefined : json["DomainUpdatedDate"],
        emailAddresses: json["EmailAddresses"] == null ? undefined : (json["EmailAddresses"] as Array<any>).map(RestapiEmailAddressFromJSON),
        expirationDate: json["ExpirationDate"] == null ? undefined : json["ExpirationDate"],
        hTTPStatus: json["HTTPStatus"] == null ? undefined : json["HTTPStatus"],
        hostingProvider: json["HostingProvider"] == null ? undefined : json["HostingProvider"],
        iPv4Addresses: json["IPv4Addresses"] == null ? undefined : (json["IPv4Addresses"] as Array<any>).map(RestapiIPv4FromJSON),
        iPv6Addresses: json["IPv6Addresses"] == null ? undefined : (json["IPv6Addresses"] as Array<any>).map(RestapiIPv6FromJSON),
        mXRecords: json["MXRecords"] == null ? undefined : (json["MXRecords"] as Array<any>).map(RestapiMXRecordFromJSON),
        nameServers: json["NameServers"] == null ? undefined : (json["NameServers"] as Array<any>).map(RestapiNameServerFromJSON),
        pageTitle: json["PageTitle"] == null ? undefined : json["PageTitle"],
        popularityRank: json["PopularityRank"] == null ? undefined : json["PopularityRank"],
        redirectDomain: json["RedirectDomain"] == null ? undefined : json["RedirectDomain"],
        redirectTarget: json["RedirectTarget"] == null ? undefined : json["RedirectTarget"],
        registrar: json["Registrar"] == null ? undefined : json["Registrar"],
        registrarStatus: json["RegistrarStatus"] == null ? undefined : json["RegistrarStatus"],
        riskScore: json["RiskScore"] == null ? undefined : json["RiskScore"],
        tLD: json["TLD"] == null ? undefined : json["TLD"],
        whoIS: json["WhoIS"] == null ? undefined : RestapiWhoISFromJSON(json["WhoIS"]),
    };
}

export function RestapiDomainToJSON(value?: RestapiDomain | null): any {
    if (value == null) {
        return value;
    }
    return {
        CreationDate: value["creationDate"],
        Domain: value["domain"],
        DomainUpdatedDate: value["domainUpdatedDate"],
        EmailAddresses: value["emailAddresses"] == null ? undefined : (value["emailAddresses"] as Array<any>).map(RestapiEmailAddressToJSON),
        ExpirationDate: value["expirationDate"],
        HTTPStatus: value["hTTPStatus"],
        HostingProvider: value["hostingProvider"],
        IPv4Addresses: value["iPv4Addresses"] == null ? undefined : (value["iPv4Addresses"] as Array<any>).map(RestapiIPv4ToJSON),
        IPv6Addresses: value["iPv6Addresses"] == null ? undefined : (value["iPv6Addresses"] as Array<any>).map(RestapiIPv6ToJSON),
        MXRecords: value["mXRecords"] == null ? undefined : (value["mXRecords"] as Array<any>).map(RestapiMXRecordToJSON),
        NameServers: value["nameServers"] == null ? undefined : (value["nameServers"] as Array<any>).map(RestapiNameServerToJSON),
        PageTitle: value["pageTitle"],
        PopularityRank: value["popularityRank"],
        RedirectDomain: value["redirectDomain"],
        RedirectTarget: value["redirectTarget"],
        Registrar: value["registrar"],
        RegistrarStatus: value["registrarStatus"],
        RiskScore: value["riskScore"],
        TLD: value["tLD"],
        WhoIS: RestapiWhoISToJSON(value["whoIS"]),
    };
}
