/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RestapiDomain } from "./RestapiDomain";
import { RestapiDomainFromJSON, RestapiDomainFromJSONTyped, RestapiDomainToJSON } from "./RestapiDomain";
import type { RestapiMITREAttack } from "./RestapiMITREAttack";
import { RestapiMITREAttackFromJSON, RestapiMITREAttackFromJSONTyped, RestapiMITREAttackToJSON } from "./RestapiMITREAttack";
import type { RestapiEmailAddressDetails } from "./RestapiEmailAddressDetails";
import { RestapiEmailAddressDetailsFromJSON, RestapiEmailAddressDetailsFromJSONTyped, RestapiEmailAddressDetailsToJSON } from "./RestapiEmailAddressDetails";
import type { RestapiFile } from "./RestapiFile";
import { RestapiFileFromJSON, RestapiFileFromJSONTyped, RestapiFileToJSON } from "./RestapiFile";
import type { RestapiURL } from "./RestapiURL";
import { RestapiURLFromJSON, RestapiURLFromJSONTyped, RestapiURLToJSON } from "./RestapiURL";
import type { RestapiUniqueIdentifier } from "./RestapiUniqueIdentifier";
import { RestapiUniqueIdentifierFromJSON, RestapiUniqueIdentifierFromJSONTyped, RestapiUniqueIdentifierToJSON } from "./RestapiUniqueIdentifier";
import type { RestapiCountry } from "./RestapiCountry";
import { RestapiCountryFromJSON, RestapiCountryFromJSONTyped, RestapiCountryToJSON } from "./RestapiCountry";
import type { RestapiX509Certificate } from "./RestapiX509Certificate";
import { RestapiX509CertificateFromJSON, RestapiX509CertificateFromJSONTyped, RestapiX509CertificateToJSON } from "./RestapiX509Certificate";
import type { RestapiIPv6 } from "./RestapiIPv6";
import { RestapiIPv6FromJSON, RestapiIPv6FromJSONTyped, RestapiIPv6ToJSON } from "./RestapiIPv6";
import type { RestapiIPv4 } from "./RestapiIPv4";
import { RestapiIPv4FromJSON, RestapiIPv4FromJSONTyped, RestapiIPv4ToJSON } from "./RestapiIPv4";
import type { RestapiSoftwarePackage } from "./RestapiSoftwarePackage";
import { RestapiSoftwarePackageFromJSON, RestapiSoftwarePackageFromJSONTyped, RestapiSoftwarePackageToJSON } from "./RestapiSoftwarePackage";
import type { RestapiThreat } from "./RestapiThreat";
import { RestapiThreatFromJSON, RestapiThreatFromJSONTyped, RestapiThreatToJSON } from "./RestapiThreat";
import type { RestapiVulnerability } from "./RestapiVulnerability";
import { RestapiVulnerabilityFromJSON, RestapiVulnerabilityFromJSONTyped, RestapiVulnerabilityToJSON } from "./RestapiVulnerability";
import type { RestapiReport } from "./RestapiReport";
import { RestapiReportFromJSON, RestapiReportFromJSONTyped, RestapiReportToJSON } from "./RestapiReport";
import type { RestapiCredentials } from "./RestapiCredentials";
import { RestapiCredentialsFromJSON, RestapiCredentialsFromJSONTyped, RestapiCredentialsToJSON } from "./RestapiCredentials";
import type { RestapiAdversary } from "./RestapiAdversary";
import { RestapiAdversaryFromJSON, RestapiAdversaryFromJSONTyped, RestapiAdversaryToJSON } from "./RestapiAdversary";
import type { RestapiCoinAddress } from "./RestapiCoinAddress";
import { RestapiCoinAddressFromJSON, RestapiCoinAddressFromJSONTyped, RestapiCoinAddressToJSON } from "./RestapiCoinAddress";
import type { RestapiSector } from "./RestapiSector";
import { RestapiSectorFromJSON, RestapiSectorFromJSONTyped, RestapiSectorToJSON } from "./RestapiSector";

/**
 *
 * @export
 * @interface RestapiIndicator
 */
export interface RestapiIndicator {
    /**
     *
     * @type {Array<RestapiAdversary>}
     * @memberof RestapiIndicator
     */
    adversaries?: Array<RestapiAdversary>;
    /**
     * Total range of customers affected by this indicator
     * @type {string}
     * @memberof RestapiIndicator
     */
    affectedCustomers?: string;
    /**
     *
     * @type {Array<RestapiX509Certificate>}
     * @memberof RestapiIndicator
     */
    certificates?: Array<RestapiX509Certificate>;
    /**
     * Automated assessment of the indicator, one of: `Clean`, `LikelyBenign`, `Suspicious`, `Malicious`, `Unknown`. Derived from the available observations and NOT human reviewed, so it is a triage aid rather than a verdict: for files from the file reputation tags and `MaliciousConfidence`, for IP addresses from the honeypot observations under `IPv4Details.HoneypotIntelligence` and `MaliciousConfidence`, and for every other type from `MaliciousConfidence` alone. Absent when no source contributed to the indicator.
     * @type {string}
     * @memberof RestapiIndicator
     */
    classification?: string;
    /**
     *
     * @type {RestapiCoinAddress}
     * @memberof RestapiIndicator
     */
    coinAddressDetails?: RestapiCoinAddress;
    /**
     *
     * @type {Array<RestapiCountry>}
     * @memberof RestapiIndicator
     */
    countries?: Array<RestapiCountry>;
    /**
     *
     * @type {RestapiCredentials}
     * @memberof RestapiIndicator
     */
    credentialsDetails?: RestapiCredentials;
    /**
     *
     * @type {RestapiDomain}
     * @memberof RestapiIndicator
     */
    domainDetails?: RestapiDomain;
    /**
     *
     * @type {RestapiEmailAddressDetails}
     * @memberof RestapiIndicator
     */
    emailAddressDetails?: RestapiEmailAddressDetails;
    /**
     *
     * @type {RestapiFile}
     * @memberof RestapiIndicator
     */
    fileDetails?: RestapiFile;
    /**
     * Indicators first seen
     * @type {string}
     * @memberof RestapiIndicator
     */
    firstSeen?: string;
    /**
     * The indicator ID. Concatenation of type and indicator fields. Based on the CKB2 vertex ID.
     * @type {string}
     * @memberof RestapiIndicator
     */
    iD?: string;
    /**
     *
     * @type {RestapiIPv4}
     * @memberof RestapiIndicator
     */
    iPv4Details?: RestapiIPv4;
    /**
     *
     * @type {RestapiIPv6}
     * @memberof RestapiIndicator
     */
    iPv6Details?: RestapiIPv6;
    /**
     * Multi field property describing indicators kill-chain, possible properties: `ActionOnObjectives`, `C2`, `Delivery`, `Exploitation`, `Installation`, `Reconnaissance`, `Weaponization`
     * @type {Array<string>}
     * @memberof RestapiIndicator
     */
    killChain?: Array<string>;
    /**
     * Indicators last seen
     * @type {string}
     * @memberof RestapiIndicator
     */
    lastSeen?: string;
    /**
     *
     * @type {string}
     * @memberof RestapiIndicator
     */
    lastUpdated?: string;
    /**
     *
     * @type {Array<RestapiMITREAttack>}
     * @memberof RestapiIndicator
     */
    mITREAttacks?: Array<RestapiMITREAttack>;
    /**
     * Indicates a confidence level by which an indicator is considered to be malicious, this can be one of: `Low`, `Medium`, `High`
     * @type {string}
     * @memberof RestapiIndicator
     */
    maliciousConfidence?: string;
    /**
     * Indicates when was the confidence was last set
     * @type {string}
     * @memberof RestapiIndicator
     */
    maliciousConfidenceValidatedTime?: string;
    /**
     *
     * @type {string}
     * @memberof RestapiIndicator
     */
    publishDate?: string;
    /**
     *
     * @type {Array<RestapiReport>}
     * @memberof RestapiIndicator
     */
    reports?: Array<RestapiReport>;
    /**
     *
     * @type {RestapiDomain}
     * @memberof RestapiIndicator
     */
    rootDomainDetails?: RestapiDomain;
    /**
     *
     * @type {Array<RestapiSector>}
     * @memberof RestapiIndicator
     */
    sectors?: Array<RestapiSector>;
    /**
     *
     * @type {Array<RestapiSoftwarePackage>}
     * @memberof RestapiIndicator
     */
    softwarePackages?: Array<RestapiSoftwarePackage>;
    /**
     *
     * @type {Array<string>}
     * @memberof RestapiIndicator
     */
    threatTypes?: Array<string>;
    /**
     *
     * @type {Array<RestapiThreat>}
     * @memberof RestapiIndicator
     */
    threats?: Array<RestapiThreat>;
    /**
     * Type of the indicator, this can be one of: `File`, `Domain`, `IPv4`, `IPv6`, `URL`
     * @type {string}
     * @memberof RestapiIndicator
     */
    type?: string;
    /**
     *
     * @type {RestapiURL}
     * @memberof RestapiIndicator
     */
    uRLDetails?: RestapiURL;
    /**
     *
     * @type {RestapiUniqueIdentifier}
     * @memberof RestapiIndicator
     */
    uniqueIdentifierDetails?: RestapiUniqueIdentifier;
    /**
     *
     * @type {Array<RestapiVulnerability>}
     * @memberof RestapiIndicator
     */
    vulnerabilities?: Array<RestapiVulnerability>;
}

/**
 * Check if a given object implements the RestapiIndicator interface.
 */
export function instanceOfRestapiIndicator(value: object): value is RestapiIndicator {
    return true;
}

export function RestapiIndicatorFromJSON(json: any): RestapiIndicator {
    return RestapiIndicatorFromJSONTyped(json, false);
}

export function RestapiIndicatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestapiIndicator {
    if (json == null) {
        return json;
    }
    return {
        adversaries: json["Adversaries"] == null ? undefined : (json["Adversaries"] as Array<any>).map(RestapiAdversaryFromJSON),
        affectedCustomers: json["AffectedCustomers"] == null ? undefined : json["AffectedCustomers"],
        certificates: json["Certificates"] == null ? undefined : (json["Certificates"] as Array<any>).map(RestapiX509CertificateFromJSON),
        classification: json["Classification"] == null ? undefined : json["Classification"],
        coinAddressDetails: json["CoinAddressDetails"] == null ? undefined : RestapiCoinAddressFromJSON(json["CoinAddressDetails"]),
        countries: json["Countries"] == null ? undefined : (json["Countries"] as Array<any>).map(RestapiCountryFromJSON),
        credentialsDetails: json["CredentialsDetails"] == null ? undefined : RestapiCredentialsFromJSON(json["CredentialsDetails"]),
        domainDetails: json["DomainDetails"] == null ? undefined : RestapiDomainFromJSON(json["DomainDetails"]),
        emailAddressDetails: json["EmailAddressDetails"] == null ? undefined : RestapiEmailAddressDetailsFromJSON(json["EmailAddressDetails"]),
        fileDetails: json["FileDetails"] == null ? undefined : RestapiFileFromJSON(json["FileDetails"]),
        firstSeen: json["FirstSeen"] == null ? undefined : json["FirstSeen"],
        iD: json["ID"] == null ? undefined : json["ID"],
        iPv4Details: json["IPv4Details"] == null ? undefined : RestapiIPv4FromJSON(json["IPv4Details"]),
        iPv6Details: json["IPv6Details"] == null ? undefined : RestapiIPv6FromJSON(json["IPv6Details"]),
        killChain: json["KillChain"] == null ? undefined : json["KillChain"],
        lastSeen: json["LastSeen"] == null ? undefined : json["LastSeen"],
        lastUpdated: json["LastUpdated"] == null ? undefined : json["LastUpdated"],
        mITREAttacks: json["MITREAttacks"] == null ? undefined : (json["MITREAttacks"] as Array<any>).map(RestapiMITREAttackFromJSON),
        maliciousConfidence: json["MaliciousConfidence"] == null ? undefined : json["MaliciousConfidence"],
        maliciousConfidenceValidatedTime: json["MaliciousConfidenceValidatedTime"] == null ? undefined : json["MaliciousConfidenceValidatedTime"],
        publishDate: json["PublishDate"] == null ? undefined : json["PublishDate"],
        reports: json["Reports"] == null ? undefined : (json["Reports"] as Array<any>).map(RestapiReportFromJSON),
        rootDomainDetails: json["RootDomainDetails"] == null ? undefined : RestapiDomainFromJSON(json["RootDomainDetails"]),
        sectors: json["Sectors"] == null ? undefined : (json["Sectors"] as Array<any>).map(RestapiSectorFromJSON),
        softwarePackages: json["SoftwarePackages"] == null ? undefined : (json["SoftwarePackages"] as Array<any>).map(RestapiSoftwarePackageFromJSON),
        threatTypes: json["ThreatTypes"] == null ? undefined : json["ThreatTypes"],
        threats: json["Threats"] == null ? undefined : (json["Threats"] as Array<any>).map(RestapiThreatFromJSON),
        type: json["Type"] == null ? undefined : json["Type"],
        uRLDetails: json["URLDetails"] == null ? undefined : RestapiURLFromJSON(json["URLDetails"]),
        uniqueIdentifierDetails: json["UniqueIdentifierDetails"] == null ? undefined : RestapiUniqueIdentifierFromJSON(json["UniqueIdentifierDetails"]),
        vulnerabilities: json["Vulnerabilities"] == null ? undefined : (json["Vulnerabilities"] as Array<any>).map(RestapiVulnerabilityFromJSON),
    };
}

export function RestapiIndicatorToJSON(value?: RestapiIndicator | null): any {
    if (value == null) {
        return value;
    }
    return {
        Adversaries: value["adversaries"] == null ? undefined : (value["adversaries"] as Array<any>).map(RestapiAdversaryToJSON),
        AffectedCustomers: value["affectedCustomers"],
        Certificates: value["certificates"] == null ? undefined : (value["certificates"] as Array<any>).map(RestapiX509CertificateToJSON),
        Classification: value["classification"],
        CoinAddressDetails: RestapiCoinAddressToJSON(value["coinAddressDetails"]),
        Countries: value["countries"] == null ? undefined : (value["countries"] as Array<any>).map(RestapiCountryToJSON),
        CredentialsDetails: RestapiCredentialsToJSON(value["credentialsDetails"]),
        DomainDetails: RestapiDomainToJSON(value["domainDetails"]),
        EmailAddressDetails: RestapiEmailAddressDetailsToJSON(value["emailAddressDetails"]),
        FileDetails: RestapiFileToJSON(value["fileDetails"]),
        FirstSeen: value["firstSeen"],
        ID: value["iD"],
        IPv4Details: RestapiIPv4ToJSON(value["iPv4Details"]),
        IPv6Details: RestapiIPv6ToJSON(value["iPv6Details"]),
        KillChain: value["killChain"],
        LastSeen: value["lastSeen"],
        LastUpdated: value["lastUpdated"],
        MITREAttacks: value["mITREAttacks"] == null ? undefined : (value["mITREAttacks"] as Array<any>).map(RestapiMITREAttackToJSON),
        MaliciousConfidence: value["maliciousConfidence"],
        MaliciousConfidenceValidatedTime: value["maliciousConfidenceValidatedTime"],
        PublishDate: value["publishDate"],
        Reports: value["reports"] == null ? undefined : (value["reports"] as Array<any>).map(RestapiReportToJSON),
        RootDomainDetails: RestapiDomainToJSON(value["rootDomainDetails"]),
        Sectors: value["sectors"] == null ? undefined : (value["sectors"] as Array<any>).map(RestapiSectorToJSON),
        SoftwarePackages: value["softwarePackages"] == null ? undefined : (value["softwarePackages"] as Array<any>).map(RestapiSoftwarePackageToJSON),
        ThreatTypes: value["threatTypes"],
        Threats: value["threats"] == null ? undefined : (value["threats"] as Array<any>).map(RestapiThreatToJSON),
        Type: value["type"],
        URLDetails: RestapiURLToJSON(value["uRLDetails"]),
        UniqueIdentifierDetails: RestapiUniqueIdentifierToJSON(value["uniqueIdentifierDetails"]),
        Vulnerabilities: value["vulnerabilities"] == null ? undefined : (value["vulnerabilities"] as Array<any>).map(RestapiVulnerabilityToJSON),
    };
}
