/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RouteCreateQueryJobRequest
 */
export interface RouteCreateQueryJobRequest {
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    action?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    actionDescription?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    actorId?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    actorIp?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    actorType?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    category?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    categoryDescription?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    cid?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof RouteCreateQueryJobRequest
     */
    endTime: string;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    eventId?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    eventVersion?: Array<string>;
    /**
     *
     * @type {{ [key: string]: Array<string>; }}
     * @memberof RouteCreateQueryJobRequest
     */
    extensions?: { [key: string]: Array<string> };
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    geoCity?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    geoCountry?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof RouteCreateQueryJobRequest
     */
    sort?: string;
    /**
     *
     * @type {string}
     * @memberof RouteCreateQueryJobRequest
     */
    startTime: string;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    targetDisplayName?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    targetId?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    targetType?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof RouteCreateQueryJobRequest
     */
    userAgent?: Array<string>;
}

/**
 * Check if a given object implements the RouteCreateQueryJobRequest interface.
 */
export function instanceOfRouteCreateQueryJobRequest(value: object): value is RouteCreateQueryJobRequest {
    if (!("endTime" in value) || value["endTime"] === undefined) return false;
    if (!("startTime" in value) || value["startTime"] === undefined) return false;
    return true;
}

export function RouteCreateQueryJobRequestFromJSON(json: any): RouteCreateQueryJobRequest {
    return RouteCreateQueryJobRequestFromJSONTyped(json, false);
}

export function RouteCreateQueryJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteCreateQueryJobRequest {
    if (json == null) {
        return json;
    }
    return {
        action: json["action"] == null ? undefined : json["action"],
        actionDescription: json["action_description"] == null ? undefined : json["action_description"],
        actorId: json["actor_id"] == null ? undefined : json["actor_id"],
        actorIp: json["actor_ip"] == null ? undefined : json["actor_ip"],
        actorType: json["actor_type"] == null ? undefined : json["actor_type"],
        category: json["category"] == null ? undefined : json["category"],
        categoryDescription: json["category_description"] == null ? undefined : json["category_description"],
        cid: json["cid"] == null ? undefined : json["cid"],
        endTime: json["end_time"],
        eventId: json["event_id"] == null ? undefined : json["event_id"],
        eventVersion: json["event_version"] == null ? undefined : json["event_version"],
        extensions: json["extensions"] == null ? undefined : json["extensions"],
        geoCity: json["geo_city"] == null ? undefined : json["geo_city"],
        geoCountry: json["geo_country"] == null ? undefined : json["geo_country"],
        sort: json["sort"] == null ? undefined : json["sort"],
        startTime: json["start_time"],
        targetDisplayName: json["target_display_name"] == null ? undefined : json["target_display_name"],
        targetId: json["target_id"] == null ? undefined : json["target_id"],
        targetType: json["target_type"] == null ? undefined : json["target_type"],
        userAgent: json["user_agent"] == null ? undefined : json["user_agent"],
    };
}

export function RouteCreateQueryJobRequestToJSON(value?: RouteCreateQueryJobRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        action: value["action"],
        action_description: value["actionDescription"],
        actor_id: value["actorId"],
        actor_ip: value["actorIp"],
        actor_type: value["actorType"],
        category: value["category"],
        category_description: value["categoryDescription"],
        cid: value["cid"],
        end_time: value["endTime"],
        event_id: value["eventId"],
        event_version: value["eventVersion"],
        extensions: value["extensions"],
        geo_city: value["geoCity"],
        geo_country: value["geoCountry"],
        sort: value["sort"],
        start_time: value["startTime"],
        target_display_name: value["targetDisplayName"],
        target_id: value["targetId"],
        target_type: value["targetType"],
        user_agent: value["userAgent"],
    };
}
