/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RuleCondition
 */
export interface RuleCondition {
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    alertType?: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    buttonText?: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    createdAt?: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    createdBy?: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    description?: string;
    /**
     *
     * @type {boolean}
     * @memberof RuleCondition
     */
    enabled?: boolean;
    /**
     *
     * @type {number}
     * @memberof RuleCondition
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    inputDescription: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    inputType: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    message?: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    messageTitle?: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    name: string;
    /**
     *
     * @type {boolean}
     * @memberof RuleCondition
     */
    notificationEnabled?: boolean;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    notificationText?: string;
    /**
     *
     * @type {number}
     * @memberof RuleCondition
     */
    ruleOptionId?: number;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    selectedOption?: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    updatedAt?: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    updatedBy?: string;
    /**
     *
     * @type {string}
     * @memberof RuleCondition
     */
    value?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof RuleCondition
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the RuleCondition interface.
 */
export function instanceOfRuleCondition(value: object): value is RuleCondition {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("inputDescription" in value) || value["inputDescription"] === undefined) return false;
    if (!("inputType" in value) || value["inputType"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function RuleConditionFromJSON(json: any): RuleCondition {
    return RuleConditionFromJSONTyped(json, false);
}

export function RuleConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleCondition {
    if (json == null) {
        return json;
    }
    return {
        alertType: json["alertType"] == null ? undefined : json["alertType"],
        buttonText: json["buttonText"] == null ? undefined : json["buttonText"],
        createdAt: json["createdAt"] == null ? undefined : json["createdAt"],
        createdBy: json["createdBy"] == null ? undefined : json["createdBy"],
        description: json["description"] == null ? undefined : json["description"],
        enabled: json["enabled"] == null ? undefined : json["enabled"],
        id: json["id"],
        inputDescription: json["input_description"],
        inputType: json["input_type"],
        message: json["message"] == null ? undefined : json["message"],
        messageTitle: json["message_title"] == null ? undefined : json["message_title"],
        name: json["name"],
        notificationEnabled: json["notification_enabled"] == null ? undefined : json["notification_enabled"],
        notificationText: json["notification_text"] == null ? undefined : json["notification_text"],
        ruleOptionId: json["ruleOptionId"] == null ? undefined : json["ruleOptionId"],
        selectedOption: json["selected_option"] == null ? undefined : json["selected_option"],
        updatedAt: json["updatedAt"] == null ? undefined : json["updatedAt"],
        updatedBy: json["updatedBy"] == null ? undefined : json["updatedBy"],
        value: json["value"] == null ? undefined : json["value"],
        values: json["values"] == null ? undefined : json["values"],
    };
}

export function RuleConditionToJSON(value?: RuleCondition | null): any {
    if (value == null) {
        return value;
    }
    return {
        alertType: value["alertType"],
        buttonText: value["buttonText"],
        createdAt: value["createdAt"],
        createdBy: value["createdBy"],
        description: value["description"],
        enabled: value["enabled"],
        id: value["id"],
        input_description: value["inputDescription"],
        input_type: value["inputType"],
        message: value["message"],
        message_title: value["messageTitle"],
        name: value["name"],
        notification_enabled: value["notificationEnabled"],
        notification_text: value["notificationText"],
        ruleOptionId: value["ruleOptionId"],
        selected_option: value["selectedOption"],
        updatedAt: value["updatedAt"],
        updatedBy: value["updatedBy"],
        value: value["value"],
        values: value["values"],
    };
}
