/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SadomainURLScan
 */
export interface SadomainURLScan {
    /**
     * The timestamp when the scan was captured
     * @type {Date}
     * @memberof SadomainURLScan
     */
    capturedAt: Date;
    /**
     * The ID of the URL scan that captured the url state when the notification was created
     * @type {string}
     * @memberof SadomainURLScan
     */
    scanId: string;
}

/**
 * Check if a given object implements the SadomainURLScan interface.
 */
export function instanceOfSadomainURLScan(value: object): value is SadomainURLScan {
    if (!("capturedAt" in value) || value["capturedAt"] === undefined) return false;
    if (!("scanId" in value) || value["scanId"] === undefined) return false;
    return true;
}

export function SadomainURLScanFromJSON(json: any): SadomainURLScan {
    return SadomainURLScanFromJSONTyped(json, false);
}

export function SadomainURLScanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SadomainURLScan {
    if (json == null) {
        return json;
    }
    return {
        capturedAt: new Date(json["captured_at"]),
        scanId: json["scan_id"],
    };
}

export function SadomainURLScanToJSON(value?: SadomainURLScan | null): any {
    if (value == null) {
        return value;
    }
    return {
        captured_at: value["capturedAt"].toISOString(),
        scan_id: value["scanId"],
    };
}
