/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SdkHostGroupEvidence } from "./SdkHostGroupEvidence";
import { SdkHostGroupEvidenceFromJSON, SdkHostGroupEvidenceFromJSONTyped, SdkHostGroupEvidenceToJSON } from "./SdkHostGroupEvidence";

/**
 *
 * @export
 * @interface SdkHostGroupEvidenceRecordVM
 */
export interface SdkHostGroupEvidenceRecordVM {
    /**
     *
     * @type {string}
     * @memberof SdkHostGroupEvidenceRecordVM
     */
    caseId: string;
    /**
     *
     * @type {string}
     * @memberof SdkHostGroupEvidenceRecordVM
     */
    id: string;
    /**
     *
     * @type {SdkHostGroupEvidence}
     * @memberof SdkHostGroupEvidenceRecordVM
     */
    value: SdkHostGroupEvidence;
}

/**
 * Check if a given object implements the SdkHostGroupEvidenceRecordVM interface.
 */
export function instanceOfSdkHostGroupEvidenceRecordVM(value: object): value is SdkHostGroupEvidenceRecordVM {
    if (!("caseId" in value) || value["caseId"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("value" in value) || value["value"] === undefined) return false;
    return true;
}

export function SdkHostGroupEvidenceRecordVMFromJSON(json: any): SdkHostGroupEvidenceRecordVM {
    return SdkHostGroupEvidenceRecordVMFromJSONTyped(json, false);
}

export function SdkHostGroupEvidenceRecordVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): SdkHostGroupEvidenceRecordVM {
    if (json == null) {
        return json;
    }
    return {
        caseId: json["case_id"],
        id: json["id"],
        value: SdkHostGroupEvidenceFromJSON(json["value"]),
    };
}

export function SdkHostGroupEvidenceRecordVMToJSON(value?: SdkHostGroupEvidenceRecordVM | null): any {
    if (value == null) {
        return value;
    }
    return {
        case_id: value["caseId"],
        id: value["id"],
        value: SdkHostGroupEvidenceToJSON(value["value"]),
    };
}
