/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SensitiveDataPredefinedPII
 */
export interface SensitiveDataPredefinedPII {
    /**
     * Name of the predefined PII detector.
     * @type {string}
     * @memberof SensitiveDataPredefinedPII
     */
    predefinedPii: string;
    /**
     * Minimum number of occurrences. Minimum 1.
     * @type {number}
     * @memberof SensitiveDataPredefinedPII
     */
    threshold: number;
}

/**
 * Check if a given object implements the SensitiveDataPredefinedPII interface.
 */
export function instanceOfSensitiveDataPredefinedPII(value: object): value is SensitiveDataPredefinedPII {
    if (!("predefinedPii" in value) || value["predefinedPii"] === undefined) return false;
    if (!("threshold" in value) || value["threshold"] === undefined) return false;
    return true;
}

export function SensitiveDataPredefinedPIIFromJSON(json: any): SensitiveDataPredefinedPII {
    return SensitiveDataPredefinedPIIFromJSONTyped(json, false);
}

export function SensitiveDataPredefinedPIIFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensitiveDataPredefinedPII {
    if (json == null) {
        return json;
    }
    return {
        predefinedPii: json["predefined_pii"],
        threshold: json["threshold"],
    };
}

export function SensitiveDataPredefinedPIIToJSON(value?: SensitiveDataPredefinedPII | null): any {
    if (value == null) {
        return value;
    }
    return {
        predefined_pii: value["predefinedPii"],
        threshold: value["threshold"],
    };
}
