/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CheckParam } from "./CheckParam";
import { CheckParamFromJSON, CheckParamFromJSONTyped, CheckParamToJSON } from "./CheckParam";
import type { ErrorSetCheckParam } from "./ErrorSetCheckParam";
import { ErrorSetCheckParamFromJSON, ErrorSetCheckParamFromJSONTyped, ErrorSetCheckParamToJSON } from "./ErrorSetCheckParam";
import type { MetaSetCheckParam } from "./MetaSetCheckParam";
import { MetaSetCheckParamFromJSON, MetaSetCheckParamFromJSONTyped, MetaSetCheckParamToJSON } from "./MetaSetCheckParam";

/**
 *
 * @export
 * @interface SetCheckParam
 */
export interface SetCheckParam {
    /**
     *
     * @type {Array<ErrorSetCheckParam>}
     * @memberof SetCheckParam
     */
    errors?: Array<ErrorSetCheckParam>;
    /**
     *
     * @type {MetaSetCheckParam}
     * @memberof SetCheckParam
     */
    meta?: MetaSetCheckParam | null;
    /**
     *
     * @type {Array<CheckParam>}
     * @memberof SetCheckParam
     */
    resources: Array<CheckParam>;
}

/**
 * Check if a given object implements the SetCheckParam interface.
 */
export function instanceOfSetCheckParam(value: object): value is SetCheckParam {
    if (!("resources" in value) || value["resources"] === undefined) return false;
    return true;
}

export function SetCheckParamFromJSON(json: any): SetCheckParam {
    return SetCheckParamFromJSONTyped(json, false);
}

export function SetCheckParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCheckParam {
    if (json == null) {
        return json;
    }
    return {
        errors: json["errors"] == null ? undefined : (json["errors"] as Array<any>).map(ErrorSetCheckParamFromJSON),
        meta: json["meta"] == null ? undefined : MetaSetCheckParamFromJSON(json["meta"]),
        resources: (json["resources"] as Array<any>).map(CheckParamFromJSON),
    };
}

export function SetCheckParamToJSON(value?: SetCheckParam | null): any {
    if (value == null) {
        return value;
    }
    return {
        errors: value["errors"] == null ? undefined : (value["errors"] as Array<any>).map(ErrorSetCheckParamToJSON),
        meta: MetaSetCheckParamToJSON(value["meta"]),
        resources: (value["resources"] as Array<any>).map(CheckParamToJSON),
    };
}
