/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SetCheckImpactV3Request
 */
export interface SetCheckImpactV3Request {
    /**
     * Also apply this impact to future instances of the same SaaS
     * @type {boolean}
     * @memberof SetCheckImpactV3Request
     */
    allFutureInstances?: boolean;
    /**
     * The new impact
     * @type {string}
     * @memberof SetCheckImpactV3Request
     */
    impact: SetCheckImpactV3RequestImpactEnum;
    /**
     * Why the impact was changed. Recorded on the check's timeline
     * @type {string}
     * @memberof SetCheckImpactV3Request
     */
    reason?: string;
}

/**
 * @export
 */
export const SetCheckImpactV3RequestImpactEnum = {
    Low: "Low",
    Medium: "Medium",
    High: "High",
} as const;
export type SetCheckImpactV3RequestImpactEnum = (typeof SetCheckImpactV3RequestImpactEnum)[keyof typeof SetCheckImpactV3RequestImpactEnum];

/**
 * Check if a given object implements the SetCheckImpactV3Request interface.
 */
export function instanceOfSetCheckImpactV3Request(value: object): value is SetCheckImpactV3Request {
    if (!("impact" in value) || value["impact"] === undefined) return false;
    return true;
}

export function SetCheckImpactV3RequestFromJSON(json: any): SetCheckImpactV3Request {
    return SetCheckImpactV3RequestFromJSONTyped(json, false);
}

export function SetCheckImpactV3RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCheckImpactV3Request {
    if (json == null) {
        return json;
    }
    return {
        allFutureInstances: json["all_future_instances"] == null ? undefined : json["all_future_instances"],
        impact: json["impact"],
        reason: json["reason"] == null ? undefined : json["reason"],
    };
}

export function SetCheckImpactV3RequestToJSON(value?: SetCheckImpactV3Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        all_future_instances: value["allFutureInstances"],
        impact: value["impact"],
        reason: value["reason"],
    };
}
