/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TypesScanType } from "./TypesScanType";
import { TypesScanTypeFromJSON, TypesScanTypeFromJSONTyped, TypesScanTypeToJSON } from "./TypesScanType";
import type { TypesClassificationScanMode } from "./TypesClassificationScanMode";
import { TypesClassificationScanModeFromJSON, TypesClassificationScanModeFromJSONTyped, TypesClassificationScanModeToJSON } from "./TypesClassificationScanMode";

/**
 *
 * @export
 * @interface TypesDSPMScanningConfig
 */
export interface TypesDSPMScanningConfig {
    /**
     *
     * @type {TypesClassificationScanMode}
     * @memberof TypesDSPMScanningConfig
     */
    classificationScanMode?: TypesClassificationScanMode;
    /**
     *
     * @type {TypesScanType}
     * @memberof TypesDSPMScanningConfig
     */
    scanType?: TypesScanType;
}

/**
 * Check if a given object implements the TypesDSPMScanningConfig interface.
 */
export function instanceOfTypesDSPMScanningConfig(value: object): value is TypesDSPMScanningConfig {
    return true;
}

export function TypesDSPMScanningConfigFromJSON(json: any): TypesDSPMScanningConfig {
    return TypesDSPMScanningConfigFromJSONTyped(json, false);
}

export function TypesDSPMScanningConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesDSPMScanningConfig {
    if (json == null) {
        return json;
    }
    return {
        classificationScanMode: json["classification_scan_mode"] == null ? undefined : TypesClassificationScanModeFromJSON(json["classification_scan_mode"]),
        scanType: json["scan_type"] == null ? undefined : TypesScanTypeFromJSON(json["scan_type"]),
    };
}

export function TypesDSPMScanningConfigToJSON(value?: TypesDSPMScanningConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        classification_scan_mode: TypesClassificationScanModeToJSON(value["classificationScanMode"]),
        scan_type: TypesScanTypeToJSON(value["scanType"]),
    };
}
