/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UrlDomainListRequest
 */
export interface UrlDomainListRequest {
    /**
     * The ID of the integration.
     * @type {string}
     * @memberof UrlDomainListRequest
     */
    integrationId: string;
    /**
     * List of URLs and domains.
     * @type {Array<string>}
     * @memberof UrlDomainListRequest
     */
    urls: Array<string>;
}

/**
 * Check if a given object implements the UrlDomainListRequest interface.
 */
export function instanceOfUrlDomainListRequest(value: object): value is UrlDomainListRequest {
    if (!("integrationId" in value) || value["integrationId"] === undefined) return false;
    if (!("urls" in value) || value["urls"] === undefined) return false;
    return true;
}

export function UrlDomainListRequestFromJSON(json: any): UrlDomainListRequest {
    return UrlDomainListRequestFromJSONTyped(json, false);
}

export function UrlDomainListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UrlDomainListRequest {
    if (json == null) {
        return json;
    }
    return {
        integrationId: json["integrationId"],
        urls: json["urls"],
    };
}

export function UrlDomainListRequestToJSON(value?: UrlDomainListRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        integrationId: value["integrationId"],
        urls: value["urls"],
    };
}
