/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserinputViewModel
 */
export interface UserinputViewModel {
    /**
     * if not empty, only listed inputs are allowed
     * @type {Array<string>}
     * @memberof UserinputViewModel
     */
    allowedInputs: Array<string>;
    /**
     * if not empty, only listed responders are allowed to provide input
     * @type {Array<string>}
     * @memberof UserinputViewModel
     */
    allowedResponders: Array<string>;
    /**
     * whether or not the user input is completed yet
     * @type {boolean}
     * @memberof UserinputViewModel
     */
    completed: boolean;
    /**
     * time at which the user input was modified
     * @type {Date}
     * @memberof UserinputViewModel
     */
    completedAt: Date;
    /**
     * time at which the user input was created
     * @type {Date}
     * @memberof UserinputViewModel
     */
    createdAt: Date;
    /**
     * ID of the user input
     * @type {string}
     * @memberof UserinputViewModel
     */
    id: string;
    /**
     * input provided by a responder user
     * @type {string}
     * @memberof UserinputViewModel
     */
    input: string;
    /**
     * note added to user input at the time an input is provided
     * @type {string}
     * @memberof UserinputViewModel
     */
    note: string;
    /**
     * user responding to the user input request
     * @type {string}
     * @memberof UserinputViewModel
     */
    responder: string;
    /**
     * time after which the user input may be expired and no longer actionable
     * @type {Date}
     * @memberof UserinputViewModel
     */
    timeoutAt: Date;
}

/**
 * Check if a given object implements the UserinputViewModel interface.
 */
export function instanceOfUserinputViewModel(value: object): value is UserinputViewModel {
    if (!("allowedInputs" in value) || value["allowedInputs"] === undefined) return false;
    if (!("allowedResponders" in value) || value["allowedResponders"] === undefined) return false;
    if (!("completed" in value) || value["completed"] === undefined) return false;
    if (!("completedAt" in value) || value["completedAt"] === undefined) return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("input" in value) || value["input"] === undefined) return false;
    if (!("note" in value) || value["note"] === undefined) return false;
    if (!("responder" in value) || value["responder"] === undefined) return false;
    if (!("timeoutAt" in value) || value["timeoutAt"] === undefined) return false;
    return true;
}

export function UserinputViewModelFromJSON(json: any): UserinputViewModel {
    return UserinputViewModelFromJSONTyped(json, false);
}

export function UserinputViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserinputViewModel {
    if (json == null) {
        return json;
    }
    return {
        allowedInputs: json["allowed_inputs"],
        allowedResponders: json["allowed_responders"],
        completed: json["completed"],
        completedAt: new Date(json["completed_at"]),
        createdAt: new Date(json["created_at"]),
        id: json["id"],
        input: json["input"],
        note: json["note"],
        responder: json["responder"],
        timeoutAt: new Date(json["timeout_at"]),
    };
}

export function UserinputViewModelToJSON(value?: UserinputViewModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        allowed_inputs: value["allowedInputs"],
        allowed_responders: value["allowedResponders"],
        completed: value["completed"],
        completed_at: value["completedAt"].toISOString(),
        created_at: value["createdAt"].toISOString(),
        id: value["id"],
        input: value["input"],
        note: value["note"],
        responder: value["responder"],
        timeout_at: value["timeoutAt"].toISOString(),
    };
}
